// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datahub/v1alpha2/datahub.proto

package containersai_datahub_v1alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha2 "datahub/metric/v1alpha2"
import v1alpha23 "datahub/prediction/v1alpha2"
import v1alpha24 "datahub/recommendation/v1alpha2"
import v1alpha21 "datahub/resource/metadata/v1alpha2"
import v1alpha22 "datahub/resource/v1alpha2"
import v1alpha25 "datahub/score/v1alpha2"
import status "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryCondition_Order int32

const (
	QueryCondition_ASC  QueryCondition_Order = 0
	QueryCondition_DESC QueryCondition_Order = 1
)

var QueryCondition_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var QueryCondition_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x QueryCondition_Order) String() string {
	return proto.EnumName(QueryCondition_Order_name, int32(x))
}
func (QueryCondition_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{0, 0}
}

type QueryCondition struct {
	TimeRange            *v1alpha2.TimeRange  `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Order                QueryCondition_Order `protobuf:"varint,2,opt,name=order,proto3,enum=containersai.datahub.v1alpha2.QueryCondition_Order" json:"order,omitempty"`
	Limit                uint64               `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryCondition) Reset()         { *m = QueryCondition{} }
func (m *QueryCondition) String() string { return proto.CompactTextString(m) }
func (*QueryCondition) ProtoMessage()    {}
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{0}
}
func (m *QueryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCondition.Unmarshal(m, b)
}
func (m *QueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCondition.Marshal(b, m, deterministic)
}
func (dst *QueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCondition.Merge(dst, src)
}
func (m *QueryCondition) XXX_Size() int {
	return xxx_messageInfo_QueryCondition.Size(m)
}
func (m *QueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCondition proto.InternalMessageInfo

func (m *QueryCondition) GetTimeRange() *v1alpha2.TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *QueryCondition) GetOrder() QueryCondition_Order {
	if m != nil {
		return m.Order
	}
	return QueryCondition_ASC
}

func (m *QueryCondition) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// *
// Represents a request for listing metric data of a pod
//
type ListPodMetricsRequest struct {
	NamespacedName       *v1alpha21.NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	QueryCondition       *QueryCondition           `protobuf:"bytes,2,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPodMetricsRequest) Reset()         { *m = ListPodMetricsRequest{} }
func (m *ListPodMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodMetricsRequest) ProtoMessage()    {}
func (*ListPodMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{1}
}
func (m *ListPodMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodMetricsRequest.Unmarshal(m, b)
}
func (m *ListPodMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodMetricsRequest.Merge(dst, src)
}
func (m *ListPodMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodMetricsRequest.Size(m)
}
func (m *ListPodMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodMetricsRequest proto.InternalMessageInfo

func (m *ListPodMetricsRequest) GetNamespacedName() *v1alpha21.NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodMetricsRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for a listing pod metric data request
//
type ListPodMetricsResponse struct {
	Status               *status.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodMetrics           []*v1alpha2.PodMetric `protobuf:"bytes,2,rep,name=pod_metrics,json=podMetrics,proto3" json:"pod_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListPodMetricsResponse) Reset()         { *m = ListPodMetricsResponse{} }
func (m *ListPodMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodMetricsResponse) ProtoMessage()    {}
func (*ListPodMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{2}
}
func (m *ListPodMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodMetricsResponse.Unmarshal(m, b)
}
func (m *ListPodMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodMetricsResponse.Merge(dst, src)
}
func (m *ListPodMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodMetricsResponse.Size(m)
}
func (m *ListPodMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodMetricsResponse proto.InternalMessageInfo

func (m *ListPodMetricsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodMetricsResponse) GetPodMetrics() []*v1alpha2.PodMetric {
	if m != nil {
		return m.PodMetrics
	}
	return nil
}

// *
// Represents a request for listing metric data of a node
//
type ListNodeMetricsRequest struct {
	NodeNames            []string        `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	QueryCondition       *QueryCondition `protobuf:"bytes,2,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListNodeMetricsRequest) Reset()         { *m = ListNodeMetricsRequest{} }
func (m *ListNodeMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodeMetricsRequest) ProtoMessage()    {}
func (*ListNodeMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{3}
}
func (m *ListNodeMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeMetricsRequest.Unmarshal(m, b)
}
func (m *ListNodeMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *ListNodeMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeMetricsRequest.Merge(dst, src)
}
func (m *ListNodeMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodeMetricsRequest.Size(m)
}
func (m *ListNodeMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeMetricsRequest proto.InternalMessageInfo

func (m *ListNodeMetricsRequest) GetNodeNames() []string {
	if m != nil {
		return m.NodeNames
	}
	return nil
}

func (m *ListNodeMetricsRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for a listing node metrics request
//
type ListNodeMetricsResponse struct {
	Status               *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeMetrics          []*v1alpha2.NodeMetric `protobuf:"bytes,2,rep,name=node_metrics,json=nodeMetrics,proto3" json:"node_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListNodeMetricsResponse) Reset()         { *m = ListNodeMetricsResponse{} }
func (m *ListNodeMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodeMetricsResponse) ProtoMessage()    {}
func (*ListNodeMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{4}
}
func (m *ListNodeMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeMetricsResponse.Unmarshal(m, b)
}
func (m *ListNodeMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodeMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeMetricsResponse.Merge(dst, src)
}
func (m *ListNodeMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodeMetricsResponse.Size(m)
}
func (m *ListNodeMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeMetricsResponse proto.InternalMessageInfo

func (m *ListNodeMetricsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodeMetricsResponse) GetNodeMetrics() []*v1alpha2.NodeMetric {
	if m != nil {
		return m.NodeMetrics
	}
	return nil
}

// *
// Represents a response for a listing pods request
//
type ListPodsResponse struct {
	Status               *status.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pods                 []*v1alpha22.Pod `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPodsResponse) Reset()         { *m = ListPodsResponse{} }
func (m *ListPodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodsResponse) ProtoMessage()    {}
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{5}
}
func (m *ListPodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsResponse.Unmarshal(m, b)
}
func (m *ListPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsResponse.Merge(dst, src)
}
func (m *ListPodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodsResponse.Size(m)
}
func (m *ListPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsResponse proto.InternalMessageInfo

func (m *ListPodsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodsResponse) GetPods() []*v1alpha22.Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for listing pods
//
type ListPodsRequest struct {
	Scaler               *v1alpha21.NamespacedName `protobuf:"bytes,1,opt,name=scaler,proto3" json:"scaler,omitempty"`
	Predict              bool                      `protobuf:"varint,2,opt,name=predict,proto3" json:"predict,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPodsRequest) Reset()         { *m = ListPodsRequest{} }
func (m *ListPodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodsRequest) ProtoMessage()    {}
func (*ListPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{6}
}
func (m *ListPodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsRequest.Unmarshal(m, b)
}
func (m *ListPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsRequest.Merge(dst, src)
}
func (m *ListPodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodsRequest.Size(m)
}
func (m *ListPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsRequest proto.InternalMessageInfo

func (m *ListPodsRequest) GetScaler() *v1alpha21.NamespacedName {
	if m != nil {
		return m.Scaler
	}
	return nil
}

func (m *ListPodsRequest) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

// *
// Represents a request for listing nodes
//
type ListNodesRequest struct {
	Predict              bool     `protobuf:"varint,1,opt,name=predict,proto3" json:"predict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{7}
}
func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (dst *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(dst, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

func (m *ListNodesRequest) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

// *
// Represents a response for a listing nodes request
//
type ListNodesResponse struct {
	Status               *status.Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Nodes                []*v1alpha22.Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{8}
}
func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(dst, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodesResponse) GetNodes() []*v1alpha22.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// *
// Represents a request for listing predictions of pods
//
type ListPodPredictionsRequest struct {
	NamespacedName       *v1alpha21.NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	QueryCondition       *QueryCondition           `protobuf:"bytes,2,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPodPredictionsRequest) Reset()         { *m = ListPodPredictionsRequest{} }
func (m *ListPodPredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodPredictionsRequest) ProtoMessage()    {}
func (*ListPodPredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{9}
}
func (m *ListPodPredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodPredictionsRequest.Unmarshal(m, b)
}
func (m *ListPodPredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodPredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodPredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodPredictionsRequest.Merge(dst, src)
}
func (m *ListPodPredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodPredictionsRequest.Size(m)
}
func (m *ListPodPredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodPredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodPredictionsRequest proto.InternalMessageInfo

func (m *ListPodPredictionsRequest) GetNamespacedName() *v1alpha21.NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodPredictionsRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for a listing predictions of pods request
//
type ListPodPredictionsResponse struct {
	Status               *status.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodPredictions       []*v1alpha23.PodPrediction `protobuf:"bytes,2,rep,name=pod_predictions,json=podPredictions,proto3" json:"pod_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListPodPredictionsResponse) Reset()         { *m = ListPodPredictionsResponse{} }
func (m *ListPodPredictionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodPredictionsResponse) ProtoMessage()    {}
func (*ListPodPredictionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{10}
}
func (m *ListPodPredictionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodPredictionsResponse.Unmarshal(m, b)
}
func (m *ListPodPredictionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodPredictionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodPredictionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodPredictionsResponse.Merge(dst, src)
}
func (m *ListPodPredictionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodPredictionsResponse.Size(m)
}
func (m *ListPodPredictionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodPredictionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodPredictionsResponse proto.InternalMessageInfo

func (m *ListPodPredictionsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodPredictionsResponse) GetPodPredictions() []*v1alpha23.PodPrediction {
	if m != nil {
		return m.PodPredictions
	}
	return nil
}

// *
// Represents a request for listing predictions of nodes
//
type ListNodePredictionsRequest struct {
	NodeNames            []string        `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	QueryCondition       *QueryCondition `protobuf:"bytes,2,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListNodePredictionsRequest) Reset()         { *m = ListNodePredictionsRequest{} }
func (m *ListNodePredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodePredictionsRequest) ProtoMessage()    {}
func (*ListNodePredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{11}
}
func (m *ListNodePredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodePredictionsRequest.Unmarshal(m, b)
}
func (m *ListNodePredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodePredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListNodePredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodePredictionsRequest.Merge(dst, src)
}
func (m *ListNodePredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodePredictionsRequest.Size(m)
}
func (m *ListNodePredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodePredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodePredictionsRequest proto.InternalMessageInfo

func (m *ListNodePredictionsRequest) GetNodeNames() []string {
	if m != nil {
		return m.NodeNames
	}
	return nil
}

func (m *ListNodePredictionsRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for a listing predictions of nodes request
//
type ListNodePredictionsResponse struct {
	Status               *status.Status              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodePredictions      []*v1alpha23.NodePrediction `protobuf:"bytes,2,rep,name=node_predictions,json=nodePredictions,proto3" json:"node_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListNodePredictionsResponse) Reset()         { *m = ListNodePredictionsResponse{} }
func (m *ListNodePredictionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodePredictionsResponse) ProtoMessage()    {}
func (*ListNodePredictionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{12}
}
func (m *ListNodePredictionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodePredictionsResponse.Unmarshal(m, b)
}
func (m *ListNodePredictionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodePredictionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListNodePredictionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodePredictionsResponse.Merge(dst, src)
}
func (m *ListNodePredictionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodePredictionsResponse.Size(m)
}
func (m *ListNodePredictionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodePredictionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodePredictionsResponse proto.InternalMessageInfo

func (m *ListNodePredictionsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodePredictionsResponse) GetNodePredictions() []*v1alpha23.NodePrediction {
	if m != nil {
		return m.NodePredictions
	}
	return nil
}

// *
// Represents a request for listing recommendations of pods
//
type ListPodRecommendationsRequest struct {
	NamespacedName       *v1alpha21.NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	QueryCondition       *QueryCondition           `protobuf:"bytes,2,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPodRecommendationsRequest) Reset()         { *m = ListPodRecommendationsRequest{} }
func (m *ListPodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsRequest) ProtoMessage()    {}
func (*ListPodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{13}
}
func (m *ListPodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListPodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsRequest.Merge(dst, src)
}
func (m *ListPodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsRequest.Size(m)
}
func (m *ListPodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsRequest proto.InternalMessageInfo

func (m *ListPodRecommendationsRequest) GetNamespacedName() *v1alpha21.NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *ListPodRecommendationsRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for listing pod recommendations request
//
type ListPodRecommendationsResponse struct {
	Status               *status.Status                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodRecommendations   []*v1alpha24.PodRecommendation `protobuf:"bytes,2,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListPodRecommendationsResponse) Reset()         { *m = ListPodRecommendationsResponse{} }
func (m *ListPodRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsResponse) ProtoMessage()    {}
func (*ListPodRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{14}
}
func (m *ListPodRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListPodRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPodRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsResponse.Merge(dst, src)
}
func (m *ListPodRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsResponse.Size(m)
}
func (m *ListPodRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsResponse proto.InternalMessageInfo

func (m *ListPodRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodRecommendationsResponse) GetPodRecommendations() []*v1alpha24.PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

// *
// Represents a request for listing pods by nodes' name
//
type ListPodsByNodeNamesRequest struct {
	NodeNames            []string `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPodsByNodeNamesRequest) Reset()         { *m = ListPodsByNodeNamesRequest{} }
func (m *ListPodsByNodeNamesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodsByNodeNamesRequest) ProtoMessage()    {}
func (*ListPodsByNodeNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{15}
}
func (m *ListPodsByNodeNamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsByNodeNamesRequest.Unmarshal(m, b)
}
func (m *ListPodsByNodeNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsByNodeNamesRequest.Marshal(b, m, deterministic)
}
func (dst *ListPodsByNodeNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsByNodeNamesRequest.Merge(dst, src)
}
func (m *ListPodsByNodeNamesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodsByNodeNamesRequest.Size(m)
}
func (m *ListPodsByNodeNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsByNodeNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsByNodeNamesRequest proto.InternalMessageInfo

func (m *ListPodsByNodeNamesRequest) GetNodeNames() []string {
	if m != nil {
		return m.NodeNames
	}
	return nil
}

// *
// Represents a request for listing system scores of pod scheduled on node
//
type ListSimulatedSchedulingScoresRequest struct {
	QueryCondition       *QueryCondition `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSimulatedSchedulingScoresRequest) Reset()         { *m = ListSimulatedSchedulingScoresRequest{} }
func (m *ListSimulatedSchedulingScoresRequest) String() string { return proto.CompactTextString(m) }
func (*ListSimulatedSchedulingScoresRequest) ProtoMessage()    {}
func (*ListSimulatedSchedulingScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{16}
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Unmarshal(m, b)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Marshal(b, m, deterministic)
}
func (dst *ListSimulatedSchedulingScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Merge(dst, src)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_Size() int {
	return xxx_messageInfo_ListSimulatedSchedulingScoresRequest.Size(m)
}
func (m *ListSimulatedSchedulingScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSimulatedSchedulingScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSimulatedSchedulingScoresRequest proto.InternalMessageInfo

func (m *ListSimulatedSchedulingScoresRequest) GetQueryCondition() *QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

// *
// Represents a response for listing system scores request
//
type ListSimulatedSchedulingScoresResponse struct {
	Status               *status.Status                        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Scores               []*v1alpha25.SimulatedSchedulingScore `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListSimulatedSchedulingScoresResponse) Reset()         { *m = ListSimulatedSchedulingScoresResponse{} }
func (m *ListSimulatedSchedulingScoresResponse) String() string { return proto.CompactTextString(m) }
func (*ListSimulatedSchedulingScoresResponse) ProtoMessage()    {}
func (*ListSimulatedSchedulingScoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{17}
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Unmarshal(m, b)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Marshal(b, m, deterministic)
}
func (dst *ListSimulatedSchedulingScoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Merge(dst, src)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_Size() int {
	return xxx_messageInfo_ListSimulatedSchedulingScoresResponse.Size(m)
}
func (m *ListSimulatedSchedulingScoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSimulatedSchedulingScoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSimulatedSchedulingScoresResponse proto.InternalMessageInfo

func (m *ListSimulatedSchedulingScoresResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListSimulatedSchedulingScoresResponse) GetScores() []*v1alpha25.SimulatedSchedulingScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

// *
// Represents a request for creating predictions of containers' metric data belonging to a pod
type CreatePodPredictionsRequest struct {
	PodPredictions       []*v1alpha23.PodPrediction `protobuf:"bytes,1,rep,name=pod_predictions,json=podPredictions,proto3" json:"pod_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreatePodPredictionsRequest) Reset()         { *m = CreatePodPredictionsRequest{} }
func (m *CreatePodPredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodPredictionsRequest) ProtoMessage()    {}
func (*CreatePodPredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{18}
}
func (m *CreatePodPredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodPredictionsRequest.Unmarshal(m, b)
}
func (m *CreatePodPredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodPredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodPredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodPredictionsRequest.Merge(dst, src)
}
func (m *CreatePodPredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodPredictionsRequest.Size(m)
}
func (m *CreatePodPredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodPredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodPredictionsRequest proto.InternalMessageInfo

func (m *CreatePodPredictionsRequest) GetPodPredictions() []*v1alpha23.PodPrediction {
	if m != nil {
		return m.PodPredictions
	}
	return nil
}

// *
// Represents a request for creating predictions of a node metric data
//
type CreateNodePredictionsRequest struct {
	NodePredictions      []*v1alpha23.NodePrediction `protobuf:"bytes,1,rep,name=node_predictions,json=nodePredictions,proto3" json:"node_predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateNodePredictionsRequest) Reset()         { *m = CreateNodePredictionsRequest{} }
func (m *CreateNodePredictionsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNodePredictionsRequest) ProtoMessage()    {}
func (*CreateNodePredictionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{19}
}
func (m *CreateNodePredictionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodePredictionsRequest.Unmarshal(m, b)
}
func (m *CreateNodePredictionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodePredictionsRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNodePredictionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodePredictionsRequest.Merge(dst, src)
}
func (m *CreateNodePredictionsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNodePredictionsRequest.Size(m)
}
func (m *CreateNodePredictionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodePredictionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodePredictionsRequest proto.InternalMessageInfo

func (m *CreateNodePredictionsRequest) GetNodePredictions() []*v1alpha23.NodePrediction {
	if m != nil {
		return m.NodePredictions
	}
	return nil
}

// *
// Represents a request for creating a pod's recommendation
//
type CreatePodRecommendationsRequest struct {
	PodRecommendations   []*v1alpha24.PodRecommendation `protobuf:"bytes,1,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CreatePodRecommendationsRequest) Reset()         { *m = CreatePodRecommendationsRequest{} }
func (m *CreatePodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodRecommendationsRequest) ProtoMessage()    {}
func (*CreatePodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{20}
}
func (m *CreatePodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreatePodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodRecommendationsRequest.Merge(dst, src)
}
func (m *CreatePodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Size(m)
}
func (m *CreatePodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodRecommendationsRequest proto.InternalMessageInfo

func (m *CreatePodRecommendationsRequest) GetPodRecommendations() []*v1alpha24.PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

// *
// Represents a request for creating pods
//
type CreatePodsRequest struct {
	Pods                 []*v1alpha22.Pod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreatePodsRequest) Reset()         { *m = CreatePodsRequest{} }
func (m *CreatePodsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodsRequest) ProtoMessage()    {}
func (*CreatePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{21}
}
func (m *CreatePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodsRequest.Unmarshal(m, b)
}
func (m *CreatePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodsRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodsRequest.Merge(dst, src)
}
func (m *CreatePodsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodsRequest.Size(m)
}
func (m *CreatePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodsRequest proto.InternalMessageInfo

func (m *CreatePodsRequest) GetPods() []*v1alpha22.Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for adding nodes
//
type CreateNodesRequest struct {
	Nodes                []*v1alpha22.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Predict              bool              `protobuf:"varint,2,opt,name=predict,proto3" json:"predict,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateNodesRequest) Reset()         { *m = CreateNodesRequest{} }
func (m *CreateNodesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNodesRequest) ProtoMessage()    {}
func (*CreateNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{22}
}
func (m *CreateNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodesRequest.Unmarshal(m, b)
}
func (m *CreateNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodesRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodesRequest.Merge(dst, src)
}
func (m *CreateNodesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNodesRequest.Size(m)
}
func (m *CreateNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodesRequest proto.InternalMessageInfo

func (m *CreateNodesRequest) GetNodes() []*v1alpha22.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *CreateNodesRequest) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

// *
// Represents a request for adding scheduling scores produced by ai engine
//
type CreateSimulatedSchedulingScoresRequest struct {
	Scores               []*v1alpha25.SimulatedSchedulingScore `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *CreateSimulatedSchedulingScoresRequest) Reset() {
	*m = CreateSimulatedSchedulingScoresRequest{}
}
func (m *CreateSimulatedSchedulingScoresRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSimulatedSchedulingScoresRequest) ProtoMessage()    {}
func (*CreateSimulatedSchedulingScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{23}
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Unmarshal(m, b)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSimulatedSchedulingScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Merge(dst, src)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.Size(m)
}
func (m *CreateSimulatedSchedulingScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSimulatedSchedulingScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSimulatedSchedulingScoresRequest proto.InternalMessageInfo

func (m *CreateSimulatedSchedulingScoresRequest) GetScores() []*v1alpha25.SimulatedSchedulingScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

// *
// Represents a request for updating pods data
//
type UpdatePodsRequest struct {
	PodInfos             []*UpdatePodsRequest_PodInfo `protobuf:"bytes,1,rep,name=pod_infos,json=podInfos,proto3" json:"pod_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UpdatePodsRequest) Reset()         { *m = UpdatePodsRequest{} }
func (m *UpdatePodsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePodsRequest) ProtoMessage()    {}
func (*UpdatePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{24}
}
func (m *UpdatePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePodsRequest.Unmarshal(m, b)
}
func (m *UpdatePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePodsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePodsRequest.Merge(dst, src)
}
func (m *UpdatePodsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePodsRequest.Size(m)
}
func (m *UpdatePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePodsRequest proto.InternalMessageInfo

func (m *UpdatePodsRequest) GetPodInfos() []*UpdatePodsRequest_PodInfo {
	if m != nil {
		return m.PodInfos
	}
	return nil
}

type UpdatePodsRequest_PodInfo struct {
	Predict              bool     `protobuf:"varint,1,opt,name=predict,proto3" json:"predict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePodsRequest_PodInfo) Reset()         { *m = UpdatePodsRequest_PodInfo{} }
func (m *UpdatePodsRequest_PodInfo) String() string { return proto.CompactTextString(m) }
func (*UpdatePodsRequest_PodInfo) ProtoMessage()    {}
func (*UpdatePodsRequest_PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{24, 0}
}
func (m *UpdatePodsRequest_PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePodsRequest_PodInfo.Unmarshal(m, b)
}
func (m *UpdatePodsRequest_PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePodsRequest_PodInfo.Marshal(b, m, deterministic)
}
func (dst *UpdatePodsRequest_PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePodsRequest_PodInfo.Merge(dst, src)
}
func (m *UpdatePodsRequest_PodInfo) XXX_Size() int {
	return xxx_messageInfo_UpdatePodsRequest_PodInfo.Size(m)
}
func (m *UpdatePodsRequest_PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePodsRequest_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePodsRequest_PodInfo proto.InternalMessageInfo

func (m *UpdatePodsRequest_PodInfo) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

// *
// Represents a request for upating nodes
//
type UpdateNodesRequest struct {
	NodeInfos            []*UpdateNodesRequest_NodeInfo `protobuf:"bytes,1,rep,name=node_infos,json=nodeInfos,proto3" json:"node_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *UpdateNodesRequest) Reset()         { *m = UpdateNodesRequest{} }
func (m *UpdateNodesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodesRequest) ProtoMessage()    {}
func (*UpdateNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{25}
}
func (m *UpdateNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodesRequest.Unmarshal(m, b)
}
func (m *UpdateNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodesRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodesRequest.Merge(dst, src)
}
func (m *UpdateNodesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodesRequest.Size(m)
}
func (m *UpdateNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodesRequest proto.InternalMessageInfo

func (m *UpdateNodesRequest) GetNodeInfos() []*UpdateNodesRequest_NodeInfo {
	if m != nil {
		return m.NodeInfos
	}
	return nil
}

type UpdateNodesRequest_NodeInfo struct {
	Predict              bool     `protobuf:"varint,1,opt,name=predict,proto3" json:"predict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodesRequest_NodeInfo) Reset()         { *m = UpdateNodesRequest_NodeInfo{} }
func (m *UpdateNodesRequest_NodeInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateNodesRequest_NodeInfo) ProtoMessage()    {}
func (*UpdateNodesRequest_NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{25, 0}
}
func (m *UpdateNodesRequest_NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodesRequest_NodeInfo.Unmarshal(m, b)
}
func (m *UpdateNodesRequest_NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodesRequest_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *UpdateNodesRequest_NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodesRequest_NodeInfo.Merge(dst, src)
}
func (m *UpdateNodesRequest_NodeInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateNodesRequest_NodeInfo.Size(m)
}
func (m *UpdateNodesRequest_NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodesRequest_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodesRequest_NodeInfo proto.InternalMessageInfo

func (m *UpdateNodesRequest_NodeInfo) GetPredict() bool {
	if m != nil {
		return m.Predict
	}
	return false
}

// *
// Represents a request for deleting pods data
//
type DeletePodsRequest struct {
	Pods                 []*v1alpha22.Pod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeletePodsRequest) Reset()         { *m = DeletePodsRequest{} }
func (m *DeletePodsRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePodsRequest) ProtoMessage()    {}
func (*DeletePodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{26}
}
func (m *DeletePodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodsRequest.Unmarshal(m, b)
}
func (m *DeletePodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodsRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodsRequest.Merge(dst, src)
}
func (m *DeletePodsRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePodsRequest.Size(m)
}
func (m *DeletePodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodsRequest proto.InternalMessageInfo

func (m *DeletePodsRequest) GetPods() []*v1alpha22.Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

// *
// Represents a request for stoping nodes
//
type DeleteNodesRequest struct {
	Nodes                []*v1alpha22.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteNodesRequest) Reset()         { *m = DeleteNodesRequest{} }
func (m *DeleteNodesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNodesRequest) ProtoMessage()    {}
func (*DeleteNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datahub_cf778f9e80a418e0, []int{27}
}
func (m *DeleteNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodesRequest.Unmarshal(m, b)
}
func (m *DeleteNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodesRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodesRequest.Merge(dst, src)
}
func (m *DeleteNodesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNodesRequest.Size(m)
}
func (m *DeleteNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodesRequest proto.InternalMessageInfo

func (m *DeleteNodesRequest) GetNodes() []*v1alpha22.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCondition)(nil), "containersai.datahub.v1alpha2.QueryCondition")
	proto.RegisterType((*ListPodMetricsRequest)(nil), "containersai.datahub.v1alpha2.ListPodMetricsRequest")
	proto.RegisterType((*ListPodMetricsResponse)(nil), "containersai.datahub.v1alpha2.ListPodMetricsResponse")
	proto.RegisterType((*ListNodeMetricsRequest)(nil), "containersai.datahub.v1alpha2.ListNodeMetricsRequest")
	proto.RegisterType((*ListNodeMetricsResponse)(nil), "containersai.datahub.v1alpha2.ListNodeMetricsResponse")
	proto.RegisterType((*ListPodsResponse)(nil), "containersai.datahub.v1alpha2.ListPodsResponse")
	proto.RegisterType((*ListPodsRequest)(nil), "containersai.datahub.v1alpha2.ListPodsRequest")
	proto.RegisterType((*ListNodesRequest)(nil), "containersai.datahub.v1alpha2.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "containersai.datahub.v1alpha2.ListNodesResponse")
	proto.RegisterType((*ListPodPredictionsRequest)(nil), "containersai.datahub.v1alpha2.ListPodPredictionsRequest")
	proto.RegisterType((*ListPodPredictionsResponse)(nil), "containersai.datahub.v1alpha2.ListPodPredictionsResponse")
	proto.RegisterType((*ListNodePredictionsRequest)(nil), "containersai.datahub.v1alpha2.ListNodePredictionsRequest")
	proto.RegisterType((*ListNodePredictionsResponse)(nil), "containersai.datahub.v1alpha2.ListNodePredictionsResponse")
	proto.RegisterType((*ListPodRecommendationsRequest)(nil), "containersai.datahub.v1alpha2.ListPodRecommendationsRequest")
	proto.RegisterType((*ListPodRecommendationsResponse)(nil), "containersai.datahub.v1alpha2.ListPodRecommendationsResponse")
	proto.RegisterType((*ListPodsByNodeNamesRequest)(nil), "containersai.datahub.v1alpha2.ListPodsByNodeNamesRequest")
	proto.RegisterType((*ListSimulatedSchedulingScoresRequest)(nil), "containersai.datahub.v1alpha2.ListSimulatedSchedulingScoresRequest")
	proto.RegisterType((*ListSimulatedSchedulingScoresResponse)(nil), "containersai.datahub.v1alpha2.ListSimulatedSchedulingScoresResponse")
	proto.RegisterType((*CreatePodPredictionsRequest)(nil), "containersai.datahub.v1alpha2.CreatePodPredictionsRequest")
	proto.RegisterType((*CreateNodePredictionsRequest)(nil), "containersai.datahub.v1alpha2.CreateNodePredictionsRequest")
	proto.RegisterType((*CreatePodRecommendationsRequest)(nil), "containersai.datahub.v1alpha2.CreatePodRecommendationsRequest")
	proto.RegisterType((*CreatePodsRequest)(nil), "containersai.datahub.v1alpha2.CreatePodsRequest")
	proto.RegisterType((*CreateNodesRequest)(nil), "containersai.datahub.v1alpha2.CreateNodesRequest")
	proto.RegisterType((*CreateSimulatedSchedulingScoresRequest)(nil), "containersai.datahub.v1alpha2.CreateSimulatedSchedulingScoresRequest")
	proto.RegisterType((*UpdatePodsRequest)(nil), "containersai.datahub.v1alpha2.UpdatePodsRequest")
	proto.RegisterType((*UpdatePodsRequest_PodInfo)(nil), "containersai.datahub.v1alpha2.UpdatePodsRequest.PodInfo")
	proto.RegisterType((*UpdateNodesRequest)(nil), "containersai.datahub.v1alpha2.UpdateNodesRequest")
	proto.RegisterType((*UpdateNodesRequest_NodeInfo)(nil), "containersai.datahub.v1alpha2.UpdateNodesRequest.NodeInfo")
	proto.RegisterType((*DeletePodsRequest)(nil), "containersai.datahub.v1alpha2.DeletePodsRequest")
	proto.RegisterType((*DeleteNodesRequest)(nil), "containersai.datahub.v1alpha2.DeleteNodesRequest")
	proto.RegisterEnum("containersai.datahub.v1alpha2.QueryCondition_Order", QueryCondition_Order_name, QueryCondition_Order_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatahubServiceClient is the client API for DatahubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatahubServiceClient interface {
	// / Used to list pod metric data
	ListPodMetrics(ctx context.Context, in *ListPodMetricsRequest, opts ...grpc.CallOption) (*ListPodMetricsResponse, error)
	// / Used to list node metric data
	ListNodeMetrics(ctx context.Context, in *ListNodeMetricsRequest, opts ...grpc.CallOption) (*ListNodeMetricsResponse, error)
	// Used to list pods
	ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	// Used to list nodes
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// / Used to list pod predictions
	ListPodPredictions(ctx context.Context, in *ListPodPredictionsRequest, opts ...grpc.CallOption) (*ListPodPredictionsResponse, error)
	// / Used to list node predictions
	ListNodePredictions(ctx context.Context, in *ListNodePredictionsRequest, opts ...grpc.CallOption) (*ListNodePredictionsResponse, error)
	// / Used to list pod recommenations
	ListPodRecommendations(ctx context.Context, in *ListPodRecommendationsRequest, opts ...grpc.CallOption) (*ListPodRecommendationsResponse, error)
	// / Used to list pods by a node name
	ListPodsByNodeName(ctx context.Context, in *ListPodsByNodeNamesRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	// / Used to list system scores
	ListSimulatedSchedulingScores(ctx context.Context, in *ListSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*ListSimulatedSchedulingScoresResponse, error)
	// / Used to add pods that need to be predicted
	CreatePods(ctx context.Context, in *CreatePodsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to add nodes
	CreateNodes(ctx context.Context, in *CreateNodesRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create predictions of pods
	CreatePodPredictions(ctx context.Context, in *CreatePodPredictionsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create predictions of nodes
	CreateNodePredictions(ctx context.Context, in *CreateNodePredictionsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create recommendations of pods
	CreatePodRecommendations(ctx context.Context, in *CreatePodRecommendationsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to create scores of system
	CreateSimulatedSchedulingScores(ctx context.Context, in *CreateSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to update info of pods
	UpdatePods(ctx context.Context, in *UpdatePodsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to update info of nodes
	UpdateNodes(ctx context.Context, in *UpdateNodesRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to delete info of pods
	DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*status.Status, error)
	// / Used to delete info of nodes
	DeleteNodes(ctx context.Context, in *DeleteNodesRequest, opts ...grpc.CallOption) (*status.Status, error)
}

type datahubServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatahubServiceClient(cc *grpc.ClientConn) DatahubServiceClient {
	return &datahubServiceClient{cc}
}

func (c *datahubServiceClient) ListPodMetrics(ctx context.Context, in *ListPodMetricsRequest, opts ...grpc.CallOption) (*ListPodMetricsResponse, error) {
	out := new(ListPodMetricsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListPodMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListNodeMetrics(ctx context.Context, in *ListNodeMetricsRequest, opts ...grpc.CallOption) (*ListNodeMetricsResponse, error) {
	out := new(ListNodeMetricsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListNodeMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodPredictions(ctx context.Context, in *ListPodPredictionsRequest, opts ...grpc.CallOption) (*ListPodPredictionsResponse, error) {
	out := new(ListPodPredictionsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListPodPredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListNodePredictions(ctx context.Context, in *ListNodePredictionsRequest, opts ...grpc.CallOption) (*ListNodePredictionsResponse, error) {
	out := new(ListNodePredictionsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListNodePredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodRecommendations(ctx context.Context, in *ListPodRecommendationsRequest, opts ...grpc.CallOption) (*ListPodRecommendationsResponse, error) {
	out := new(ListPodRecommendationsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListPodRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListPodsByNodeName(ctx context.Context, in *ListPodsByNodeNamesRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListPodsByNodeName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) ListSimulatedSchedulingScores(ctx context.Context, in *ListSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*ListSimulatedSchedulingScoresResponse, error) {
	out := new(ListSimulatedSchedulingScoresResponse)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/ListSimulatedSchedulingScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePods(ctx context.Context, in *CreatePodsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreatePods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateNodes(ctx context.Context, in *CreateNodesRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreateNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePodPredictions(ctx context.Context, in *CreatePodPredictionsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreatePodPredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateNodePredictions(ctx context.Context, in *CreateNodePredictionsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreateNodePredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreatePodRecommendations(ctx context.Context, in *CreatePodRecommendationsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreatePodRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) CreateSimulatedSchedulingScores(ctx context.Context, in *CreateSimulatedSchedulingScoresRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/CreateSimulatedSchedulingScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) UpdatePods(ctx context.Context, in *UpdatePodsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/UpdatePods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) UpdateNodes(ctx context.Context, in *UpdateNodesRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/UpdateNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/DeletePods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubServiceClient) DeleteNodes(ctx context.Context, in *DeleteNodesRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/containersai.datahub.v1alpha2.DatahubService/DeleteNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatahubServiceServer is the server API for DatahubService service.
type DatahubServiceServer interface {
	// / Used to list pod metric data
	ListPodMetrics(context.Context, *ListPodMetricsRequest) (*ListPodMetricsResponse, error)
	// / Used to list node metric data
	ListNodeMetrics(context.Context, *ListNodeMetricsRequest) (*ListNodeMetricsResponse, error)
	// Used to list pods
	ListPods(context.Context, *ListPodsRequest) (*ListPodsResponse, error)
	// Used to list nodes
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// / Used to list pod predictions
	ListPodPredictions(context.Context, *ListPodPredictionsRequest) (*ListPodPredictionsResponse, error)
	// / Used to list node predictions
	ListNodePredictions(context.Context, *ListNodePredictionsRequest) (*ListNodePredictionsResponse, error)
	// / Used to list pod recommenations
	ListPodRecommendations(context.Context, *ListPodRecommendationsRequest) (*ListPodRecommendationsResponse, error)
	// / Used to list pods by a node name
	ListPodsByNodeName(context.Context, *ListPodsByNodeNamesRequest) (*ListPodsResponse, error)
	// / Used to list system scores
	ListSimulatedSchedulingScores(context.Context, *ListSimulatedSchedulingScoresRequest) (*ListSimulatedSchedulingScoresResponse, error)
	// / Used to add pods that need to be predicted
	CreatePods(context.Context, *CreatePodsRequest) (*status.Status, error)
	// / Used to add nodes
	CreateNodes(context.Context, *CreateNodesRequest) (*status.Status, error)
	// / Used to create predictions of pods
	CreatePodPredictions(context.Context, *CreatePodPredictionsRequest) (*status.Status, error)
	// / Used to create predictions of nodes
	CreateNodePredictions(context.Context, *CreateNodePredictionsRequest) (*status.Status, error)
	// / Used to create recommendations of pods
	CreatePodRecommendations(context.Context, *CreatePodRecommendationsRequest) (*status.Status, error)
	// / Used to create scores of system
	CreateSimulatedSchedulingScores(context.Context, *CreateSimulatedSchedulingScoresRequest) (*status.Status, error)
	// / Used to update info of pods
	UpdatePods(context.Context, *UpdatePodsRequest) (*status.Status, error)
	// / Used to update info of nodes
	UpdateNodes(context.Context, *UpdateNodesRequest) (*status.Status, error)
	// / Used to delete info of pods
	DeletePods(context.Context, *DeletePodsRequest) (*status.Status, error)
	// / Used to delete info of nodes
	DeleteNodes(context.Context, *DeleteNodesRequest) (*status.Status, error)
}

func RegisterDatahubServiceServer(s *grpc.Server, srv DatahubServiceServer) {
	s.RegisterService(&_DatahubService_serviceDesc, srv)
}

func _DatahubService_ListPodMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListPodMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodMetrics(ctx, req.(*ListPodMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListNodeMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListNodeMetrics(ctx, req.(*ListNodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPods(ctx, req.(*ListPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodPredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodPredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodPredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListPodPredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodPredictions(ctx, req.(*ListPodPredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListNodePredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodePredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListNodePredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListNodePredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListNodePredictions(ctx, req.(*ListNodePredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListPodRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodRecommendations(ctx, req.(*ListPodRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListPodsByNodeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsByNodeNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListPodsByNodeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListPodsByNodeName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListPodsByNodeName(ctx, req.(*ListPodsByNodeNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_ListSimulatedSchedulingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimulatedSchedulingScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).ListSimulatedSchedulingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/ListSimulatedSchedulingScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).ListSimulatedSchedulingScores(ctx, req.(*ListSimulatedSchedulingScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreatePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePods(ctx, req.(*CreatePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateNodes(ctx, req.(*CreateNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePodPredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodPredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePodPredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreatePodPredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePodPredictions(ctx, req.(*CreatePodPredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateNodePredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodePredictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateNodePredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreateNodePredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateNodePredictions(ctx, req.(*CreateNodePredictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreatePodRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreatePodRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreatePodRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreatePodRecommendations(ctx, req.(*CreatePodRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_CreateSimulatedSchedulingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimulatedSchedulingScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).CreateSimulatedSchedulingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/CreateSimulatedSchedulingScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).CreateSimulatedSchedulingScores(ctx, req.(*CreateSimulatedSchedulingScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_UpdatePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).UpdatePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/UpdatePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).UpdatePods(ctx, req.(*UpdatePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_UpdateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).UpdateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/UpdateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).UpdateNodes(ctx, req.(*UpdateNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_DeletePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).DeletePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/DeletePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).DeletePods(ctx, req.(*DeletePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatahubService_DeleteNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServiceServer).DeleteNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containersai.datahub.v1alpha2.DatahubService/DeleteNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServiceServer).DeleteNodes(ctx, req.(*DeleteNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatahubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "containersai.datahub.v1alpha2.DatahubService",
	HandlerType: (*DatahubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPodMetrics",
			Handler:    _DatahubService_ListPodMetrics_Handler,
		},
		{
			MethodName: "ListNodeMetrics",
			Handler:    _DatahubService_ListNodeMetrics_Handler,
		},
		{
			MethodName: "ListPods",
			Handler:    _DatahubService_ListPods_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _DatahubService_ListNodes_Handler,
		},
		{
			MethodName: "ListPodPredictions",
			Handler:    _DatahubService_ListPodPredictions_Handler,
		},
		{
			MethodName: "ListNodePredictions",
			Handler:    _DatahubService_ListNodePredictions_Handler,
		},
		{
			MethodName: "ListPodRecommendations",
			Handler:    _DatahubService_ListPodRecommendations_Handler,
		},
		{
			MethodName: "ListPodsByNodeName",
			Handler:    _DatahubService_ListPodsByNodeName_Handler,
		},
		{
			MethodName: "ListSimulatedSchedulingScores",
			Handler:    _DatahubService_ListSimulatedSchedulingScores_Handler,
		},
		{
			MethodName: "CreatePods",
			Handler:    _DatahubService_CreatePods_Handler,
		},
		{
			MethodName: "CreateNodes",
			Handler:    _DatahubService_CreateNodes_Handler,
		},
		{
			MethodName: "CreatePodPredictions",
			Handler:    _DatahubService_CreatePodPredictions_Handler,
		},
		{
			MethodName: "CreateNodePredictions",
			Handler:    _DatahubService_CreateNodePredictions_Handler,
		},
		{
			MethodName: "CreatePodRecommendations",
			Handler:    _DatahubService_CreatePodRecommendations_Handler,
		},
		{
			MethodName: "CreateSimulatedSchedulingScores",
			Handler:    _DatahubService_CreateSimulatedSchedulingScores_Handler,
		},
		{
			MethodName: "UpdatePods",
			Handler:    _DatahubService_UpdatePods_Handler,
		},
		{
			MethodName: "UpdateNodes",
			Handler:    _DatahubService_UpdateNodes_Handler,
		},
		{
			MethodName: "DeletePods",
			Handler:    _DatahubService_DeletePods_Handler,
		},
		{
			MethodName: "DeleteNodes",
			Handler:    _DatahubService_DeleteNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datahub/v1alpha2/datahub.proto",
}

func init() {
	proto.RegisterFile("datahub/v1alpha2/datahub.proto", fileDescriptor_datahub_cf778f9e80a418e0)
}

var fileDescriptor_datahub_cf778f9e80a418e0 = []byte{
	// 1292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0xcf, 0x34, 0xff, 0x5f, 0xd0, 0x26, 0x99, 0xb6, 0x74, 0x71, 0x49, 0x89, 0x4c, 0x40, 0x11,
	0x04, 0x6f, 0x93, 0x16, 0x68, 0x53, 0x4a, 0x45, 0x93, 0x1e, 0x2a, 0x41, 0x08, 0xde, 0xa4, 0xc0,
	0x29, 0xb8, 0xf6, 0x34, 0x31, 0xda, 0xb5, 0x1d, 0xdb, 0x5b, 0xa9, 0x97, 0x46, 0xa2, 0xdc, 0x90,
	0xe8, 0xa1, 0x02, 0x24, 0x3e, 0x02, 0x42, 0x1c, 0x39, 0xf2, 0x3d, 0x38, 0x70, 0xe0, 0x9b, 0xa0,
	0xb1, 0x67, 0xc6, 0x76, 0x3c, 0x8e, 0x27, 0x66, 0xab, 0x4a, 0xbd, 0xd9, 0xb3, 0xef, 0xcf, 0x6f,
	0x7e, 0xef, 0xcd, 0x9b, 0x9f, 0x13, 0xb8, 0xe4, 0x58, 0xb1, 0x75, 0x30, 0xb8, 0xdf, 0x79, 0xb8,
	0x6a, 0xf5, 0x82, 0x03, 0x6b, 0xad, 0xc3, 0x16, 0x8c, 0x20, 0xf4, 0x63, 0x1f, 0x2f, 0xd8, 0xbe,
	0x17, 0x5b, 0xae, 0x47, 0xc2, 0xc8, 0x72, 0x0d, 0xfe, 0x1b, 0x37, 0xd6, 0x2e, 0xec, 0xfb, 0xfe,
	0x7e, 0x8f, 0x74, 0xc2, 0xc0, 0xee, 0x44, 0xb1, 0x15, 0x0f, 0xa2, 0xd4, 0x4f, 0x5b, 0xe5, 0x71,
	0x43, 0x12, 0xf9, 0x83, 0xd0, 0x26, 0x9d, 0x3e, 0x89, 0x2d, 0xba, 0x98, 0x65, 0xe2, 0x2b, 0xcc,
	0x65, 0xb9, 0xe4, 0x22, 0x2c, 0xf9, 0x0a, 0xb3, 0x5c, 0xe1, 0x96, 0x41, 0x48, 0x1c, 0xd7, 0x8e,
	0x5d, 0xdf, 0xcb, 0x6c, 0xb3, 0x35, 0x66, 0xbd, 0xc4, 0xad, 0xfb, 0x24, 0x0e, 0x5d, 0xbb, 0x90,
	0x3f, 0x74, 0x6d, 0x66, 0x75, 0x35, 0xcb, 0x6e, 0xfb, 0xfd, 0x3e, 0xf1, 0x1c, 0xab, 0x18, 0xb7,
	0xb8, 0xce, 0xbc, 0x74, 0xee, 0x15, 0xd9, 0x7e, 0x98, 0x03, 0x9c, 0xbc, 0xa6, 0x36, 0xfa, 0x3f,
	0x08, 0x5a, 0x5f, 0x0c, 0x48, 0xf8, 0x68, 0xc3, 0xf7, 0x1c, 0x97, 0x3a, 0xe3, 0x2d, 0x80, 0xd8,
	0xed, 0x93, 0xbd, 0xd0, 0xf2, 0xf6, 0x49, 0x1b, 0x2d, 0xa2, 0xe5, 0x99, 0xb5, 0x8e, 0x21, 0xa5,
	0x9a, 0x81, 0xe4, 0x91, 0x8d, 0x1d, 0xb7, 0x4f, 0x4c, 0xea, 0x66, 0x4e, 0xc7, 0xfc, 0x11, 0xdf,
	0x85, 0x71, 0x3f, 0x74, 0x48, 0xd8, 0x3e, 0xb3, 0x88, 0x96, 0x5b, 0x6b, 0x57, 0x8c, 0x13, 0xab,
	0x66, 0x14, 0xd1, 0x18, 0x9f, 0x53, 0x57, 0x33, 0x8d, 0x80, 0xcf, 0xc1, 0x78, 0xcf, 0xed, 0xbb,
	0x71, 0x7b, 0x74, 0x11, 0x2d, 0x8f, 0x99, 0xe9, 0x8b, 0xae, 0xc1, 0x78, 0x62, 0x85, 0x27, 0x61,
	0xf4, 0x93, 0xee, 0xc6, 0xdc, 0x08, 0x9e, 0x82, 0xb1, 0xcd, 0x3b, 0xdd, 0x8d, 0x39, 0xa4, 0xff,
	0x8d, 0xe0, 0xfc, 0xa7, 0x6e, 0x14, 0x6f, 0xfb, 0xce, 0x67, 0x09, 0xd8, 0xc8, 0x24, 0x87, 0x03,
	0x12, 0xc5, 0xf8, 0x00, 0x66, 0x3d, 0xab, 0x4f, 0xa2, 0xc0, 0xb2, 0x89, 0xb3, 0x47, 0x1f, 0xd9,
	0x5e, 0x6f, 0xc9, 0x01, 0x8a, 0x32, 0x8b, 0xce, 0x10, 0x90, 0xb7, 0x44, 0x1c, 0xfa, 0x64, 0xb6,
	0xbc, 0xc2, 0x3b, 0xbe, 0x07, 0xb3, 0x87, 0x74, 0x53, 0x7b, 0x36, 0xdf, 0x55, 0x42, 0xc5, 0xcc,
	0xda, 0x7b, 0xa7, 0xa2, 0xc2, 0x6c, 0x1d, 0x16, 0xde, 0xf5, 0x9f, 0x11, 0xbc, 0x7a, 0x7c, 0x6f,
	0x51, 0xe0, 0x7b, 0x11, 0xc1, 0xef, 0xc0, 0x44, 0xda, 0xf1, 0x6c, 0x4f, 0xd8, 0x48, 0xcf, 0x82,
	0x11, 0x06, 0xb6, 0xd1, 0x4d, 0x7e, 0x31, 0x99, 0x05, 0xde, 0x86, 0x99, 0xc0, 0x77, 0xf6, 0xd2,
	0x5a, 0x46, 0xed, 0x33, 0x8b, 0xa3, 0xea, 0x05, 0x17, 0xa9, 0x4d, 0x08, 0x04, 0x0a, 0xfd, 0x29,
	0x03, 0xb6, 0xe5, 0x3b, 0xe4, 0x18, 0xeb, 0x0b, 0x00, 0x9e, 0xef, 0x90, 0x84, 0x6f, 0x0a, 0x6e,
	0x74, 0x79, 0xda, 0x9c, 0xa6, 0x2b, 0x09, 0x87, 0xcf, 0x8d, 0xaa, 0x5f, 0x11, 0x5c, 0x28, 0x21,
	0x6a, 0xc0, 0x55, 0x17, 0x5e, 0x49, 0xe0, 0x17, 0xc9, 0xba, 0xac, 0x46, 0x56, 0x96, 0xdc, 0x9c,
	0xf1, 0x32, 0x20, 0xfa, 0x11, 0xcc, 0xb1, 0x32, 0x36, 0x03, 0x75, 0x0b, 0xc6, 0x02, 0xdf, 0xe1,
	0x60, 0xde, 0xad, 0x69, 0xdf, 0x7c, 0xed, 0xcc, 0xc4, 0x51, 0xff, 0x1e, 0xc1, 0x6c, 0x86, 0x20,
	0x2d, 0xd4, 0x97, 0x30, 0x11, 0xd9, 0x56, 0x8f, 0x84, 0xc3, 0x3a, 0x15, 0x2c, 0x1c, 0x6e, 0xc3,
	0x24, 0x9b, 0x82, 0x49, 0x69, 0xa7, 0x4c, 0xfe, 0xaa, 0xaf, 0xa4, 0x3c, 0x50, 0x9a, 0x04, 0x8c,
	0x9c, 0x35, 0x2a, 0x5a, 0x3f, 0x41, 0x30, 0x9f, 0x33, 0x6f, 0xc0, 0xdb, 0x6d, 0x18, 0xa7, 0x65,
	0xe0, 0xc4, 0xad, 0xa8, 0x12, 0x47, 0x33, 0x9a, 0xa9, 0x2b, 0x9d, 0x9f, 0xaf, 0x31, 0xea, 0xb6,
	0xc5, 0x6c, 0x7f, 0x89, 0x66, 0xcc, 0x6f, 0x08, 0x34, 0xd9, 0xfe, 0x1a, 0xd0, 0xfd, 0x0d, 0xcc,
	0xd2, 0x39, 0x93, 0x5d, 0x81, 0x9c, 0xf8, 0x0f, 0xe5, 0x10, 0x73, 0x77, 0x65, 0xbe, 0x67, 0x33,
	0x18, 0x66, 0x2b, 0x28, 0xa0, 0xd2, 0x9f, 0x31, 0xb0, 0xb4, 0x40, 0x92, 0x6a, 0xbc, 0xa0, 0xd9,
	0xf3, 0x07, 0x82, 0x8b, 0x52, 0x54, 0x0d, 0x38, 0xb4, 0x61, 0x2e, 0xd9, 0x42, 0x99, 0xc4, 0x6b,
	0xea, 0x24, 0x16, 0x81, 0x98, 0xb3, 0x5e, 0x11, 0x98, 0xfe, 0x2f, 0x82, 0x05, 0x56, 0x73, 0xb3,
	0xa0, 0x2b, 0x5e, 0xa2, 0xbe, 0xfe, 0x0b, 0xc1, 0xa5, 0xaa, 0x3d, 0x36, 0xa8, 0x4b, 0x00, 0x67,
	0x69, 0x6f, 0x17, 0x65, 0x18, 0x2f, 0x4d, 0x25, 0x29, 0x05, 0xcd, 0x56, 0x98, 0xcb, 0x85, 0x9f,
	0x4c, 0x1c, 0x94, 0x50, 0xea, 0x37, 0xc4, 0xb9, 0x8c, 0x6e, 0x3f, 0xda, 0xe2, 0x4d, 0xac, 0xd6,
	0xea, 0xfa, 0x63, 0x58, 0xa2, 0xce, 0x5d, 0xb7, 0x3f, 0xe8, 0x59, 0x31, 0x71, 0xba, 0xf6, 0x01,
	0x71, 0x06, 0x3d, 0xd7, 0xdb, 0xef, 0x52, 0x6d, 0x28, 0xc2, 0x48, 0xd8, 0x47, 0x43, 0x9a, 0x2a,
	0x6f, 0xd5, 0x00, 0x68, 0x50, 0x84, 0x5d, 0x7a, 0x65, 0x51, 0x6f, 0xc6, 0xfb, 0x4d, 0x39, 0xc8,
	0x54, 0xfe, 0x0a, 0xa8, 0x55, 0x18, 0x4c, 0x16, 0x4c, 0x3f, 0x82, 0x8b, 0x1b, 0x21, 0xb1, 0x62,
	0x22, 0x9f, 0xf1, 0x92, 0xb1, 0x86, 0x86, 0x3b, 0xd6, 0x9e, 0x20, 0x78, 0x3d, 0x45, 0x50, 0x31,
	0xd8, 0x64, 0x53, 0x01, 0x0d, 0x7b, 0x2a, 0x3c, 0x43, 0xf0, 0x86, 0xe0, 0xa1, 0x62, 0x2e, 0x54,
	0x1c, 0x03, 0xf4, 0xfc, 0x8e, 0xc1, 0x0e, 0xcc, 0x0b, 0x50, 0x02, 0x06, 0x17, 0x44, 0xa8, 0xa9,
	0x20, 0x0a, 0x01, 0x67, 0x84, 0x8b, 0xb0, 0x42, 0x2f, 0xa0, 0xc6, 0x7a, 0xe1, 0x04, 0xf5, 0x73,
	0x04, 0x6f, 0xa7, 0x39, 0x6b, 0x4f, 0x65, 0xd6, 0xe7, 0x68, 0x98, 0x7d, 0xfe, 0x14, 0xc1, 0xfc,
	0x6e, 0xe0, 0x1c, 0xe3, 0x72, 0x17, 0xa6, 0x69, 0x49, 0x5d, 0xef, 0x81, 0x5f, 0xd3, 0x54, 0x22,
	0x53, 0x29, 0x08, 0x65, 0xf6, 0xae, 0xf7, 0xc0, 0x37, 0xa7, 0x82, 0xf4, 0x21, 0xd2, 0xde, 0x84,
	0x49, 0xb6, 0x78, 0x82, 0xc4, 0xfb, 0x09, 0x01, 0x4e, 0x83, 0x15, 0xea, 0xf0, 0x35, 0x1b, 0x6e,
	0x79, 0x4c, 0xeb, 0x4a, 0x98, 0xf2, 0x61, 0x92, 0xb2, 0x24, 0xa8, 0x92, 0xc1, 0x98, 0xc2, 0x5a,
	0x82, 0x29, 0xbe, 0x7c, 0x02, 0xae, 0x1d, 0x98, 0xdf, 0x24, 0x3d, 0x32, 0xe4, 0xa6, 0xfb, 0x0a,
	0x70, 0x1a, 0x75, 0xd8, 0x4d, 0xb7, 0xf6, 0xe7, 0x3c, 0xb4, 0x36, 0x53, 0xcb, 0x2e, 0x09, 0x1f,
	0xba, 0x36, 0xc1, 0x47, 0xd0, 0x2a, 0x7e, 0x3a, 0xe2, 0xab, 0x35, 0x0c, 0x4a, 0xbf, 0xa2, 0xb5,
	0xf7, 0x4f, 0xe9, 0x95, 0x8e, 0x75, 0x7d, 0x04, 0x7f, 0xc7, 0xbe, 0x39, 0x72, 0x5f, 0x64, 0x58,
	0x25, 0x58, 0xf9, 0x9b, 0x52, 0xfb, 0xe0, 0xb4, 0x6e, 0x02, 0x44, 0x1f, 0xa6, 0xf8, 0x25, 0x8a,
	0x0d, 0xb5, 0x9d, 0x88, 0xac, 0x1d, 0x65, 0x7b, 0x91, 0x2e, 0x80, 0x69, 0xf1, 0xc5, 0x82, 0x3b,
	0x8a, 0xa8, 0x45, 0xc2, 0xcb, 0xea, 0x0e, 0x22, 0xe3, 0x0f, 0x08, 0x70, 0x59, 0xbe, 0xe3, 0x6b,
	0x6a, 0xd8, 0xcb, 0x57, 0x8d, 0x76, 0xbd, 0x81, 0xa7, 0x40, 0xf3, 0x23, 0x82, 0xb3, 0x12, 0x25,
	0x8c, 0xaf, 0x2b, 0xee, 0x4c, 0x82, 0x67, 0xbd, 0x89, 0xab, 0x00, 0xf4, 0x4b, 0xf6, 0x17, 0x94,
	0x63, 0x17, 0x0b, 0xfe, 0x48, 0x6d, 0xa3, 0xf2, 0x8b, 0x50, 0xbb, 0xd9, 0xd0, 0x3b, 0x7f, 0x3c,
	0x70, 0x59, 0xdf, 0x61, 0x45, 0xfa, 0x25, 0x92, 0xb0, 0x49, 0xbf, 0xfe, 0xce, 0x3e, 0x04, 0x2a,
	0x6f, 0x24, 0xbc, 0xa1, 0x10, 0xb4, 0xee, 0x3e, 0xd3, 0x36, 0xff, 0x5f, 0x10, 0x01, 0x77, 0x07,
	0x20, 0xd3, 0x02, 0xb8, 0xee, 0xb8, 0x94, 0x64, 0x83, 0x26, 0xd1, 0x96, 0xfa, 0x08, 0xbe, 0x07,
	0x33, 0x39, 0x2d, 0x80, 0x57, 0x95, 0xc2, 0x16, 0x0e, 0xae, 0x3c, 0xee, 0x01, 0x9c, 0x93, 0xc9,
	0x4a, 0xbc, 0xae, 0x8a, 0x5b, 0x72, 0x1a, 0xe4, 0x99, 0xbe, 0x85, 0xf3, 0x52, 0xf9, 0x88, 0x6f,
	0x28, 0xef, 0x45, 0x39, 0x57, 0x00, 0xed, 0x2a, 0x91, 0x88, 0x3f, 0x56, 0xdd, 0x59, 0xc5, 0xa1,
	0x92, 0x67, 0x7c, 0xcc, 0x65, 0x69, 0x75, 0x97, 0xde, 0x51, 0x4a, 0x5c, 0xdb, 0xa7, 0xf2, 0xfc,
	0x3b, 0x00, 0x99, 0xe0, 0xa9, 0xed, 0xba, 0x92, 0x36, 0xaa, 0xee, 0xba, 0x9c, 0x64, 0xa9, 0xed,
	0xba, 0xb2, 0xbc, 0xa9, 0x46, 0x9b, 0x49, 0x97, 0x5a, 0xb4, 0x25, 0x95, 0x53, 0x8d, 0x36, 0x27,
	0x5d, 0x6a, 0xd1, 0x96, 0x65, 0x8e, 0x3c, 0xee, 0xfd, 0x89, 0xe4, 0x9f, 0x14, 0x57, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x3b, 0x47, 0x3b, 0xdb, 0x09, 0x1a, 0x00, 0x00,
}
