// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/schemas/types.proto

package schemas

import (
	fmt "fmt"
	common "github.com/containers-ai/api/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Table int32

const (
	Table_TABLE_UNDEFINED      Table = 0
	Table_TABLE_APPLICATION    Table = 1
	Table_TABLE_METRIC         Table = 2
	Table_TABLE_PLANNING       Table = 3
	Table_TABLE_PREDICTION     Table = 4
	Table_TABLE_RESOURCE       Table = 5
	Table_TABLE_RECOMMENDATION Table = 6
)

var Table_name = map[int32]string{
	0: "TABLE_UNDEFINED",
	1: "TABLE_APPLICATION",
	2: "TABLE_METRIC",
	3: "TABLE_PLANNING",
	4: "TABLE_PREDICTION",
	5: "TABLE_RESOURCE",
	6: "TABLE_RECOMMENDATION",
}

var Table_value = map[string]int32{
	"TABLE_UNDEFINED":      0,
	"TABLE_APPLICATION":    1,
	"TABLE_METRIC":         2,
	"TABLE_PLANNING":       3,
	"TABLE_PREDICTION":     4,
	"TABLE_RESOURCE":       5,
	"TABLE_RECOMMENDATION": 6,
}

func (x Table) String() string {
	return proto.EnumName(Table_name, int32(x))
}

func (Table) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01194bf23370964f, []int{0}
}

type Scope int32

const (
	Scope_SCOPE_UNDEFINED   Scope = 0
	Scope_SCOPE_APPLICATION Scope = 1
	Scope_SCOPE_RESOURCE    Scope = 2
)

var Scope_name = map[int32]string{
	0: "SCOPE_UNDEFINED",
	1: "SCOPE_APPLICATION",
	2: "SCOPE_RESOURCE",
}

var Scope_value = map[string]int32{
	"SCOPE_UNDEFINED":   0,
	"SCOPE_APPLICATION": 1,
	"SCOPE_RESOURCE":    2,
}

func (x Scope) String() string {
	return proto.EnumName(Scope_name, int32(x))
}

func (Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01194bf23370964f, []int{1}
}

type SchemaMeta struct {
	Table                Table    `protobuf:"varint,1,opt,name=table,proto3,enum=containersai.alameda.v1alpha1.datahub.schemas.Table" json:"table,omitempty"`
	Scope                Scope    `protobuf:"varint,2,opt,name=scope,proto3,enum=containersai.alameda.v1alpha1.datahub.schemas.Scope" json:"scope,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaMeta) Reset()         { *m = SchemaMeta{} }
func (m *SchemaMeta) String() string { return proto.CompactTextString(m) }
func (*SchemaMeta) ProtoMessage()    {}
func (*SchemaMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_01194bf23370964f, []int{0}
}

func (m *SchemaMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaMeta.Unmarshal(m, b)
}
func (m *SchemaMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaMeta.Marshal(b, m, deterministic)
}
func (m *SchemaMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaMeta.Merge(m, src)
}
func (m *SchemaMeta) XXX_Size() int {
	return xxx_messageInfo_SchemaMeta.Size(m)
}
func (m *SchemaMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaMeta.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaMeta proto.InternalMessageInfo

func (m *SchemaMeta) GetTable() Table {
	if m != nil {
		return m.Table
	}
	return Table_TABLE_UNDEFINED
}

func (m *SchemaMeta) GetScope() Scope {
	if m != nil {
		return m.Scope
	}
	return Scope_SCOPE_UNDEFINED
}

func (m *SchemaMeta) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SchemaMeta) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Measurement struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*Column `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Measurement) Reset()         { *m = Measurement{} }
func (m *Measurement) String() string { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()    {}
func (*Measurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_01194bf23370964f, []int{1}
}

func (m *Measurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Measurement.Unmarshal(m, b)
}
func (m *Measurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Measurement.Marshal(b, m, deterministic)
}
func (m *Measurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Measurement.Merge(m, src)
}
func (m *Measurement) XXX_Size() int {
	return xxx_messageInfo_Measurement.Size(m)
}
func (m *Measurement) XXX_DiscardUnknown() {
	xxx_messageInfo_Measurement.DiscardUnknown(m)
}

var xxx_messageInfo_Measurement proto.InternalMessageInfo

func (m *Measurement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Measurement) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Column struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Required             bool              `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	ColumnTypes          common.ColumnType `protobuf:"varint,3,opt,name=column_types,json=columnTypes,proto3,enum=containersai.common.ColumnType" json:"column_types,omitempty"`
	DataTypes            common.DataType   `protobuf:"varint,4,opt,name=data_types,json=dataTypes,proto3,enum=containersai.common.DataType" json:"data_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_01194bf23370964f, []int{2}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Column) GetColumnTypes() common.ColumnType {
	if m != nil {
		return m.ColumnTypes
	}
	return common.ColumnType_COLUMNTYPE_UDEFINED
}

func (m *Column) GetDataTypes() common.DataType {
	if m != nil {
		return m.DataTypes
	}
	return common.DataType_DATATYPE_UNDEFINED
}

func init() {
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.schemas.Table", Table_name, Table_value)
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.schemas.Scope", Scope_name, Scope_value)
	proto.RegisterType((*SchemaMeta)(nil), "containersai.alameda.v1alpha1.datahub.schemas.SchemaMeta")
	proto.RegisterType((*Measurement)(nil), "containersai.alameda.v1alpha1.datahub.schemas.Measurement")
	proto.RegisterType((*Column)(nil), "containersai.alameda.v1alpha1.datahub.schemas.Column")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/schemas/types.proto", fileDescriptor_01194bf23370964f)
}

var fileDescriptor_01194bf23370964f = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xb6, 0xfc, 0x09, 0x87, 0x0d, 0xd6, 0x71, 0x4d, 0x1a, 0x12, 0x23, 0xe1, 0x8a, 0x6c, 0xb2,
	0xad, 0x8b, 0x7a, 0xe7, 0x4d, 0x69, 0xeb, 0xa6, 0x86, 0xb6, 0x64, 0xe8, 0xde, 0x78, 0x43, 0x0e,
	0x65, 0xb2, 0x34, 0xa1, 0x3f, 0xb6, 0x83, 0x09, 0x0f, 0xe3, 0x8b, 0xf8, 0x1c, 0x3e, 0x90, 0xe9,
	0x4c, 0x61, 0xdd, 0xb8, 0x17, 0xe2, 0xdd, 0x99, 0xaf, 0xf3, 0xfd, 0x9c, 0x39, 0x3d, 0xf0, 0x0e,
	0x77, 0x98, 0xb0, 0x0d, 0xae, 0x30, 0x8f, 0x8d, 0xef, 0x37, 0xb8, 0xcb, 0xb7, 0x78, 0x63, 0x6c,
	0x90, 0xe3, 0x76, 0xbf, 0x36, 0xca, 0x68, 0xcb, 0x12, 0x2c, 0x0d, 0x7e, 0xc8, 0x59, 0xa9, 0xe7,
	0x45, 0xc6, 0x33, 0x72, 0x1d, 0x65, 0x29, 0xc7, 0x38, 0x65, 0x45, 0x89, 0xb1, 0x5e, 0xd3, 0xf5,
	0x23, 0x55, 0xaf, 0xa9, 0x7a, 0x4d, 0x1d, 0x92, 0x28, 0x4b, 0x92, 0x2c, 0xfd, 0x53, 0x62, 0xfc,
	0x4b, 0x01, 0x58, 0x8a, 0xef, 0x1e, 0xe3, 0x48, 0xbe, 0x40, 0x9b, 0xe3, 0x7a, 0xc7, 0x34, 0x65,
	0xa4, 0x4c, 0x06, 0xd3, 0x0f, 0xfa, 0x59, 0x0e, 0x7a, 0x58, 0x71, 0xa9, 0x94, 0xa8, 0xb4, 0xca,
	0x28, 0xcb, 0x99, 0xd6, 0xf8, 0x2f, 0xad, 0x65, 0xc5, 0xa5, 0x52, 0x82, 0x0c, 0xa1, 0x1b, 0x21,
	0x67, 0xf7, 0x59, 0x71, 0xd0, 0x9a, 0x23, 0x65, 0xd2, 0xa3, 0xa7, 0x33, 0x21, 0xd0, 0xaa, 0x3a,
	0xd2, 0x5a, 0x02, 0x17, 0xf5, 0xb8, 0x80, 0xbe, 0xc7, 0xb0, 0xdc, 0x17, 0x2c, 0x61, 0x29, 0xaf,
	0xae, 0xa4, 0x98, 0xc8, 0xae, 0x7a, 0x54, 0xd4, 0x24, 0x80, 0xe7, 0x51, 0xb6, 0xdb, 0x27, 0x69,
	0xa9, 0x35, 0x46, 0xcd, 0x49, 0x7f, 0xfa, 0xf1, 0xcc, 0x80, 0x96, 0x60, 0xd3, 0xa3, 0xca, 0xf8,
	0xa7, 0x02, 0x1d, 0x89, 0x3d, 0xe9, 0x37, 0x84, 0x6e, 0xc1, 0xbe, 0xed, 0xe3, 0x82, 0x6d, 0xc4,
	0x8b, 0x74, 0xe9, 0xe9, 0x4c, 0x66, 0x70, 0x21, 0x55, 0x56, 0x62, 0x36, 0xa2, 0xc5, 0xc1, 0xf4,
	0xed, 0xe3, 0x40, 0x72, 0x7a, 0xb5, 0x6d, 0x78, 0xc8, 0x19, 0xed, 0x47, 0xa7, 0xba, 0x24, 0x9f,
	0x00, 0xaa, 0x84, 0xb5, 0x42, 0x4b, 0x28, 0xbc, 0x79, 0x52, 0xc1, 0x46, 0x8e, 0x82, 0xdf, 0xdb,
	0xd4, 0x55, 0x79, 0xf5, 0x43, 0x81, 0xb6, 0x98, 0x1e, 0x79, 0x05, 0x2f, 0x42, 0x73, 0x36, 0x77,
	0x56, 0x77, 0xbe, 0xed, 0x7c, 0x76, 0x7d, 0xc7, 0x56, 0x9f, 0x91, 0xd7, 0xf0, 0x52, 0x82, 0xe6,
	0x62, 0x31, 0x77, 0x2d, 0x33, 0x74, 0x03, 0x5f, 0x55, 0x88, 0x0a, 0x17, 0x12, 0xf6, 0x9c, 0x90,
	0xba, 0x96, 0xda, 0x20, 0x04, 0x06, 0x12, 0x59, 0xcc, 0x4d, 0xdf, 0x77, 0xfd, 0x5b, 0xb5, 0x49,
	0x2e, 0x41, 0xad, 0x31, 0xea, 0xd8, 0xae, 0x25, 0xb8, 0xad, 0x87, 0x9b, 0xd4, 0x59, 0x06, 0x77,
	0xd4, 0x72, 0xd4, 0x36, 0xd1, 0xe0, 0xf2, 0x88, 0x59, 0x81, 0xe7, 0x39, 0xbe, 0x2d, 0x9d, 0x3a,
	0x57, 0xb7, 0xd0, 0x16, 0x3f, 0x44, 0x15, 0x6f, 0x69, 0x05, 0x8b, 0xbf, 0xe2, 0x49, 0xf0, 0x71,
	0x3c, 0x02, 0x03, 0x09, 0x9f, 0x2c, 0x1a, 0x33, 0xeb, 0xab, 0x79, 0x1f, 0xf3, 0x6a, 0x8e, 0x51,
	0x96, 0x18, 0x0f, 0xcf, 0x73, 0x8d, 0xb1, 0x51, 0x2d, 0xde, 0xbf, 0x2c, 0xe1, 0xba, 0x23, 0x96,
	0xe7, 0xfd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x35, 0x5e, 0x19, 0xb3, 0x03, 0x00, 0x00,
}
