// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/resources/types.proto

package resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlamedaPodSpec struct {
	AlamedaScaler          *ObjectMeta           `protobuf:"bytes,1,opt,name=alameda_scaler,json=alamedaScaler,proto3" json:"alameda_scaler,omitempty"`
	ScalingTool            ScalingTool           `protobuf:"varint,2,opt,name=scaling_tool,json=scalingTool,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.ScalingTool" json:"scaling_tool,omitempty"`
	UsedRecommendationId   string                `protobuf:"bytes,3,opt,name=used_recommendation_id,json=usedRecommendationId,proto3" json:"used_recommendation_id,omitempty"`
	Policy                 RecommendationPolicy  `protobuf:"varint,4,opt,name=policy,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.RecommendationPolicy" json:"policy,omitempty"`
	AlamedaScalerResources *ResourceRequirements `protobuf:"bytes,5,opt,name=alameda_scaler_resources,json=alamedaScalerResources,proto3" json:"alameda_scaler_resources,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *AlamedaPodSpec) Reset()         { *m = AlamedaPodSpec{} }
func (m *AlamedaPodSpec) String() string { return proto.CompactTextString(m) }
func (*AlamedaPodSpec) ProtoMessage()    {}
func (*AlamedaPodSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{0}
}

func (m *AlamedaPodSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaPodSpec.Unmarshal(m, b)
}
func (m *AlamedaPodSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaPodSpec.Marshal(b, m, deterministic)
}
func (m *AlamedaPodSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaPodSpec.Merge(m, src)
}
func (m *AlamedaPodSpec) XXX_Size() int {
	return xxx_messageInfo_AlamedaPodSpec.Size(m)
}
func (m *AlamedaPodSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaPodSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaPodSpec proto.InternalMessageInfo

func (m *AlamedaPodSpec) GetAlamedaScaler() *ObjectMeta {
	if m != nil {
		return m.AlamedaScaler
	}
	return nil
}

func (m *AlamedaPodSpec) GetScalingTool() ScalingTool {
	if m != nil {
		return m.ScalingTool
	}
	return ScalingTool_SCALING_TOOL_UNDEFINED
}

func (m *AlamedaPodSpec) GetUsedRecommendationId() string {
	if m != nil {
		return m.UsedRecommendationId
	}
	return ""
}

func (m *AlamedaPodSpec) GetPolicy() RecommendationPolicy {
	if m != nil {
		return m.Policy
	}
	return RecommendationPolicy_RECOMMENDATION_POLICY_UNDEFINED
}

func (m *AlamedaPodSpec) GetAlamedaScalerResources() *ResourceRequirements {
	if m != nil {
		return m.AlamedaScalerResources
	}
	return nil
}

type AlamedaControllerSpec struct {
	AlamedaScaler                 *ObjectMeta          `protobuf:"bytes,1,opt,name=alameda_scaler,json=alamedaScaler,proto3" json:"alameda_scaler,omitempty"`
	ScalingTool                   ScalingTool          `protobuf:"varint,2,opt,name=scaling_tool,json=scalingTool,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.ScalingTool" json:"scaling_tool,omitempty"`
	Policy                        RecommendationPolicy `protobuf:"varint,3,opt,name=policy,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.RecommendationPolicy" json:"policy,omitempty"`
	EnableRecommendationExecution bool                 `protobuf:"varint,4,opt,name=enable_recommendation_execution,json=enableRecommendationExecution,proto3" json:"enable_recommendation_execution,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}             `json:"-"`
	XXX_unrecognized              []byte               `json:"-"`
	XXX_sizecache                 int32                `json:"-"`
}

func (m *AlamedaControllerSpec) Reset()         { *m = AlamedaControllerSpec{} }
func (m *AlamedaControllerSpec) String() string { return proto.CompactTextString(m) }
func (*AlamedaControllerSpec) ProtoMessage()    {}
func (*AlamedaControllerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{1}
}

func (m *AlamedaControllerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaControllerSpec.Unmarshal(m, b)
}
func (m *AlamedaControllerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaControllerSpec.Marshal(b, m, deterministic)
}
func (m *AlamedaControllerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaControllerSpec.Merge(m, src)
}
func (m *AlamedaControllerSpec) XXX_Size() int {
	return xxx_messageInfo_AlamedaControllerSpec.Size(m)
}
func (m *AlamedaControllerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaControllerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaControllerSpec proto.InternalMessageInfo

func (m *AlamedaControllerSpec) GetAlamedaScaler() *ObjectMeta {
	if m != nil {
		return m.AlamedaScaler
	}
	return nil
}

func (m *AlamedaControllerSpec) GetScalingTool() ScalingTool {
	if m != nil {
		return m.ScalingTool
	}
	return ScalingTool_SCALING_TOOL_UNDEFINED
}

func (m *AlamedaControllerSpec) GetPolicy() RecommendationPolicy {
	if m != nil {
		return m.Policy
	}
	return RecommendationPolicy_RECOMMENDATION_POLICY_UNDEFINED
}

func (m *AlamedaControllerSpec) GetEnableRecommendationExecution() bool {
	if m != nil {
		return m.EnableRecommendationExecution
	}
	return false
}

type AlamedaApplicationSpec struct {
	ScalingTool          ScalingTool `protobuf:"varint,1,opt,name=scaling_tool,json=scalingTool,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.ScalingTool" json:"scaling_tool,omitempty"`
	MinReplicas          int32       `protobuf:"varint,2,opt,name=MinReplicas,proto3" json:"MinReplicas,omitempty"`
	MaxReplicas          int32       `protobuf:"varint,3,opt,name=MaxReplicas,proto3" json:"MaxReplicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AlamedaApplicationSpec) Reset()         { *m = AlamedaApplicationSpec{} }
func (m *AlamedaApplicationSpec) String() string { return proto.CompactTextString(m) }
func (*AlamedaApplicationSpec) ProtoMessage()    {}
func (*AlamedaApplicationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{2}
}

func (m *AlamedaApplicationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaApplicationSpec.Unmarshal(m, b)
}
func (m *AlamedaApplicationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaApplicationSpec.Marshal(b, m, deterministic)
}
func (m *AlamedaApplicationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaApplicationSpec.Merge(m, src)
}
func (m *AlamedaApplicationSpec) XXX_Size() int {
	return xxx_messageInfo_AlamedaApplicationSpec.Size(m)
}
func (m *AlamedaApplicationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaApplicationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaApplicationSpec proto.InternalMessageInfo

func (m *AlamedaApplicationSpec) GetScalingTool() ScalingTool {
	if m != nil {
		return m.ScalingTool
	}
	return ScalingTool_SCALING_TOOL_UNDEFINED
}

func (m *AlamedaApplicationSpec) GetMinReplicas() int32 {
	if m != nil {
		return m.MinReplicas
	}
	return 0
}

func (m *AlamedaApplicationSpec) GetMaxReplicas() int32 {
	if m != nil {
		return m.MaxReplicas
	}
	return 0
}

type AlamedaNodeSpec struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AlamedaNodeSpec) Reset()         { *m = AlamedaNodeSpec{} }
func (m *AlamedaNodeSpec) String() string { return proto.CompactTextString(m) }
func (*AlamedaNodeSpec) ProtoMessage()    {}
func (*AlamedaNodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{3}
}

func (m *AlamedaNodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlamedaNodeSpec.Unmarshal(m, b)
}
func (m *AlamedaNodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlamedaNodeSpec.Marshal(b, m, deterministic)
}
func (m *AlamedaNodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlamedaNodeSpec.Merge(m, src)
}
func (m *AlamedaNodeSpec) XXX_Size() int {
	return xxx_messageInfo_AlamedaNodeSpec.Size(m)
}
func (m *AlamedaNodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AlamedaNodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AlamedaNodeSpec proto.InternalMessageInfo

func (m *AlamedaNodeSpec) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

// Represents the capacity of a Kubernetes node
type Capacity struct {
	CpuCores                 int64    `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes              int64    `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NetworkMegabitsPerSecond int64    `protobuf:"varint,3,opt,name=network_megabits_per_second,json=networkMegabitsPerSecond,proto3" json:"network_megabits_per_second,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Capacity) Reset()         { *m = Capacity{} }
func (m *Capacity) String() string { return proto.CompactTextString(m) }
func (*Capacity) ProtoMessage()    {}
func (*Capacity) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{4}
}

func (m *Capacity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capacity.Unmarshal(m, b)
}
func (m *Capacity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capacity.Marshal(b, m, deterministic)
}
func (m *Capacity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capacity.Merge(m, src)
}
func (m *Capacity) XXX_Size() int {
	return xxx_messageInfo_Capacity.Size(m)
}
func (m *Capacity) XXX_DiscardUnknown() {
	xxx_messageInfo_Capacity.DiscardUnknown(m)
}

var xxx_messageInfo_Capacity proto.InternalMessageInfo

func (m *Capacity) GetCpuCores() int64 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *Capacity) GetMemoryBytes() int64 {
	if m != nil {
		return m.MemoryBytes
	}
	return 0
}

func (m *Capacity) GetNetworkMegabitsPerSecond() int64 {
	if m != nil {
		return m.NetworkMegabitsPerSecond
	}
	return 0
}

type Provider struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	InstanceType         string   `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	InstanceId           string   `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StorageSize          int64    `protobuf:"varint,8,opt,name=storage_size,json=storageSize,proto3" json:"storage_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{5}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Provider) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *Provider) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Provider) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Provider) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Provider) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Provider) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Provider) GetStorageSize() int64 {
	if m != nil {
		return m.StorageSize
	}
	return 0
}

//*
// ResourceRequirements describes the compute resource requirements
type ResourceRequirements struct {
	// limits describes the maximum amount of compute resources allowed
	// use enum ResourceName as key of the map which defined in common
	Limits map[int32]string `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// requests describes the minimum amount of compute resources required
	// use enum ResourceName as key of the map which defined in common
	Requests             map[int32]string `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResourceRequirements) Reset()         { *m = ResourceRequirements{} }
func (m *ResourceRequirements) String() string { return proto.CompactTextString(m) }
func (*ResourceRequirements) ProtoMessage()    {}
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb5f61783b62fcd, []int{6}
}

func (m *ResourceRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequirements.Unmarshal(m, b)
}
func (m *ResourceRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequirements.Marshal(b, m, deterministic)
}
func (m *ResourceRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequirements.Merge(m, src)
}
func (m *ResourceRequirements) XXX_Size() int {
	return xxx_messageInfo_ResourceRequirements.Size(m)
}
func (m *ResourceRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequirements proto.InternalMessageInfo

func (m *ResourceRequirements) GetLimits() map[int32]string {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *ResourceRequirements) GetRequests() map[int32]string {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*AlamedaPodSpec)(nil), "containersai.alameda.v1alpha1.datahub.resources.AlamedaPodSpec")
	proto.RegisterType((*AlamedaControllerSpec)(nil), "containersai.alameda.v1alpha1.datahub.resources.AlamedaControllerSpec")
	proto.RegisterType((*AlamedaApplicationSpec)(nil), "containersai.alameda.v1alpha1.datahub.resources.AlamedaApplicationSpec")
	proto.RegisterType((*AlamedaNodeSpec)(nil), "containersai.alameda.v1alpha1.datahub.resources.AlamedaNodeSpec")
	proto.RegisterType((*Capacity)(nil), "containersai.alameda.v1alpha1.datahub.resources.Capacity")
	proto.RegisterType((*Provider)(nil), "containersai.alameda.v1alpha1.datahub.resources.Provider")
	proto.RegisterType((*ResourceRequirements)(nil), "containersai.alameda.v1alpha1.datahub.resources.ResourceRequirements")
	proto.RegisterMapType((map[int32]string)(nil), "containersai.alameda.v1alpha1.datahub.resources.ResourceRequirements.LimitsEntry")
	proto.RegisterMapType((map[int32]string)(nil), "containersai.alameda.v1alpha1.datahub.resources.ResourceRequirements.RequestsEntry")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/resources/types.proto", fileDescriptor_fdb5f61783b62fcd)
}

var fileDescriptor_fdb5f61783b62fcd = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xc1, 0x6e, 0xe3, 0x36,
	0x10, 0x85, 0xac, 0xd8, 0xb5, 0xe9, 0xc4, 0x2d, 0x88, 0xd4, 0x10, 0x1c, 0x14, 0x71, 0xdd, 0x8b,
	0x2f, 0x95, 0x11, 0xb7, 0x05, 0x9a, 0xa6, 0x3d, 0x24, 0x86, 0x0b, 0x04, 0x68, 0x5a, 0x97, 0x4e,
	0x2f, 0x05, 0x0a, 0x81, 0xa6, 0x06, 0x0e, 0x1b, 0x49, 0x54, 0x48, 0x2a, 0x8d, 0x72, 0xe9, 0x61,
	0x4f, 0xfb, 0x51, 0xfb, 0x2d, 0x7b, 0xdf, 0xfd, 0x89, 0x05, 0x29, 0xc9, 0x8e, 0x83, 0x3d, 0xc4,
	0x8b, 0xec, 0x65, 0x6f, 0xe4, 0xf0, 0xcd, 0x7b, 0x4f, 0x33, 0xc4, 0x50, 0x68, 0x4c, 0x23, 0x1a,
	0x43, 0x48, 0x03, 0x9a, 0xf2, 0xd1, 0xed, 0x11, 0x8d, 0xd2, 0x2b, 0x7a, 0x34, 0x0a, 0xa9, 0xa6,
	0x57, 0xd9, 0x62, 0x24, 0x41, 0x89, 0x4c, 0x32, 0x50, 0x23, 0x9d, 0xa7, 0xa0, 0xfc, 0x54, 0x0a,
	0x2d, 0xf0, 0x88, 0x89, 0x44, 0x53, 0x9e, 0x80, 0x54, 0x94, 0xfb, 0x25, 0x81, 0x5f, 0x25, 0xfb,
	0x65, 0xb2, 0xbf, 0x4a, 0xee, 0xfd, 0xf0, 0x44, 0x91, 0x18, 0x34, 0x35, 0xd1, 0x42, 0xe7, 0xc9,
	0x69, 0xa9, 0x88, 0x38, 0xe3, 0x95, 0xbd, 0xc1, 0x5b, 0x17, 0x75, 0x4e, 0x8b, 0xcc, 0x99, 0x08,
	0xe7, 0x29, 0x30, 0xbc, 0x40, 0x9d, 0x8a, 0x4b, 0x31, 0x1a, 0x81, 0xf4, 0x9c, 0xbe, 0x33, 0x6c,
	0x8f, 0x4f, 0xfc, 0x2d, 0x3f, 0xc5, 0xff, 0x63, 0xf1, 0x2f, 0x30, 0x7d, 0x01, 0x9a, 0x92, 0xbd,
	0x12, 0x3e, 0xb7, 0x8c, 0x38, 0x40, 0xbb, 0x86, 0x9b, 0x27, 0xcb, 0x40, 0x0b, 0x11, 0x79, 0xb5,
	0xbe, 0x33, 0xec, 0x8c, 0x7f, 0xde, 0x5a, 0x61, 0x5e, 0x90, 0x5c, 0x0a, 0x11, 0x91, 0xb6, 0x5a,
	0x6f, 0xf0, 0xf7, 0xa8, 0x9b, 0x29, 0x08, 0x03, 0x09, 0x4c, 0xc4, 0x31, 0x24, 0x21, 0xd5, 0x5c,
	0x24, 0x01, 0x0f, 0x3d, 0xb7, 0xef, 0x0c, 0x5b, 0x64, 0xdf, 0x9c, 0x92, 0x8d, 0xc3, 0xf3, 0x10,
	0xff, 0x83, 0x1a, 0xb6, 0x3e, 0xb9, 0xb7, 0x63, 0x0d, 0x4d, 0xb7, 0x36, 0xb4, 0x49, 0x39, 0xb3,
	0x64, 0xa4, 0x24, 0xc5, 0xff, 0x23, 0x6f, 0xb3, 0xb2, 0xc1, 0x2a, 0xd1, 0xab, 0xdb, 0x1a, 0x7f,
	0x88, 0x60, 0xb1, 0x22, 0x70, 0x93, 0x71, 0x09, 0x31, 0x24, 0x5a, 0x91, 0xee, 0x46, 0xb5, 0x2b,
	0x88, 0x1a, 0xbc, 0x70, 0xd1, 0x97, 0x65, 0xb7, 0x27, 0x22, 0xd1, 0x52, 0x44, 0x11, 0xc8, 0x4f,
	0xa7, 0xe9, 0xeb, 0xf6, 0xb9, 0x1f, 0xa3, 0x7d, 0xbf, 0xa2, 0x43, 0x48, 0xe8, 0x22, 0x82, 0xc7,
	0xb7, 0x0a, 0xee, 0x80, 0x65, 0x66, 0x65, 0xaf, 0x4d, 0x93, 0x7c, 0x55, 0xc0, 0x36, 0xc9, 0xa6,
	0x15, 0x68, 0xf0, 0xca, 0x41, 0xdd, 0xb2, 0x0b, 0xa7, 0x69, 0x1a, 0x71, 0x66, 0xcf, 0x6d, 0x1b,
	0x1e, 0x97, 0xc8, 0x79, 0xee, 0x12, 0xf5, 0x51, 0xfb, 0x82, 0x27, 0x04, 0xac, 0xac, 0xb2, 0x2d,
	0xa8, 0x93, 0x87, 0x21, 0x8b, 0xa0, 0x77, 0x2b, 0x84, 0x5b, 0x22, 0xd6, 0xa1, 0xc1, 0x15, 0xfa,
	0xbc, 0xb4, 0xff, 0xbb, 0x08, 0xc1, 0xfa, 0xfe, 0x0b, 0x35, 0x53, 0x29, 0x6e, 0x79, 0xb8, 0xba,
	0x38, 0xc7, 0x5b, 0x7b, 0x9e, 0x95, 0x04, 0x64, 0x45, 0x35, 0x78, 0xe9, 0xa0, 0xe6, 0x84, 0xa6,
	0x94, 0x71, 0x9d, 0xe3, 0x03, 0xd4, 0x62, 0x69, 0x16, 0x30, 0x21, 0x41, 0x59, 0x11, 0x97, 0x34,
	0x59, 0x9a, 0x4d, 0xcc, 0x1e, 0x7f, 0x8d, 0x76, 0x63, 0x88, 0x85, 0xcc, 0x83, 0x45, 0xae, 0xa1,
	0xf8, 0x30, 0x97, 0xb4, 0x8b, 0xd8, 0x99, 0x09, 0xe1, 0x5f, 0xd0, 0x41, 0x02, 0xfa, 0x3f, 0x21,
	0xaf, 0x83, 0x18, 0x96, 0x74, 0xc1, 0xb5, 0x0a, 0x52, 0x90, 0x81, 0x02, 0x26, 0x92, 0x62, 0x2e,
	0xb8, 0xc4, 0x2b, 0x21, 0x17, 0x25, 0x62, 0x06, 0x72, 0x6e, 0xcf, 0x07, 0xaf, 0x1d, 0xd4, 0xac,
	0x2c, 0xe2, 0xde, 0xa3, 0xef, 0x6d, 0xad, 0x4d, 0xe3, 0x6f, 0xd0, 0x1e, 0x4f, 0x94, 0xa6, 0x09,
	0x83, 0xc0, 0xbc, 0x04, 0xd6, 0x4b, 0x8b, 0xec, 0x56, 0xc1, 0xcb, 0x3c, 0x05, 0xdc, 0x45, 0x0d,
	0x09, 0x4b, 0x73, 0x65, 0x8a, 0x79, 0x54, 0xee, 0x30, 0x46, 0x3b, 0xf7, 0x22, 0x01, 0x7b, 0x91,
	0x5a, 0xc4, 0xae, 0x71, 0x07, 0xd5, 0x44, 0x31, 0x20, 0x5a, 0xa4, 0x26, 0x94, 0xc1, 0x48, 0x11,
	0x81, 0xd7, 0x28, 0x30, 0x66, 0x8d, 0x0f, 0x51, 0x7b, 0x25, 0xca, 0x43, 0xef, 0x33, 0x7b, 0x84,
	0xaa, 0xd0, 0x79, 0x68, 0x0a, 0xa4, 0xb4, 0x90, 0x74, 0x09, 0x81, 0xe2, 0xf7, 0xe0, 0x35, 0x8b,
	0x02, 0x95, 0xb1, 0x39, 0xbf, 0x87, 0xc1, 0x9b, 0x1a, 0xda, 0x7f, 0xdf, 0x38, 0xc1, 0x1c, 0x35,
	0x22, 0x1e, 0x73, 0x6d, 0xca, 0xee, 0x0e, 0xdb, 0xe3, 0x3f, 0x9f, 0x65, 0x4a, 0xf9, 0xbf, 0x59,
	0xce, 0x69, 0xa2, 0x65, 0x4e, 0x4a, 0x01, 0x2c, 0x50, 0x53, 0xc2, 0x4d, 0x06, 0x4a, 0x9b, 0x1e,
	0x1a, 0xb1, 0xf9, 0xf3, 0x88, 0x91, 0x92, 0xb5, 0x90, 0x5b, 0x89, 0xf4, 0x8e, 0x51, 0xfb, 0x81,
	0x0f, 0xfc, 0x05, 0x72, 0xaf, 0x21, 0xb7, 0x3d, 0xad, 0x13, 0xb3, 0xc4, 0xfb, 0xa8, 0x7e, 0x4b,
	0xa3, 0xac, 0x6a, 0x63, 0xb1, 0xf9, 0xa9, 0xf6, 0xa3, 0xd3, 0x3b, 0x41, 0x7b, 0x1b, 0xac, 0xdb,
	0x24, 0x9f, 0x4d, 0xff, 0x9e, 0x2c, 0xb9, 0x36, 0xc6, 0x99, 0x88, 0x1f, 0xfc, 0x24, 0x7c, 0x4b,
	0xf9, 0xc8, 0x3c, 0xe1, 0x4f, 0x7b, 0xce, 0x17, 0x0d, 0xfb, 0x8c, 0x7f, 0xf7, 0x2e, 0x00, 0x00,
	0xff, 0xff, 0x1f, 0x11, 0x8f, 0x3f, 0x9b, 0x08, 0x00, 0x00,
}
