// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/common/metrics.proto

package common

import (
	fmt "fmt"
	common "github.com/containers-ai/api/common"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Metric type. A metric may be either CPU or memory.
type MetricType int32

const (
	MetricType_METRICS_TYPE_UNDEFINED       MetricType = 0
	MetricType_CPU_USAGE_SECONDS_PERCENTAGE MetricType = 1
	MetricType_MEMORY_USAGE_BYTES           MetricType = 2
	MetricType_POWER_USAGE_WATTS            MetricType = 3
	MetricType_TEMPERATURE_CELSIUS          MetricType = 4
	MetricType_DUTY_CYCLE                   MetricType = 5
	MetricType_CURRENT_OFFSET               MetricType = 6
)

var MetricType_name = map[int32]string{
	0: "METRICS_TYPE_UNDEFINED",
	1: "CPU_USAGE_SECONDS_PERCENTAGE",
	2: "MEMORY_USAGE_BYTES",
	3: "POWER_USAGE_WATTS",
	4: "TEMPERATURE_CELSIUS",
	5: "DUTY_CYCLE",
	6: "CURRENT_OFFSET",
}

var MetricType_value = map[string]int32{
	"METRICS_TYPE_UNDEFINED":       0,
	"CPU_USAGE_SECONDS_PERCENTAGE": 1,
	"MEMORY_USAGE_BYTES":           2,
	"POWER_USAGE_WATTS":            3,
	"TEMPERATURE_CELSIUS":          4,
	"DUTY_CYCLE":                   5,
	"CURRENT_OFFSET":               6,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{0}
}

type ResourceName int32

const (
	ResourceName_RESOURCE_NAME_UNDEFINED ResourceName = 0
	ResourceName_CPU                     ResourceName = 1
	ResourceName_MEMORY                  ResourceName = 2
)

var ResourceName_name = map[int32]string{
	0: "RESOURCE_NAME_UNDEFINED",
	1: "CPU",
	2: "MEMORY",
}

var ResourceName_value = map[string]int32{
	"RESOURCE_NAME_UNDEFINED": 0,
	"CPU":                     1,
	"MEMORY":                  2,
}

func (x ResourceName) String() string {
	return proto.EnumName(ResourceName_name, int32(x))
}

func (ResourceName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{1}
}

//*
// Represents a data point of time-series metric data
type Sample struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	NumValue             string               `protobuf:"bytes,3,opt,name=num_value,json=numValue,proto3" json:"num_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{0}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Sample) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Sample) GetNumValue() string {
	if m != nil {
		return m.NumValue
	}
	return ""
}

//*
// Represents a piece of metreic data
type MetricData struct {
	MetricType           MetricType `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=containersai.alameda.v1alpha1.datahub.common.MetricType" json:"metric_type,omitempty"`
	Data                 []*Sample  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Granularity          int64      `protobuf:"varint,3,opt,name=granularity,proto3" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MetricData) Reset()         { *m = MetricData{} }
func (m *MetricData) String() string { return proto.CompactTextString(m) }
func (*MetricData) ProtoMessage()    {}
func (*MetricData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{1}
}

func (m *MetricData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricData.Unmarshal(m, b)
}
func (m *MetricData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricData.Marshal(b, m, deterministic)
}
func (m *MetricData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricData.Merge(m, src)
}
func (m *MetricData) XXX_Size() int {
	return xxx_messageInfo_MetricData.Size(m)
}
func (m *MetricData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricData.DiscardUnknown(m)
}

var xxx_messageInfo_MetricData proto.InternalMessageInfo

func (m *MetricData) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_METRICS_TYPE_UNDEFINED
}

func (m *MetricData) GetData() []*Sample {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MetricData) GetGranularity() int64 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

type ReadMetricData struct {
	MetricType           MetricType      `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=containersai.alameda.v1alpha1.datahub.common.MetricType" json:"metric_type,omitempty"`
	Groups               []*common.Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReadMetricData) Reset()         { *m = ReadMetricData{} }
func (m *ReadMetricData) String() string { return proto.CompactTextString(m) }
func (*ReadMetricData) ProtoMessage()    {}
func (*ReadMetricData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{2}
}

func (m *ReadMetricData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMetricData.Unmarshal(m, b)
}
func (m *ReadMetricData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMetricData.Marshal(b, m, deterministic)
}
func (m *ReadMetricData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMetricData.Merge(m, src)
}
func (m *ReadMetricData) XXX_Size() int {
	return xxx_messageInfo_ReadMetricData.Size(m)
}
func (m *ReadMetricData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMetricData.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMetricData proto.InternalMessageInfo

func (m *ReadMetricData) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_METRICS_TYPE_UNDEFINED
}

func (m *ReadMetricData) GetGroups() []*common.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type WriteMetricData struct {
	MetricType           MetricType    `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=containersai.alameda.v1alpha1.datahub.common.MetricType" json:"metric_type,omitempty"`
	Columns              []string      `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows                 []*common.Row `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WriteMetricData) Reset()         { *m = WriteMetricData{} }
func (m *WriteMetricData) String() string { return proto.CompactTextString(m) }
func (*WriteMetricData) ProtoMessage()    {}
func (*WriteMetricData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dcb68d43798345b, []int{3}
}

func (m *WriteMetricData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteMetricData.Unmarshal(m, b)
}
func (m *WriteMetricData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteMetricData.Marshal(b, m, deterministic)
}
func (m *WriteMetricData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteMetricData.Merge(m, src)
}
func (m *WriteMetricData) XXX_Size() int {
	return xxx_messageInfo_WriteMetricData.Size(m)
}
func (m *WriteMetricData) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteMetricData.DiscardUnknown(m)
}

var xxx_messageInfo_WriteMetricData proto.InternalMessageInfo

func (m *WriteMetricData) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_METRICS_TYPE_UNDEFINED
}

func (m *WriteMetricData) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *WriteMetricData) GetRows() []*common.Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.common.MetricType", MetricType_name, MetricType_value)
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.common.ResourceName", ResourceName_name, ResourceName_value)
	proto.RegisterType((*Sample)(nil), "containersai.alameda.v1alpha1.datahub.common.Sample")
	proto.RegisterType((*MetricData)(nil), "containersai.alameda.v1alpha1.datahub.common.MetricData")
	proto.RegisterType((*ReadMetricData)(nil), "containersai.alameda.v1alpha1.datahub.common.ReadMetricData")
	proto.RegisterType((*WriteMetricData)(nil), "containersai.alameda.v1alpha1.datahub.common.WriteMetricData")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/common/metrics.proto", fileDescriptor_0dcb68d43798345b)
}

var fileDescriptor_0dcb68d43798345b = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6a, 0xdb, 0x3e,
	0x1c, 0xc5, 0x7f, 0x8e, 0xf3, 0x4b, 0xdb, 0x6f, 0x46, 0xe6, 0xa9, 0xac, 0x35, 0xd9, 0x60, 0x21,
	0x57, 0xa5, 0x74, 0x36, 0xcd, 0x36, 0xd8, 0x65, 0x53, 0x47, 0xed, 0x0a, 0xb5, 0x63, 0x64, 0x79,
	0xc5, 0xbb, 0x11, 0x6a, 0xa2, 0xa5, 0x06, 0xdb, 0x32, 0xfe, 0xd3, 0xd2, 0x77, 0xd8, 0x3b, 0xec,
	0x25, 0xc6, 0x5e, 0x64, 0x2f, 0x34, 0xfc, 0x27, 0xdd, 0x0a, 0x83, 0xad, 0x37, 0xbd, 0xb2, 0xbf,
	0xf2, 0xf9, 0x1c, 0x8e, 0x0e, 0x96, 0xe0, 0x90, 0x47, 0x3c, 0x16, 0x4b, 0xce, 0x78, 0x1a, 0x9a,
	0xd7, 0x87, 0x3c, 0x4a, 0xaf, 0xf8, 0xa1, 0xb9, 0xe4, 0x05, 0xbf, 0x2a, 0x2f, 0xcd, 0x85, 0x8c,
	0x63, 0x99, 0x98, 0xb1, 0x28, 0xb2, 0x70, 0x91, 0x1b, 0x69, 0x26, 0x0b, 0x89, 0x0e, 0x16, 0x32,
	0x29, 0x78, 0x98, 0x88, 0x2c, 0xe7, 0xa1, 0xd1, 0xf2, 0xc6, 0x9a, 0x35, 0x5a, 0xd6, 0x68, 0xd8,
	0xe1, 0x76, 0xeb, 0xd1, 0x3c, 0x1a, 0x8b, 0xe1, 0xab, 0x95, 0x94, 0xab, 0x48, 0x98, 0xf5, 0x74,
	0x59, 0x7e, 0x36, 0x8b, 0x30, 0x16, 0x79, 0xc1, 0xe3, 0xb4, 0x11, 0x8c, 0xbf, 0x28, 0xd0, 0xf3,
	0x78, 0x9c, 0x46, 0x02, 0x19, 0xd0, 0xad, 0xbe, 0xea, 0xca, 0x48, 0xd9, 0xeb, 0x4f, 0x86, 0x46,
	0x83, 0x1a, 0x6b, 0xd4, 0xa0, 0x6b, 0x94, 0xd4, 0x3a, 0xf4, 0x0e, 0x36, 0x45, 0xb2, 0x64, 0x35,
	0xd3, 0xf9, 0x2b, 0xb3, 0x21, 0x92, 0x65, 0x35, 0xa1, 0x17, 0xb0, 0x95, 0x94, 0x31, 0xbb, 0xe6,
	0x51, 0x29, 0x74, 0x75, 0xa4, 0xec, 0x6d, 0x91, 0xcd, 0xa4, 0x8c, 0x3f, 0x56, 0xf3, 0xf8, 0x87,
	0x02, 0x60, 0xd7, 0x25, 0xcc, 0x78, 0xc1, 0x51, 0x00, 0xfd, 0xa6, 0x12, 0x56, 0xdc, 0xa6, 0x4d,
	0xb2, 0xc1, 0xe4, 0xbd, 0xf1, 0x90, 0x5e, 0x8c, 0xc6, 0x8e, 0xde, 0xa6, 0x82, 0x40, 0x7c, 0xf7,
	0x8e, 0x3e, 0x40, 0xb7, 0x12, 0xea, 0x9d, 0x91, 0xba, 0xd7, 0x9f, 0xbc, 0x7d, 0x98, 0x67, 0xd3,
	0x18, 0xa9, 0x1d, 0xd0, 0x08, 0xfa, 0xab, 0x8c, 0x27, 0x65, 0xc4, 0xb3, 0xb0, 0xb8, 0xad, 0xb7,
	0xa4, 0x92, 0xdf, 0x97, 0xc6, 0x5f, 0x15, 0x18, 0x10, 0xc1, 0x97, 0x8f, 0xb3, 0xb3, 0x09, 0xf4,
	0x56, 0x99, 0x2c, 0xd3, 0xbc, 0xdd, 0xdb, 0xf0, 0xbe, 0x6b, 0x0b, 0x9f, 0x56, 0x12, 0xd2, 0x2a,
	0xc7, 0xdf, 0x14, 0x78, 0x7a, 0x91, 0x85, 0x85, 0x78, 0x9c, 0x88, 0x3a, 0x6c, 0x2c, 0x64, 0x54,
	0xc6, 0x49, 0x93, 0x71, 0x8b, 0xac, 0x47, 0x74, 0x00, 0xdd, 0x4c, 0xde, 0xe4, 0xba, 0x5a, 0x47,
	0xd7, 0xff, 0x18, 0x9d, 0xc8, 0x1b, 0x52, 0xab, 0xf6, 0xbf, 0xdf, 0xfd, 0x2e, 0xb5, 0xed, 0x10,
	0x76, 0x6c, 0x4c, 0xc9, 0x99, 0xe5, 0x31, 0x1a, 0xb8, 0x98, 0xf9, 0xce, 0x0c, 0x9f, 0x9c, 0x39,
	0x78, 0xa6, 0xfd, 0x87, 0x46, 0xf0, 0xd2, 0x72, 0x7d, 0xe6, 0x7b, 0xd3, 0x53, 0xcc, 0x3c, 0x6c,
	0xcd, 0x9d, 0x99, 0xc7, 0x5c, 0x4c, 0x2c, 0xec, 0xd0, 0xe9, 0x29, 0xd6, 0x14, 0xb4, 0x03, 0xc8,
	0xc6, 0xf6, 0x9c, 0x04, 0xad, 0xe8, 0x38, 0xa0, 0xd8, 0xd3, 0x3a, 0xe8, 0x39, 0x3c, 0x73, 0xe7,
	0x17, 0x98, 0xb4, 0xcb, 0x17, 0x53, 0x4a, 0x3d, 0x4d, 0x45, 0xbb, 0xb0, 0x4d, 0xb1, 0xed, 0x62,
	0x32, 0xa5, 0x3e, 0xc1, 0xcc, 0xc2, 0xe7, 0xde, 0x99, 0xef, 0x69, 0x5d, 0x34, 0x00, 0x98, 0xf9,
	0x34, 0x60, 0x56, 0x60, 0x9d, 0x63, 0xed, 0x7f, 0x84, 0x60, 0x60, 0xf9, 0x84, 0x60, 0x87, 0xb2,
	0xf9, 0xc9, 0x89, 0x87, 0xa9, 0xd6, 0xdb, 0x3f, 0x82, 0x27, 0x44, 0xe4, 0xb2, 0xcc, 0x16, 0xc2,
	0xe1, 0xf5, 0xa1, 0xd8, 0x25, 0xd8, 0x9b, 0xfb, 0xc4, 0xc2, 0xcc, 0x99, 0xda, 0xf7, 0xa3, 0x6f,
	0x80, 0x6a, 0xb9, 0xbe, 0xa6, 0x20, 0x80, 0x5e, 0x93, 0x50, 0xeb, 0x1c, 0x1f, 0x7f, 0x3a, 0x5a,
	0x85, 0x45, 0x5b, 0xb5, 0xf9, 0xab, 0xa6, 0xd7, 0x3c, 0x34, 0xab, 0x2b, 0xe6, 0x1f, 0xae, 0x9b,
	0xcb, 0x5e, 0x7d, 0x4e, 0xdf, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xf0, 0xe7, 0xe9, 0x9c,
	0x04, 0x00, 0x00,
}
