// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/common/queries.proto

package common

import (
	fmt "fmt"
	common "github.com/containers-ai/api/common"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeRange_AggregateFunction int32

const (
	TimeRange_NONE TimeRange_AggregateFunction = 0
	TimeRange_MAX  TimeRange_AggregateFunction = 1
	TimeRange_AVG  TimeRange_AggregateFunction = 2
)

var TimeRange_AggregateFunction_name = map[int32]string{
	0: "NONE",
	1: "MAX",
	2: "AVG",
}

var TimeRange_AggregateFunction_value = map[string]int32{
	"NONE": 0,
	"MAX":  1,
	"AVG":  2,
}

func (x TimeRange_AggregateFunction) String() string {
	return proto.EnumName(TimeRange_AggregateFunction_name, int32(x))
}

func (TimeRange_AggregateFunction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d602763cab07305c, []int{0, 0}
}

type QueryCondition_Order int32

const (
	QueryCondition_NONE QueryCondition_Order = 0
	QueryCondition_ASC  QueryCondition_Order = 1
	QueryCondition_DESC QueryCondition_Order = 2
)

var QueryCondition_Order_name = map[int32]string{
	0: "NONE",
	1: "ASC",
	2: "DESC",
}

var QueryCondition_Order_value = map[string]int32{
	"NONE": 0,
	"ASC":  1,
	"DESC": 2,
}

func (x QueryCondition_Order) String() string {
	return proto.EnumName(QueryCondition_Order_name, int32(x))
}

func (QueryCondition_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d602763cab07305c, []int{2, 0}
}

//*
// Represents a time range definition
//
type TimeRange struct {
	StartTime            *timestamp.Timestamp        `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp        `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Step                 *duration.Duration          `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	AggregateFunction    TimeRange_AggregateFunction `protobuf:"varint,4,opt,name=aggregateFunction,proto3,enum=containersai.alameda.v1alpha1.datahub.common.TimeRange_AggregateFunction" json:"aggregateFunction,omitempty"`
	ApplyTime            *timestamp.Timestamp        `protobuf:"bytes,5,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d602763cab07305c, []int{0}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeRange) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TimeRange) GetStep() *duration.Duration {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *TimeRange) GetAggregateFunction() TimeRange_AggregateFunction {
	if m != nil {
		return m.AggregateFunction
	}
	return TimeRange_NONE
}

func (m *TimeRange) GetApplyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ApplyTime
	}
	return nil
}

type WhereCondition struct {
	Keys                 []string          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values               []string          `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Operators            []string          `protobuf:"bytes,3,rep,name=operators,proto3" json:"operators,omitempty"`
	Types                []common.DataType `protobuf:"varint,4,rep,packed,name=types,proto3,enum=containersai.common.DataType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WhereCondition) Reset()         { *m = WhereCondition{} }
func (m *WhereCondition) String() string { return proto.CompactTextString(m) }
func (*WhereCondition) ProtoMessage()    {}
func (*WhereCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d602763cab07305c, []int{1}
}

func (m *WhereCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhereCondition.Unmarshal(m, b)
}
func (m *WhereCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhereCondition.Marshal(b, m, deterministic)
}
func (m *WhereCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhereCondition.Merge(m, src)
}
func (m *WhereCondition) XXX_Size() int {
	return xxx_messageInfo_WhereCondition.Size(m)
}
func (m *WhereCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_WhereCondition.DiscardUnknown(m)
}

var xxx_messageInfo_WhereCondition proto.InternalMessageInfo

func (m *WhereCondition) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *WhereCondition) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *WhereCondition) GetOperators() []string {
	if m != nil {
		return m.Operators
	}
	return nil
}

func (m *WhereCondition) GetTypes() []common.DataType {
	if m != nil {
		return m.Types
	}
	return nil
}

type QueryCondition struct {
	TimeRange            *TimeRange           `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Order                QueryCondition_Order `protobuf:"varint,2,opt,name=order,proto3,enum=containersai.alameda.v1alpha1.datahub.common.QueryCondition_Order" json:"order,omitempty"`
	Where                *WhereCondition      `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Groups               []string             `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Limit                uint64               `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryCondition) Reset()         { *m = QueryCondition{} }
func (m *QueryCondition) String() string { return proto.CompactTextString(m) }
func (*QueryCondition) ProtoMessage()    {}
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d602763cab07305c, []int{2}
}

func (m *QueryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCondition.Unmarshal(m, b)
}
func (m *QueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCondition.Marshal(b, m, deterministic)
}
func (m *QueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCondition.Merge(m, src)
}
func (m *QueryCondition) XXX_Size() int {
	return xxx_messageInfo_QueryCondition.Size(m)
}
func (m *QueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCondition proto.InternalMessageInfo

func (m *QueryCondition) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *QueryCondition) GetOrder() QueryCondition_Order {
	if m != nil {
		return m.Order
	}
	return QueryCondition_NONE
}

func (m *QueryCondition) GetWhere() *WhereCondition {
	if m != nil {
		return m.Where
	}
	return nil
}

func (m *QueryCondition) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *QueryCondition) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.common.TimeRange_AggregateFunction", TimeRange_AggregateFunction_name, TimeRange_AggregateFunction_value)
	proto.RegisterEnum("containersai.alameda.v1alpha1.datahub.common.QueryCondition_Order", QueryCondition_Order_name, QueryCondition_Order_value)
	proto.RegisterType((*TimeRange)(nil), "containersai.alameda.v1alpha1.datahub.common.TimeRange")
	proto.RegisterType((*WhereCondition)(nil), "containersai.alameda.v1alpha1.datahub.common.WhereCondition")
	proto.RegisterType((*QueryCondition)(nil), "containersai.alameda.v1alpha1.datahub.common.QueryCondition")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/common/queries.proto", fileDescriptor_d602763cab07305c)
}

var fileDescriptor_d602763cab07305c = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0xb2, 0x2d, 0x46, 0xaa, 0x3a, 0x0b, 0xa1, 0x30, 0xf1, 0x51, 0x55, 0x3c, 0xf4,
	0x81, 0x39, 0x6a, 0x27, 0x84, 0x90, 0x78, 0xa0, 0x1f, 0x03, 0xf1, 0xc0, 0x26, 0xbc, 0x6a, 0x4c,
	0xbc, 0x54, 0xb7, 0x8d, 0x49, 0x2d, 0x92, 0x38, 0x38, 0xce, 0xa6, 0xfe, 0x0a, 0xc4, 0xdf, 0xe4,
	0x57, 0x20, 0x3b, 0xee, 0xaa, 0xae, 0x0f, 0xa3, 0xbc, 0xe5, 0xfa, 0x9e, 0x73, 0x7c, 0x7d, 0xee,
	0x51, 0x50, 0x0f, 0x52, 0xc8, 0x58, 0x0c, 0x53, 0x28, 0x78, 0x74, 0xdd, 0x83, 0xb4, 0x58, 0x40,
	0x2f, 0x8a, 0x41, 0xc1, 0xa2, 0x9a, 0x45, 0x73, 0x91, 0x65, 0x22, 0x8f, 0x7e, 0x56, 0x4c, 0x72,
	0x56, 0x92, 0x42, 0x0a, 0x25, 0xf0, 0xab, 0xb9, 0xc8, 0x15, 0xf0, 0x9c, 0xc9, 0x12, 0x38, 0xb1,
	0x7c, 0xb2, 0xe2, 0x12, 0xcb, 0x25, 0x35, 0xf7, 0x08, 0x5b, 0x0d, 0xb5, 0x2c, 0x56, 0x0a, 0x47,
	0xcf, 0x13, 0x21, 0x92, 0x94, 0x45, 0xa6, 0x9a, 0x55, 0xdf, 0xa3, 0xb8, 0x92, 0xa0, 0xb8, 0xc8,
	0x6d, 0xff, 0xc5, 0xdd, 0xbe, 0xe2, 0x19, 0x2b, 0x15, 0x64, 0x45, 0x0d, 0xe8, 0xfc, 0x76, 0x51,
	0x30, 0xe1, 0x19, 0xa3, 0x90, 0x27, 0x0c, 0xbf, 0x45, 0xa8, 0x54, 0x20, 0xd5, 0x54, 0xc3, 0x42,
	0xa7, 0xed, 0x74, 0x1f, 0xf6, 0x8f, 0x48, 0xad, 0x41, 0x56, 0x1a, 0x64, 0xb2, 0xd2, 0xa0, 0x81,
	0x41, 0xeb, 0x1a, 0xbf, 0x46, 0x07, 0x2c, 0x8f, 0x6b, 0x62, 0xe3, 0x5e, 0xe2, 0x3e, 0xcb, 0x63,
	0x43, 0x3b, 0x46, 0x5e, 0xa9, 0x58, 0x11, 0xba, 0x86, 0xf2, 0x64, 0x8b, 0x32, 0xb6, 0xef, 0xa1,
	0x06, 0x86, 0x6f, 0xd0, 0x21, 0x24, 0x89, 0x64, 0x09, 0x28, 0xf6, 0xa1, 0xca, 0xe7, 0xba, 0x15,
	0x7a, 0x6d, 0xa7, 0xdb, 0xec, 0x7f, 0x22, 0xbb, 0xb8, 0x49, 0x6e, 0x1f, 0x4d, 0x06, 0x77, 0x05,
	0xe9, 0xf6, 0x1d, 0xda, 0x19, 0x28, 0x8a, 0x74, 0x59, 0x3f, 0xd0, 0xbf, 0xdf, 0x19, 0x83, 0xd6,
	0x75, 0x27, 0x42, 0x87, 0x5b, 0x57, 0xe0, 0x03, 0xe4, 0x9d, 0x9d, 0x9f, 0x9d, 0xb6, 0x1e, 0xe0,
	0x7d, 0xe4, 0x7e, 0x1e, 0x5c, 0xb5, 0x1c, 0xfd, 0x31, 0xb8, 0xfc, 0xd8, 0x6a, 0x74, 0x7e, 0x39,
	0xa8, 0xf9, 0x75, 0xc1, 0x24, 0x1b, 0x89, 0x3c, 0xe6, 0x06, 0x8e, 0x91, 0xf7, 0x83, 0x2d, 0xcb,
	0xd0, 0x69, 0xbb, 0xdd, 0x80, 0x9a, 0x6f, 0xfc, 0x18, 0xed, 0x5d, 0x43, 0x5a, 0xb1, 0x32, 0x6c,
	0x98, 0x53, 0x5b, 0xe1, 0xa7, 0x28, 0x10, 0x05, 0x93, 0xa0, 0x84, 0x2c, 0x43, 0xd7, 0xb4, 0xd6,
	0x07, 0xf8, 0x04, 0xf9, 0x26, 0x40, 0xa1, 0xd7, 0x76, 0xbb, 0xcd, 0xfe, 0xb3, 0x4d, 0xd7, 0xac,
	0x39, 0x63, 0x50, 0x30, 0x59, 0x16, 0x8c, 0xd6, 0xd8, 0xce, 0x9f, 0x06, 0x6a, 0x7e, 0xa9, 0x98,
	0x5c, 0xae, 0x27, 0xba, 0x44, 0x48, 0x5b, 0x31, 0x95, 0xda, 0x43, 0x1b, 0x95, 0x37, 0xff, 0xb9,
	0x02, 0x1a, 0xa8, 0xdb, 0x08, 0x5e, 0x21, 0x5f, 0xc8, 0x98, 0x49, 0x13, 0xa2, 0x66, 0x7f, 0xb8,
	0x9b, 0xe4, 0xe6, 0x90, 0xe4, 0x5c, 0x2b, 0xd1, 0x5a, 0x10, 0x53, 0xe4, 0xdf, 0x68, 0x57, 0x6d,
	0xd6, 0xde, 0xed, 0xa6, 0xbc, 0xb9, 0x10, 0x5a, 0x4b, 0xe9, 0x1d, 0x24, 0x52, 0x54, 0x45, 0x6d,
	0x67, 0x40, 0x6d, 0x85, 0x1f, 0x21, 0x3f, 0xe5, 0x19, 0x57, 0x26, 0x29, 0x1e, 0xad, 0x8b, 0xce,
	0x4b, 0xe4, 0x9b, 0x89, 0x36, 0xb7, 0x3f, 0xb8, 0x18, 0xb5, 0x1c, 0x7d, 0x34, 0x3e, 0xbd, 0x18,
	0xb5, 0x1a, 0xc3, 0xe1, 0xb7, 0xf7, 0x09, 0x57, 0xf6, 0xea, 0x68, 0x3d, 0xe4, 0x31, 0xf0, 0x48,
	0xff, 0x5b, 0xfe, 0xe1, 0x3f, 0x33, 0xdb, 0x33, 0x91, 0x3c, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x30, 0x70, 0x94, 0xf8, 0x95, 0x04, 0x00, 0x00,
}
