// source: datahub/recommendation/v1alpha2/recommendation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var datahub_resource_metadata_v1alpha2_metadata_pb = require('../../../datahub/resource/metadata/v1alpha2/metadata_pb.js');
goog.object.extend(proto, datahub_resource_metadata_v1alpha2_metadata_pb);
var datahub_resource_pod_assign_v1alpha2_assign_pb = require('../../../datahub/resource/pod/assign/v1alpha2/assign_pb.js');
goog.object.extend(proto, datahub_resource_pod_assign_v1alpha2_assign_pb);
var datahub_metric_v1alpha2_metric_pb = require('../../../datahub/metric/v1alpha2/metric_pb.js');
goog.object.extend(proto, datahub_metric_v1alpha2_metric_pb);
goog.exportSymbol('proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy', null, global);
goog.exportSymbol('proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.PolicyCase', null, global);
goog.exportSymbol('proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation', null, global);
goog.exportSymbol('proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation', null, global);
goog.exportSymbol('proto.containersai.datahub.recommendation.v1alpha2.RecommendationPolicy', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.displayName = 'proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_);
};
goog.inherits(proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.displayName = 'proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.repeatedFields_, null);
};
goog.inherits(proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.displayName = 'proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    limitRecommendationsMap: (f = msg.getLimitRecommendationsMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : [],
    requestRecommendationsMap: (f = msg.getRequestRecommendationsMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : [],
    initialLimitRecommendationsMap: (f = msg.getInitialLimitRecommendationsMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : [],
    initialRequestRecommendationsMap: (f = msg.getInitialRequestRecommendationsMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation;
  return proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = msg.getLimitRecommendationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    case 3:
      var value = msg.getRequestRecommendationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    case 4:
      var value = msg.getInitialLimitRecommendationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    case 5:
      var value = msg.getInitialRequestRecommendationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLimitRecommendationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
  f = message.getRequestRecommendationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
  f = message.getInitialLimitRecommendationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
  f = message.getInitialRequestRecommendationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<int32, containersai.datahub.metric.v1alpha2.MetricData> limit_recommendations = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.getLimitRecommendationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.clearLimitRecommendationsMap = function() {
  this.getLimitRecommendationsMap().clear();
  return this;};


/**
 * map<int32, containersai.datahub.metric.v1alpha2.MetricData> request_recommendations = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.getRequestRecommendationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.clearRequestRecommendationsMap = function() {
  this.getRequestRecommendationsMap().clear();
  return this;};


/**
 * map<int32, containersai.datahub.metric.v1alpha2.MetricData> initial_limit_recommendations = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.getInitialLimitRecommendationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.clearInitialLimitRecommendationsMap = function() {
  this.getInitialLimitRecommendationsMap().clear();
  return this;};


/**
 * map<int32, containersai.datahub.metric.v1alpha2.MetricData> initial_request_recommendations = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.getInitialRequestRecommendationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.prototype.clearInitialRequestRecommendationsMap = function() {
  this.getInitialRequestRecommendationsMap().clear();
  return this;};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.PolicyCase = {
  POLICY_NOT_SET: 0,
  NODE_PRIORITY: 2,
  NODE_SELECTOR: 3,
  NODE_NAME: 4
};

/**
 * @return {proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.PolicyCase}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.getPolicyCase = function() {
  return /** @type {proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.PolicyCase} */(jspb.Message.computeOneofCase(this, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.toObject = function(includeInstance, msg) {
  var f, obj = {
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    nodePriority: (f = msg.getNodePriority()) && datahub_resource_pod_assign_v1alpha2_assign_pb.NodePriority.toObject(includeInstance, f),
    nodeSelector: (f = msg.getNodeSelector()) && datahub_resource_pod_assign_v1alpha2_assign_pb.Selector.toObject(includeInstance, f),
    nodeName: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy;
  return proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 2:
      var value = new datahub_resource_pod_assign_v1alpha2_assign_pb.NodePriority;
      reader.readMessage(value,datahub_resource_pod_assign_v1alpha2_assign_pb.NodePriority.deserializeBinaryFromReader);
      msg.setNodePriority(value);
      break;
    case 3:
      var value = new datahub_resource_pod_assign_v1alpha2_assign_pb.Selector;
      reader.readMessage(value,datahub_resource_pod_assign_v1alpha2_assign_pb.Selector.deserializeBinaryFromReader);
      msg.setNodeSelector(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNodePriority();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      datahub_resource_pod_assign_v1alpha2_assign_pb.NodePriority.serializeBinaryToWriter
    );
  }
  f = message.getNodeSelector();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      datahub_resource_pod_assign_v1alpha2_assign_pb.Selector.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.hasTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional containersai.datahub.resource.pod.assign.v1alpha2.NodePriority node_priority = 2;
 * @return {?proto.containersai.datahub.resource.pod.assign.v1alpha2.NodePriority}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.getNodePriority = function() {
  return /** @type{?proto.containersai.datahub.resource.pod.assign.v1alpha2.NodePriority} */ (
    jspb.Message.getWrapperField(this, datahub_resource_pod_assign_v1alpha2_assign_pb.NodePriority, 2));
};


/**
 * @param {?proto.containersai.datahub.resource.pod.assign.v1alpha2.NodePriority|undefined} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.setNodePriority = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.clearNodePriority = function() {
  return this.setNodePriority(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.hasNodePriority = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional containersai.datahub.resource.pod.assign.v1alpha2.Selector node_selector = 3;
 * @return {?proto.containersai.datahub.resource.pod.assign.v1alpha2.Selector}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.getNodeSelector = function() {
  return /** @type{?proto.containersai.datahub.resource.pod.assign.v1alpha2.Selector} */ (
    jspb.Message.getWrapperField(this, datahub_resource_pod_assign_v1alpha2_assign_pb.Selector, 3));
};


/**
 * @param {?proto.containersai.datahub.resource.pod.assign.v1alpha2.Selector|undefined} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.setNodeSelector = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.clearNodeSelector = function() {
  return this.setNodeSelector(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.hasNodeSelector = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string node_name = 4;
 * @return {string}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.getNodeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.setNodeName = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.clearNodeName = function() {
  return jspb.Message.setOneofField(this, 4, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.prototype.hasNodeName = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespacedName: (f = msg.getNamespacedName()) && datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.toObject(includeInstance, f),
    applyRecommendationNow: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    assignPodPolicy: (f = msg.getAssignPodPolicy()) && proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.toObject(includeInstance, f),
    containerRecommendationsList: jspb.Message.toObjectList(msg.getContainerRecommendationsList(),
    proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation;
  return proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName;
      reader.readMessage(value,datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.deserializeBinaryFromReader);
      msg.setNamespacedName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setApplyRecommendationNow(value);
      break;
    case 3:
      var value = new proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy;
      reader.readMessage(value,proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.deserializeBinaryFromReader);
      msg.setAssignPodPolicy(value);
      break;
    case 4:
      var value = new proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation;
      reader.readMessage(value,proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.deserializeBinaryFromReader);
      msg.addContainerRecommendations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespacedName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.serializeBinaryToWriter
    );
  }
  f = message.getApplyRecommendationNow();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAssignPodPolicy();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy.serializeBinaryToWriter
    );
  }
  f = message.getContainerRecommendationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation.serializeBinaryToWriter
    );
  }
};


/**
 * optional containersai.datahub.resource.metadata.v1alpha2.NamespacedName namespaced_name = 1;
 * @return {?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.getNamespacedName = function() {
  return /** @type{?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName} */ (
    jspb.Message.getWrapperField(this, datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName, 1));
};


/**
 * @param {?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName|undefined} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.setNamespacedName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.clearNamespacedName = function() {
  return this.setNamespacedName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.hasNamespacedName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool apply_recommendation_now = 2;
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.getApplyRecommendationNow = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.setApplyRecommendationNow = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional AssignPodPolicy assign_pod_policy = 3;
 * @return {?proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.getAssignPodPolicy = function() {
  return /** @type{?proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy} */ (
    jspb.Message.getWrapperField(this, proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy, 3));
};


/**
 * @param {?proto.containersai.datahub.recommendation.v1alpha2.AssignPodPolicy|undefined} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.setAssignPodPolicy = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.clearAssignPodPolicy = function() {
  return this.setAssignPodPolicy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.hasAssignPodPolicy = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated ContainerRecommendation container_recommendations = 4;
 * @return {!Array<!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation>}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.getContainerRecommendationsList = function() {
  return /** @type{!Array<!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation, 4));
};


/**
 * @param {!Array<!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation>} value
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
*/
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.setContainerRecommendationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation}
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.addContainerRecommendations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.containersai.datahub.recommendation.v1alpha2.ContainerRecommendation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation} returns this
 */
proto.containersai.datahub.recommendation.v1alpha2.PodRecommendation.prototype.clearContainerRecommendationsList = function() {
  return this.setContainerRecommendationsList([]);
};


/**
 * @enum {number}
 */
proto.containersai.datahub.recommendation.v1alpha2.RecommendationPolicy = {
  RECOMMENDATIONPOLICY_UNDEFINED: 0,
  STABLE: 1,
  COMPACT: 2
};

goog.object.extend(exports, proto.containersai.datahub.recommendation.v1alpha2);
