// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/applications/services.proto

package applications

import (
	fmt "fmt"
	common "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/common"
	schemas "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/schemas"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateApplicationsRequest struct {
	Applications         []*WriteApplication `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateApplicationsRequest) Reset()         { *m = CreateApplicationsRequest{} }
func (m *CreateApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationsRequest) ProtoMessage()    {}
func (*CreateApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f2a91df07831ee, []int{0}
}

func (m *CreateApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationsRequest.Unmarshal(m, b)
}
func (m *CreateApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationsRequest.Merge(m, src)
}
func (m *CreateApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationsRequest.Size(m)
}
func (m *CreateApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationsRequest proto.InternalMessageInfo

func (m *CreateApplicationsRequest) GetApplications() []*WriteApplication {
	if m != nil {
		return m.Applications
	}
	return nil
}

type ListApplicationsRequest struct {
	SchemaMeta           *schemas.SchemaMeta    `protobuf:"bytes,1,opt,name=schema_meta,json=schemaMeta,proto3" json:"schema_meta,omitempty"`
	Where                *common.WhereCondition `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListApplicationsRequest) Reset()         { *m = ListApplicationsRequest{} }
func (m *ListApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsRequest) ProtoMessage()    {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f2a91df07831ee, []int{1}
}

func (m *ListApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsRequest.Unmarshal(m, b)
}
func (m *ListApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsRequest.Merge(m, src)
}
func (m *ListApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsRequest.Size(m)
}
func (m *ListApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsRequest proto.InternalMessageInfo

func (m *ListApplicationsRequest) GetSchemaMeta() *schemas.SchemaMeta {
	if m != nil {
		return m.SchemaMeta
	}
	return nil
}

func (m *ListApplicationsRequest) GetWhere() *common.WhereCondition {
	if m != nil {
		return m.Where
	}
	return nil
}

type ListApplicationsResponse struct {
	Status               *status.Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Applications         []*ReadApplication `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListApplicationsResponse) Reset()         { *m = ListApplicationsResponse{} }
func (m *ListApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsResponse) ProtoMessage()    {}
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f2a91df07831ee, []int{2}
}

func (m *ListApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsResponse.Unmarshal(m, b)
}
func (m *ListApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsResponse.Merge(m, src)
}
func (m *ListApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsResponse.Size(m)
}
func (m *ListApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsResponse proto.InternalMessageInfo

func (m *ListApplicationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListApplicationsResponse) GetApplications() []*ReadApplication {
	if m != nil {
		return m.Applications
	}
	return nil
}

type DeleteApplicationsRequest struct {
	SchemaMeta           *schemas.SchemaMeta    `protobuf:"bytes,1,opt,name=schema_meta,json=schemaMeta,proto3" json:"schema_meta,omitempty"`
	Where                *common.WhereCondition `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeleteApplicationsRequest) Reset()         { *m = DeleteApplicationsRequest{} }
func (m *DeleteApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationsRequest) ProtoMessage()    {}
func (*DeleteApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f2a91df07831ee, []int{3}
}

func (m *DeleteApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationsRequest.Unmarshal(m, b)
}
func (m *DeleteApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationsRequest.Merge(m, src)
}
func (m *DeleteApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationsRequest.Size(m)
}
func (m *DeleteApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationsRequest proto.InternalMessageInfo

func (m *DeleteApplicationsRequest) GetSchemaMeta() *schemas.SchemaMeta {
	if m != nil {
		return m.SchemaMeta
	}
	return nil
}

func (m *DeleteApplicationsRequest) GetWhere() *common.WhereCondition {
	if m != nil {
		return m.Where
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateApplicationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.applications.CreateApplicationsRequest")
	proto.RegisterType((*ListApplicationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.applications.ListApplicationsRequest")
	proto.RegisterType((*ListApplicationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.applications.ListApplicationsResponse")
	proto.RegisterType((*DeleteApplicationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.applications.DeleteApplicationsRequest")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/applications/services.proto", fileDescriptor_c6f2a91df07831ee)
}

var fileDescriptor_c6f2a91df07831ee = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xb1, 0x6e, 0xea, 0x30,
	0x14, 0x86, 0x15, 0xae, 0x2e, 0x83, 0xb9, 0x53, 0x16, 0x02, 0x13, 0x62, 0x42, 0x57, 0xba, 0xf6,
	0x85, 0x2e, 0xad, 0xc4, 0xd2, 0x82, 0xaa, 0x0e, 0xed, 0x12, 0x06, 0x24, 0x16, 0x74, 0x48, 0x8e,
	0x12, 0x4b, 0x49, 0x6c, 0x6c, 0x87, 0xaa, 0x0f, 0xd0, 0xe7, 0xe9, 0x73, 0x54, 0x7d, 0xa9, 0x8a,
	0xc4, 0xd0, 0xd0, 0x52, 0x94, 0x76, 0xeb, 0x94, 0x44, 0xf6, 0xf9, 0xce, 0xff, 0xff, 0x27, 0x87,
	0x9c, 0x43, 0x02, 0x29, 0x86, 0xb0, 0x04, 0xc9, 0xd9, 0x66, 0x08, 0x89, 0x8c, 0x61, 0xc8, 0x42,
	0x30, 0x10, 0xe7, 0x2b, 0x06, 0x52, 0x26, 0x3c, 0x00, 0xc3, 0x45, 0xa6, 0x99, 0x46, 0xb5, 0xe1,
	0x01, 0x6a, 0x2a, 0x95, 0x30, 0xc2, 0x1d, 0x05, 0x22, 0x33, 0xc0, 0x33, 0x54, 0x1a, 0x38, 0xb5,
	0x18, 0xba, 0x43, 0x50, 0x8b, 0xa0, 0x55, 0x44, 0x77, 0x5c, 0xbf, 0x5b, 0xf5, 0xa3, 0xec, 0xd8,
	0x1d, 0x9e, 0xac, 0x0e, 0x44, 0x9a, 0x8a, 0x8c, 0xad, 0x73, 0x54, 0x7c, 0x27, 0xb2, 0xfb, 0xff,
	0x64, 0x89, 0x0e, 0x62, 0x4c, 0x41, 0x33, 0xf3, 0x20, 0xf7, 0x15, 0xed, 0x48, 0x88, 0x28, 0x41,
	0xa6, 0x64, 0xc0, 0xb4, 0x01, 0x93, 0xdb, 0x83, 0xfe, 0xa3, 0x43, 0x3a, 0x13, 0x85, 0x60, 0xf0,
	0xb2, 0x22, 0xcd, 0xc7, 0x75, 0x8e, 0xda, 0xb8, 0x31, 0xf9, 0x53, 0x55, 0xec, 0x39, 0xbd, 0x5f,
	0x83, 0xd6, 0x68, 0x4a, 0xbf, 0x1e, 0x12, 0x9d, 0x2b, 0x7e, 0xd0, 0xc3, 0x3f, 0x20, 0xf7, 0x9f,
	0x1d, 0xd2, 0xbe, 0xe5, 0xda, 0x1c, 0x53, 0xb1, 0x20, 0xad, 0xd2, 0xd3, 0x32, 0x45, 0x03, 0x9e,
	0xd3, 0x73, 0x06, 0xad, 0xd1, 0x45, 0x4d, 0x11, 0x36, 0x0d, 0x3a, 0x2b, 0x9e, 0x77, 0x68, 0xc0,
	0x27, 0x7a, 0xff, 0xee, 0xfa, 0xe4, 0xf7, 0x7d, 0x8c, 0x0a, 0xbd, 0x46, 0x41, 0x1d, 0xd7, 0xa4,
	0x96, 0x63, 0xa1, 0xf3, 0x6d, 0xe9, 0x44, 0x64, 0x21, 0x2f, 0x2c, 0x95, 0xa8, 0xfe, 0x93, 0x43,
	0xbc, 0x8f, 0x5e, 0xb4, 0x14, 0x99, 0x46, 0xf7, 0x2f, 0x69, 0x96, 0x03, 0xb0, 0x3e, 0x5c, 0x5a,
	0x8e, 0x86, 0x2a, 0x19, 0xd0, 0x59, 0x71, 0xe2, 0xdb, 0x1b, 0x6e, 0xf4, 0x2e, 0xfe, 0x46, 0x11,
	0xff, 0xe4, 0x3b, 0xf1, 0xfb, 0x08, 0xe1, 0xe7, 0xe9, 0xbf, 0x38, 0xa4, 0x33, 0xc5, 0x04, 0x8f,
	0xff, 0x05, 0x3f, 0x2c, 0xff, 0xab, 0x9b, 0xc5, 0x75, 0xc4, 0x8d, 0xbd, 0xc6, 0xde, 0x80, 0xff,
	0x80, 0xb3, 0xed, 0xc6, 0xd4, 0x5e, 0xd7, 0x55, 0xb3, 0x58, 0x92, 0xb3, 0xd7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x2f, 0x61, 0x37, 0x50, 0x04, 0x00, 0x00,
}
