// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datahub/metric/v1alpha2/metric.proto

package containersai_datahub_metric_v1alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha2 "datahub/resource/metadata/v1alpha2"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Metric type. A metric may be either CPU or memory.
type MetricType int32

const (
	MetricType_UNDEFINED                    MetricType = 0
	MetricType_CPU_USAGE_SECONDS_PERCENTAGE MetricType = 1
	MetricType_MEMORY_USAGE_BYTES           MetricType = 2
)

var MetricType_name = map[int32]string{
	0: "UNDEFINED",
	1: "CPU_USAGE_SECONDS_PERCENTAGE",
	2: "MEMORY_USAGE_BYTES",
}
var MetricType_value = map[string]int32{
	"UNDEFINED":                    0,
	"CPU_USAGE_SECONDS_PERCENTAGE": 1,
	"MEMORY_USAGE_BYTES":           2,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{0}
}

// *
// Represents metric data of a container
type ContainerMetric struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MetricData           []*MetricData `protobuf:"bytes,2,rep,name=metric_data,json=metricData,proto3" json:"metric_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ContainerMetric) Reset()         { *m = ContainerMetric{} }
func (m *ContainerMetric) String() string { return proto.CompactTextString(m) }
func (*ContainerMetric) ProtoMessage()    {}
func (*ContainerMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{0}
}
func (m *ContainerMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerMetric.Unmarshal(m, b)
}
func (m *ContainerMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerMetric.Marshal(b, m, deterministic)
}
func (dst *ContainerMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerMetric.Merge(dst, src)
}
func (m *ContainerMetric) XXX_Size() int {
	return xxx_messageInfo_ContainerMetric.Size(m)
}
func (m *ContainerMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerMetric.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerMetric proto.InternalMessageInfo

func (m *ContainerMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerMetric) GetMetricData() []*MetricData {
	if m != nil {
		return m.MetricData
	}
	return nil
}

// *
// Represents metric data of a pod
type PodMetric struct {
	NamespacedName       *v1alpha2.NamespacedName `protobuf:"bytes,1,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	ContainerMetrics     []*ContainerMetric       `protobuf:"bytes,2,rep,name=container_metrics,json=containerMetrics,proto3" json:"container_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PodMetric) Reset()         { *m = PodMetric{} }
func (m *PodMetric) String() string { return proto.CompactTextString(m) }
func (*PodMetric) ProtoMessage()    {}
func (*PodMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{1}
}
func (m *PodMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodMetric.Unmarshal(m, b)
}
func (m *PodMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodMetric.Marshal(b, m, deterministic)
}
func (dst *PodMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodMetric.Merge(dst, src)
}
func (m *PodMetric) XXX_Size() int {
	return xxx_messageInfo_PodMetric.Size(m)
}
func (m *PodMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PodMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PodMetric proto.InternalMessageInfo

func (m *PodMetric) GetNamespacedName() *v1alpha2.NamespacedName {
	if m != nil {
		return m.NamespacedName
	}
	return nil
}

func (m *PodMetric) GetContainerMetrics() []*ContainerMetric {
	if m != nil {
		return m.ContainerMetrics
	}
	return nil
}

// *
// Represents metric data of a node
type NodeMetric struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MetricData           []*MetricData `protobuf:"bytes,2,rep,name=metric_data,json=metricData,proto3" json:"metric_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeMetric) Reset()         { *m = NodeMetric{} }
func (m *NodeMetric) String() string { return proto.CompactTextString(m) }
func (*NodeMetric) ProtoMessage()    {}
func (*NodeMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{2}
}
func (m *NodeMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMetric.Unmarshal(m, b)
}
func (m *NodeMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMetric.Marshal(b, m, deterministic)
}
func (dst *NodeMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMetric.Merge(dst, src)
}
func (m *NodeMetric) XXX_Size() int {
	return xxx_messageInfo_NodeMetric.Size(m)
}
func (m *NodeMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMetric.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMetric proto.InternalMessageInfo

func (m *NodeMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeMetric) GetMetricData() []*MetricData {
	if m != nil {
		return m.MetricData
	}
	return nil
}

// *
// Represents a data point of time-series metric data
type Sample struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	NumValue             string               `protobuf:"bytes,2,opt,name=num_value,json=numValue,proto3" json:"num_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{3}
}
func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (dst *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(dst, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Sample) GetNumValue() string {
	if m != nil {
		return m.NumValue
	}
	return ""
}

// *
// Represents a time range definition
//
type TimeRange struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Step                 *duration.Duration   `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{4}
}
func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (dst *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(dst, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeRange) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TimeRange) GetStep() *duration.Duration {
	if m != nil {
		return m.Step
	}
	return nil
}

// *
// Represents a piece of metreic data
type MetricData struct {
	MetricType MetricType `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=containersai.datahub.metric.v1alpha2.MetricType" json:"metric_type,omitempty"`
	// data can be time series or non-time series
	Data                 []*Sample `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricData) Reset()         { *m = MetricData{} }
func (m *MetricData) String() string { return proto.CompactTextString(m) }
func (*MetricData) ProtoMessage()    {}
func (*MetricData) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_3e16daea3cebaf66, []int{5}
}
func (m *MetricData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricData.Unmarshal(m, b)
}
func (m *MetricData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricData.Marshal(b, m, deterministic)
}
func (dst *MetricData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricData.Merge(dst, src)
}
func (m *MetricData) XXX_Size() int {
	return xxx_messageInfo_MetricData.Size(m)
}
func (m *MetricData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricData.DiscardUnknown(m)
}

var xxx_messageInfo_MetricData proto.InternalMessageInfo

func (m *MetricData) GetMetricType() MetricType {
	if m != nil {
		return m.MetricType
	}
	return MetricType_UNDEFINED
}

func (m *MetricData) GetData() []*Sample {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ContainerMetric)(nil), "containersai.datahub.metric.v1alpha2.ContainerMetric")
	proto.RegisterType((*PodMetric)(nil), "containersai.datahub.metric.v1alpha2.PodMetric")
	proto.RegisterType((*NodeMetric)(nil), "containersai.datahub.metric.v1alpha2.NodeMetric")
	proto.RegisterType((*Sample)(nil), "containersai.datahub.metric.v1alpha2.Sample")
	proto.RegisterType((*TimeRange)(nil), "containersai.datahub.metric.v1alpha2.TimeRange")
	proto.RegisterType((*MetricData)(nil), "containersai.datahub.metric.v1alpha2.MetricData")
	proto.RegisterEnum("containersai.datahub.metric.v1alpha2.MetricType", MetricType_name, MetricType_value)
}

func init() {
	proto.RegisterFile("datahub/metric/v1alpha2/metric.proto", fileDescriptor_metric_3e16daea3cebaf66)
}

var fileDescriptor_metric_3e16daea3cebaf66 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0x39, 0x8d, 0xfa, 0xab, 0x27, 0xa2, 0x0d, 0x7b, 0x40, 0x21, 0x20, 0x88, 0xac, 0x1e,
	0x2a, 0x04, 0x1b, 0x1a, 0xd4, 0x03, 0x27, 0x28, 0xb1, 0xa9, 0x38, 0xc4, 0x0d, 0xeb, 0x18, 0xa9,
	0x27, 0x6b, 0x63, 0x2f, 0x89, 0xa5, 0x78, 0x6d, 0xd9, 0xeb, 0x8a, 0x7e, 0x1c, 0xee, 0x7c, 0x21,
	0xbe, 0x0d, 0xda, 0x3f, 0x36, 0x4d, 0x41, 0x22, 0x5c, 0xb8, 0xcd, 0x8c, 0xe7, 0xcd, 0x7b, 0xf3,
	0x76, 0x0c, 0xc7, 0x09, 0x15, 0x74, 0x5d, 0x2f, 0xc7, 0x19, 0x13, 0x65, 0x1a, 0x8f, 0xaf, 0x4f,
	0xe9, 0xa6, 0x58, 0xd3, 0x89, 0xc9, 0x71, 0x51, 0xe6, 0x22, 0x47, 0xc7, 0x71, 0xce, 0x05, 0x4d,
	0x39, 0x2b, 0x2b, 0x9a, 0x62, 0x03, 0xc1, 0xa6, 0xa5, 0x81, 0x0c, 0x9f, 0xae, 0xf2, 0x7c, 0xb5,
	0x61, 0x63, 0x85, 0x59, 0xd6, 0x9f, 0xc7, 0x22, 0xcd, 0x58, 0x25, 0x68, 0x56, 0xe8, 0x31, 0xc3,
	0x27, 0x77, 0x1b, 0x92, 0xba, 0xa4, 0x22, 0xcd, 0xb9, 0xf9, 0x7e, 0xda, 0x88, 0x29, 0x59, 0x95,
	0xd7, 0x65, 0xcc, 0xa4, 0x0a, 0x2a, 0x8b, 0x5b, 0xba, 0x54, 0x45, 0x43, 0x9c, 0x2f, 0x70, 0x34,
	0x6d, 0xb4, 0xcd, 0x94, 0x1e, 0x84, 0xa0, 0xcb, 0x69, 0xc6, 0x06, 0xd6, 0xc8, 0x3a, 0xb1, 0x89,
	0x8a, 0xd1, 0x47, 0xe8, 0x69, 0xb5, 0x91, 0xc4, 0x0e, 0x3a, 0xa3, 0xbd, 0x93, 0xde, 0xe4, 0x25,
	0xde, 0x65, 0x2d, 0xac, 0xc7, 0xba, 0x54, 0x50, 0x02, 0x59, 0x1b, 0x3b, 0xdf, 0x2d, 0xb0, 0xe7,
	0x79, 0x62, 0x48, 0xd7, 0x70, 0x24, 0x89, 0xaa, 0x82, 0xc6, 0x2c, 0x89, 0x5a, 0xfe, 0xde, 0xe4,
	0xcd, 0xef, 0x49, 0x9a, 0x0d, 0x71, 0xbb, 0x4f, 0xcb, 0xe7, 0xb7, 0x73, 0x64, 0x44, 0x0e, 0xf9,
	0x56, 0x8e, 0x96, 0x70, 0xbf, 0x9d, 0x18, 0x69, 0x3d, 0x95, 0x59, 0xe8, 0x6c, 0xb7, 0x85, 0xee,
	0x18, 0x46, 0xfa, 0xf1, 0x76, 0xa1, 0x72, 0x2a, 0x00, 0x3f, 0x4f, 0xd8, 0xbf, 0x35, 0x34, 0x84,
	0xfd, 0x80, 0x66, 0xc5, 0x86, 0x21, 0x0c, 0x5d, 0x79, 0x3a, 0xc6, 0xc1, 0x21, 0xd6, 0x67, 0x83,
	0x9b, 0xb3, 0xc1, 0x8b, 0xe6, 0xae, 0x88, 0xea, 0x43, 0x8f, 0xc0, 0xe6, 0x75, 0x16, 0x5d, 0xd3,
	0x4d, 0xcd, 0x06, 0x1d, 0xa5, 0xf2, 0x80, 0xd7, 0xd9, 0x27, 0x99, 0x3b, 0xdf, 0x2c, 0xb0, 0x25,
	0x80, 0x50, 0xbe, 0x62, 0xe8, 0x35, 0x40, 0x25, 0x68, 0x29, 0xa2, 0x1d, 0x09, 0x6c, 0xd5, 0x2d,
	0x73, 0x74, 0x06, 0x07, 0x8c, 0x27, 0x1a, 0xd8, 0xf9, 0x23, 0xf0, 0x7f, 0xc6, 0x13, 0x05, 0x7b,
	0x01, 0xdd, 0x4a, 0xb0, 0x62, 0xb0, 0xa7, 0x20, 0x0f, 0x7f, 0x81, 0xb8, 0xe6, 0x1f, 0x20, 0xaa,
	0xcd, 0xf9, 0x6a, 0x01, 0xfc, 0x34, 0xe8, 0x96, 0xcf, 0xe2, 0xa6, 0xd0, 0x82, 0x0f, 0xff, 0xce,
	0xe7, 0xc5, 0x4d, 0xc1, 0x1a, 0x9f, 0x65, 0x8c, 0xde, 0x42, 0xf7, 0xd6, 0x9b, 0x3d, 0xdf, 0x6d,
	0x96, 0x7e, 0x19, 0xa2, 0x90, 0xcf, 0xc2, 0x46, 0xa2, 0x9a, 0x77, 0x0f, 0xec, 0xd0, 0x77, 0xbd,
	0xf7, 0x1f, 0x7c, 0xcf, 0xed, 0xff, 0x87, 0x46, 0xf0, 0x78, 0x3a, 0x0f, 0xa3, 0x30, 0x38, 0xbf,
	0xf0, 0xa2, 0xc0, 0x9b, 0x5e, 0xfa, 0x6e, 0x10, 0xcd, 0x3d, 0x32, 0xf5, 0xfc, 0xc5, 0xf9, 0x85,
	0xd7, 0xb7, 0xd0, 0x03, 0x40, 0x33, 0x6f, 0x76, 0x49, 0xae, 0x4c, 0xd3, 0xbb, 0xab, 0x85, 0x17,
	0xf4, 0x3b, 0xcb, 0x7d, 0xe5, 0xc9, 0xab, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x07, 0x1d,
	0x23, 0x94, 0x04, 0x00, 0x00,
}
