// source: datahub/metric/v1alpha2/metric.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var datahub_resource_metadata_v1alpha2_metadata_pb = require('../../../datahub/resource/metadata/v1alpha2/metadata_pb.js');
goog.object.extend(proto, datahub_resource_metadata_v1alpha2_metadata_pb);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.ContainerMetric', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.MetricData', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.MetricType', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.NodeMetric', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.PodMetric', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.Sample', null, global);
goog.exportSymbol('proto.containersai.datahub.metric.v1alpha2.TimeRange', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.ContainerMetric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.ContainerMetric.displayName = 'proto.containersai.datahub.metric.v1alpha2.ContainerMetric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.containersai.datahub.metric.v1alpha2.PodMetric.repeatedFields_, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.PodMetric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.PodMetric.displayName = 'proto.containersai.datahub.metric.v1alpha2.PodMetric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.NodeMetric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.NodeMetric.displayName = 'proto.containersai.datahub.metric.v1alpha2.NodeMetric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.Sample = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.Sample, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.Sample.displayName = 'proto.containersai.datahub.metric.v1alpha2.Sample';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.TimeRange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.TimeRange.displayName = 'proto.containersai.datahub.metric.v1alpha2.TimeRange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.containersai.datahub.metric.v1alpha2.MetricData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.containersai.datahub.metric.v1alpha2.MetricData.repeatedFields_, null);
};
goog.inherits(proto.containersai.datahub.metric.v1alpha2.MetricData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.containersai.datahub.metric.v1alpha2.MetricData.displayName = 'proto.containersai.datahub.metric.v1alpha2.MetricData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.ContainerMetric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    metricDataMap: (f = msg.getMetricDataMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.ContainerMetric;
  return proto.containersai.datahub.metric.v1alpha2.ContainerMetric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = msg.getMetricDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.ContainerMetric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMetricDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<int32, MetricData> metric_data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.getMetricDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.ContainerMetric.prototype.clearMetricDataMap = function() {
  this.getMetricDataMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.PodMetric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.PodMetric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespacedName: (f = msg.getNamespacedName()) && datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.toObject(includeInstance, f),
    containerMetricsList: jspb.Message.toObjectList(msg.getContainerMetricsList(),
    proto.containersai.datahub.metric.v1alpha2.ContainerMetric.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.PodMetric;
  return proto.containersai.datahub.metric.v1alpha2.PodMetric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.PodMetric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName;
      reader.readMessage(value,datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.deserializeBinaryFromReader);
      msg.setNamespacedName(value);
      break;
    case 2:
      var value = new proto.containersai.datahub.metric.v1alpha2.ContainerMetric;
      reader.readMessage(value,proto.containersai.datahub.metric.v1alpha2.ContainerMetric.deserializeBinaryFromReader);
      msg.addContainerMetrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.PodMetric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.PodMetric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespacedName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName.serializeBinaryToWriter
    );
  }
  f = message.getContainerMetricsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.containersai.datahub.metric.v1alpha2.ContainerMetric.serializeBinaryToWriter
    );
  }
};


/**
 * optional containersai.datahub.resource.metadata.v1alpha2.NamespacedName namespaced_name = 1;
 * @return {?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.getNamespacedName = function() {
  return /** @type{?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName} */ (
    jspb.Message.getWrapperField(this, datahub_resource_metadata_v1alpha2_metadata_pb.NamespacedName, 1));
};


/**
 * @param {?proto.containersai.datahub.resource.metadata.v1alpha2.NamespacedName|undefined} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric} returns this
*/
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.setNamespacedName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.clearNamespacedName = function() {
  return this.setNamespacedName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.hasNamespacedName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ContainerMetric container_metrics = 2;
 * @return {!Array<!proto.containersai.datahub.metric.v1alpha2.ContainerMetric>}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.getContainerMetricsList = function() {
  return /** @type{!Array<!proto.containersai.datahub.metric.v1alpha2.ContainerMetric>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.containersai.datahub.metric.v1alpha2.ContainerMetric, 2));
};


/**
 * @param {!Array<!proto.containersai.datahub.metric.v1alpha2.ContainerMetric>} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric} returns this
*/
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.setContainerMetricsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric=} opt_value
 * @param {number=} opt_index
 * @return {!proto.containersai.datahub.metric.v1alpha2.ContainerMetric}
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.addContainerMetrics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.containersai.datahub.metric.v1alpha2.ContainerMetric, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.containersai.datahub.metric.v1alpha2.PodMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.PodMetric.prototype.clearContainerMetricsList = function() {
  return this.setContainerMetricsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.NodeMetric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.NodeMetric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    metricDataMap: (f = msg.getMetricDataMap()) ? f.toObject(includeInstance, proto.containersai.datahub.metric.v1alpha2.MetricData.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.NodeMetric}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.NodeMetric;
  return proto.containersai.datahub.metric.v1alpha2.NodeMetric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.NodeMetric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.NodeMetric}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = msg.getMetricDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader, 0, new proto.containersai.datahub.metric.v1alpha2.MetricData());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.NodeMetric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.NodeMetric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMetricDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.NodeMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<int32, MetricData> metric_data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>}
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.getMetricDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.containersai.datahub.metric.v1alpha2.MetricData>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.containersai.datahub.metric.v1alpha2.MetricData));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.containersai.datahub.metric.v1alpha2.NodeMetric} returns this
 */
proto.containersai.datahub.metric.v1alpha2.NodeMetric.prototype.clearMetricDataMap = function() {
  this.getMetricDataMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.Sample.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.Sample} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.Sample.toObject = function(includeInstance, msg) {
  var f, obj = {
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    numValue: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.Sample;
  return proto.containersai.datahub.metric.v1alpha2.Sample.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.Sample} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.Sample.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.Sample} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.Sample.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNumValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample} returns this
*/
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample} returns this
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.hasTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string num_value = 2;
 * @return {string}
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.getNumValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample} returns this
 */
proto.containersai.datahub.metric.v1alpha2.Sample.prototype.setNumValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.TimeRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.TimeRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    step: (f = msg.getStep()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.TimeRange;
  return proto.containersai.datahub.metric.v1alpha2.TimeRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.TimeRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setStep(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.TimeRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.TimeRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStep();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp start_time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
*/
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
*/
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Duration step = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.getStep = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
*/
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.setStep = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.containersai.datahub.metric.v1alpha2.TimeRange} returns this
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.clearStep = function() {
  return this.setStep(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.containersai.datahub.metric.v1alpha2.TimeRange.prototype.hasStep = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.toObject = function(opt_includeInstance) {
  return proto.containersai.datahub.metric.v1alpha2.MetricData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.containersai.datahub.metric.v1alpha2.MetricData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.containersai.datahub.metric.v1alpha2.Sample.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.containersai.datahub.metric.v1alpha2.MetricData}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.containersai.datahub.metric.v1alpha2.MetricData;
  return proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.containersai.datahub.metric.v1alpha2.MetricData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.containersai.datahub.metric.v1alpha2.MetricData}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.containersai.datahub.metric.v1alpha2.Sample;
      reader.readMessage(value,proto.containersai.datahub.metric.v1alpha2.Sample.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.containersai.datahub.metric.v1alpha2.MetricData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.containersai.datahub.metric.v1alpha2.Sample.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Sample data = 1;
 * @return {!Array<!proto.containersai.datahub.metric.v1alpha2.Sample>}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.getDataList = function() {
  return /** @type{!Array<!proto.containersai.datahub.metric.v1alpha2.Sample>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.containersai.datahub.metric.v1alpha2.Sample, 1));
};


/**
 * @param {!Array<!proto.containersai.datahub.metric.v1alpha2.Sample>} value
 * @return {!proto.containersai.datahub.metric.v1alpha2.MetricData} returns this
*/
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.containersai.datahub.metric.v1alpha2.Sample=} opt_value
 * @param {number=} opt_index
 * @return {!proto.containersai.datahub.metric.v1alpha2.Sample}
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.containersai.datahub.metric.v1alpha2.Sample, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.containersai.datahub.metric.v1alpha2.MetricData} returns this
 */
proto.containersai.datahub.metric.v1alpha2.MetricData.prototype.clearDataList = function() {
  return this.setDataList([]);
};


/**
 * @enum {number}
 */
proto.containersai.datahub.metric.v1alpha2.MetricType = {
  UNDEFINED: 0,
  CPU_USAGE_SECONDS_PERCENTAGE: 1,
  MEMORY_USAGE_BYTES: 2
};

goog.object.extend(exports, proto.containersai.datahub.metric.v1alpha2);
