// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/recommendations/recommendations.proto

package recommendations

import (
	fmt "fmt"
	common "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/common"
	resources "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/resources"
	schemas "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/schemas"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a resource configuration recommendation
// It includes recommended limits and requests for the initial stage (a container which is just started) and after the initial stage
type ContainerRecommendation struct {
	Name                          string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LimitRecommendations          []*common.MetricData `protobuf:"bytes,2,rep,name=limit_recommendations,json=limitRecommendations,proto3" json:"limit_recommendations,omitempty"`
	RequestRecommendations        []*common.MetricData `protobuf:"bytes,3,rep,name=request_recommendations,json=requestRecommendations,proto3" json:"request_recommendations,omitempty"`
	InitialLimitRecommendations   []*common.MetricData `protobuf:"bytes,4,rep,name=initial_limit_recommendations,json=initialLimitRecommendations,proto3" json:"initial_limit_recommendations,omitempty"`
	InitialRequestRecommendations []*common.MetricData `protobuf:"bytes,5,rep,name=initial_request_recommendations,json=initialRequestRecommendations,proto3" json:"initial_request_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}             `json:"-"`
	XXX_unrecognized              []byte               `json:"-"`
	XXX_sizecache                 int32                `json:"-"`
}

func (m *ContainerRecommendation) Reset()         { *m = ContainerRecommendation{} }
func (m *ContainerRecommendation) String() string { return proto.CompactTextString(m) }
func (*ContainerRecommendation) ProtoMessage()    {}
func (*ContainerRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{0}
}

func (m *ContainerRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRecommendation.Unmarshal(m, b)
}
func (m *ContainerRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRecommendation.Marshal(b, m, deterministic)
}
func (m *ContainerRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRecommendation.Merge(m, src)
}
func (m *ContainerRecommendation) XXX_Size() int {
	return xxx_messageInfo_ContainerRecommendation.Size(m)
}
func (m *ContainerRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRecommendation proto.InternalMessageInfo

func (m *ContainerRecommendation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerRecommendation) GetLimitRecommendations() []*common.MetricData {
	if m != nil {
		return m.LimitRecommendations
	}
	return nil
}

func (m *ContainerRecommendation) GetRequestRecommendations() []*common.MetricData {
	if m != nil {
		return m.RequestRecommendations
	}
	return nil
}

func (m *ContainerRecommendation) GetInitialLimitRecommendations() []*common.MetricData {
	if m != nil {
		return m.InitialLimitRecommendations
	}
	return nil
}

func (m *ContainerRecommendation) GetInitialRequestRecommendations() []*common.MetricData {
	if m != nil {
		return m.InitialRequestRecommendations
	}
	return nil
}

// Represents a set of container resource configuration recommendations of a pod
type PodRecommendation struct {
	ObjectMeta               *resources.ObjectMeta      `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	ApplyRecommendationNow   bool                       `protobuf:"varint,2,opt,name=apply_recommendation_now,json=applyRecommendationNow,proto3" json:"apply_recommendation_now,omitempty"`
	AssignPodPolicy          *resources.AssignPodPolicy `protobuf:"bytes,3,opt,name=assign_pod_policy,json=assignPodPolicy,proto3" json:"assign_pod_policy,omitempty"`
	ContainerRecommendations []*ContainerRecommendation `protobuf:"bytes,4,rep,name=container_recommendations,json=containerRecommendations,proto3" json:"container_recommendations,omitempty"`
	StartTime                *timestamp.Timestamp       `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                  *timestamp.Timestamp       `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TopController            *resources.Controller      `protobuf:"bytes,7,opt,name=top_controller,json=topController,proto3" json:"top_controller,omitempty"`
	RecommendationId         string                     `protobuf:"bytes,8,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	TotalCost                float64                    `protobuf:"fixed64,9,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *PodRecommendation) Reset()         { *m = PodRecommendation{} }
func (m *PodRecommendation) String() string { return proto.CompactTextString(m) }
func (*PodRecommendation) ProtoMessage()    {}
func (*PodRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{1}
}

func (m *PodRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodRecommendation.Unmarshal(m, b)
}
func (m *PodRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodRecommendation.Marshal(b, m, deterministic)
}
func (m *PodRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodRecommendation.Merge(m, src)
}
func (m *PodRecommendation) XXX_Size() int {
	return xxx_messageInfo_PodRecommendation.Size(m)
}
func (m *PodRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_PodRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_PodRecommendation proto.InternalMessageInfo

func (m *PodRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *PodRecommendation) GetApplyRecommendationNow() bool {
	if m != nil {
		return m.ApplyRecommendationNow
	}
	return false
}

func (m *PodRecommendation) GetAssignPodPolicy() *resources.AssignPodPolicy {
	if m != nil {
		return m.AssignPodPolicy
	}
	return nil
}

func (m *PodRecommendation) GetContainerRecommendations() []*ContainerRecommendation {
	if m != nil {
		return m.ContainerRecommendations
	}
	return nil
}

func (m *PodRecommendation) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PodRecommendation) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *PodRecommendation) GetTopController() *resources.Controller {
	if m != nil {
		return m.TopController
	}
	return nil
}

func (m *PodRecommendation) GetRecommendationId() string {
	if m != nil {
		return m.RecommendationId
	}
	return ""
}

func (m *PodRecommendation) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

type ControllerRecommendation struct {
	ObjectMeta           *resources.ObjectMeta         `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind                `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType     `protobuf:"varint,3,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	RecommendedSpec      *ControllerRecommendedSpec    `protobuf:"bytes,4,opt,name=recommended_spec,json=recommendedSpec,proto3" json:"recommended_spec,omitempty"`
	RecommendedSpecK8S   *ControllerRecommendedSpecK8S `protobuf:"bytes,5,opt,name=recommended_spec_k8s,json=recommendedSpecK8s,proto3" json:"recommended_spec_k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ControllerRecommendation) Reset()         { *m = ControllerRecommendation{} }
func (m *ControllerRecommendation) String() string { return proto.CompactTextString(m) }
func (*ControllerRecommendation) ProtoMessage()    {}
func (*ControllerRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{2}
}

func (m *ControllerRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerRecommendation.Unmarshal(m, b)
}
func (m *ControllerRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerRecommendation.Marshal(b, m, deterministic)
}
func (m *ControllerRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerRecommendation.Merge(m, src)
}
func (m *ControllerRecommendation) XXX_Size() int {
	return xxx_messageInfo_ControllerRecommendation.Size(m)
}
func (m *ControllerRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerRecommendation proto.InternalMessageInfo

func (m *ControllerRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ControllerRecommendation) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ControllerRecommendation) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

func (m *ControllerRecommendation) GetRecommendedSpec() *ControllerRecommendedSpec {
	if m != nil {
		return m.RecommendedSpec
	}
	return nil
}

func (m *ControllerRecommendation) GetRecommendedSpecK8S() *ControllerRecommendedSpecK8S {
	if m != nil {
		return m.RecommendedSpecK8S
	}
	return nil
}

type ApplicationRecommendation struct {
	ObjectMeta           *resources.ObjectMeta         `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind                `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType     `protobuf:"varint,3,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	RecommendedSpec      *ControllerRecommendedSpec    `protobuf:"bytes,4,opt,name=recommended_spec,json=recommendedSpec,proto3" json:"recommended_spec,omitempty"`
	RecommendedSpecK8S   *ControllerRecommendedSpecK8S `protobuf:"bytes,5,opt,name=recommended_spec_k8s,json=recommendedSpecK8s,proto3" json:"recommended_spec_k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ApplicationRecommendation) Reset()         { *m = ApplicationRecommendation{} }
func (m *ApplicationRecommendation) String() string { return proto.CompactTextString(m) }
func (*ApplicationRecommendation) ProtoMessage()    {}
func (*ApplicationRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{3}
}

func (m *ApplicationRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationRecommendation.Unmarshal(m, b)
}
func (m *ApplicationRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationRecommendation.Marshal(b, m, deterministic)
}
func (m *ApplicationRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationRecommendation.Merge(m, src)
}
func (m *ApplicationRecommendation) XXX_Size() int {
	return xxx_messageInfo_ApplicationRecommendation.Size(m)
}
func (m *ApplicationRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationRecommendation proto.InternalMessageInfo

func (m *ApplicationRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ApplicationRecommendation) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ApplicationRecommendation) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

func (m *ApplicationRecommendation) GetRecommendedSpec() *ControllerRecommendedSpec {
	if m != nil {
		return m.RecommendedSpec
	}
	return nil
}

func (m *ApplicationRecommendation) GetRecommendedSpecK8S() *ControllerRecommendedSpecK8S {
	if m != nil {
		return m.RecommendedSpecK8S
	}
	return nil
}

type NamespaceRecommendation struct {
	ObjectMeta           *resources.ObjectMeta         `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind                `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType     `protobuf:"varint,3,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	RecommendedSpec      *ControllerRecommendedSpec    `protobuf:"bytes,4,opt,name=recommended_spec,json=recommendedSpec,proto3" json:"recommended_spec,omitempty"`
	RecommendedSpecK8S   *ControllerRecommendedSpecK8S `protobuf:"bytes,5,opt,name=recommended_spec_k8s,json=recommendedSpecK8s,proto3" json:"recommended_spec_k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NamespaceRecommendation) Reset()         { *m = NamespaceRecommendation{} }
func (m *NamespaceRecommendation) String() string { return proto.CompactTextString(m) }
func (*NamespaceRecommendation) ProtoMessage()    {}
func (*NamespaceRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{4}
}

func (m *NamespaceRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceRecommendation.Unmarshal(m, b)
}
func (m *NamespaceRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceRecommendation.Marshal(b, m, deterministic)
}
func (m *NamespaceRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceRecommendation.Merge(m, src)
}
func (m *NamespaceRecommendation) XXX_Size() int {
	return xxx_messageInfo_NamespaceRecommendation.Size(m)
}
func (m *NamespaceRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceRecommendation proto.InternalMessageInfo

func (m *NamespaceRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *NamespaceRecommendation) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *NamespaceRecommendation) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

func (m *NamespaceRecommendation) GetRecommendedSpec() *ControllerRecommendedSpec {
	if m != nil {
		return m.RecommendedSpec
	}
	return nil
}

func (m *NamespaceRecommendation) GetRecommendedSpecK8S() *ControllerRecommendedSpecK8S {
	if m != nil {
		return m.RecommendedSpecK8S
	}
	return nil
}

type NodeRecommendation struct {
	ObjectMeta           *resources.ObjectMeta         `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind                `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType     `protobuf:"varint,3,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	RecommendedSpec      *ControllerRecommendedSpec    `protobuf:"bytes,4,opt,name=recommended_spec,json=recommendedSpec,proto3" json:"recommended_spec,omitempty"`
	RecommendedSpecK8S   *ControllerRecommendedSpecK8S `protobuf:"bytes,5,opt,name=recommended_spec_k8s,json=recommendedSpecK8s,proto3" json:"recommended_spec_k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NodeRecommendation) Reset()         { *m = NodeRecommendation{} }
func (m *NodeRecommendation) String() string { return proto.CompactTextString(m) }
func (*NodeRecommendation) ProtoMessage()    {}
func (*NodeRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{5}
}

func (m *NodeRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRecommendation.Unmarshal(m, b)
}
func (m *NodeRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRecommendation.Marshal(b, m, deterministic)
}
func (m *NodeRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRecommendation.Merge(m, src)
}
func (m *NodeRecommendation) XXX_Size() int {
	return xxx_messageInfo_NodeRecommendation.Size(m)
}
func (m *NodeRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRecommendation proto.InternalMessageInfo

func (m *NodeRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *NodeRecommendation) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *NodeRecommendation) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

func (m *NodeRecommendation) GetRecommendedSpec() *ControllerRecommendedSpec {
	if m != nil {
		return m.RecommendedSpec
	}
	return nil
}

func (m *NodeRecommendation) GetRecommendedSpecK8S() *ControllerRecommendedSpecK8S {
	if m != nil {
		return m.RecommendedSpecK8S
	}
	return nil
}

type ClusterRecommendation struct {
	ObjectMeta           *resources.ObjectMeta         `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind                `protobuf:"varint,2,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType     `protobuf:"varint,3,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	RecommendedSpec      *ControllerRecommendedSpec    `protobuf:"bytes,4,opt,name=recommended_spec,json=recommendedSpec,proto3" json:"recommended_spec,omitempty"`
	RecommendedSpecK8S   *ControllerRecommendedSpecK8S `protobuf:"bytes,5,opt,name=recommended_spec_k8s,json=recommendedSpecK8s,proto3" json:"recommended_spec_k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClusterRecommendation) Reset()         { *m = ClusterRecommendation{} }
func (m *ClusterRecommendation) String() string { return proto.CompactTextString(m) }
func (*ClusterRecommendation) ProtoMessage()    {}
func (*ClusterRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{6}
}

func (m *ClusterRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRecommendation.Unmarshal(m, b)
}
func (m *ClusterRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRecommendation.Marshal(b, m, deterministic)
}
func (m *ClusterRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRecommendation.Merge(m, src)
}
func (m *ClusterRecommendation) XXX_Size() int {
	return xxx_messageInfo_ClusterRecommendation.Size(m)
}
func (m *ClusterRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRecommendation proto.InternalMessageInfo

func (m *ClusterRecommendation) GetObjectMeta() *resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ClusterRecommendation) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ClusterRecommendation) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

func (m *ClusterRecommendation) GetRecommendedSpec() *ControllerRecommendedSpec {
	if m != nil {
		return m.RecommendedSpec
	}
	return nil
}

func (m *ClusterRecommendation) GetRecommendedSpecK8S() *ControllerRecommendedSpecK8S {
	if m != nil {
		return m.RecommendedSpecK8S
	}
	return nil
}

type ReadRecommendation struct {
	SchemaMeta           *schemas.SchemaMeta      `protobuf:"bytes,1,opt,name=schema_meta,json=schemaMeta,proto3" json:"schema_meta,omitempty"`
	Recommendations      []*common.ReadMetricData `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ReadRecommendation) Reset()         { *m = ReadRecommendation{} }
func (m *ReadRecommendation) String() string { return proto.CompactTextString(m) }
func (*ReadRecommendation) ProtoMessage()    {}
func (*ReadRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{7}
}

func (m *ReadRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRecommendation.Unmarshal(m, b)
}
func (m *ReadRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRecommendation.Marshal(b, m, deterministic)
}
func (m *ReadRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRecommendation.Merge(m, src)
}
func (m *ReadRecommendation) XXX_Size() int {
	return xxx_messageInfo_ReadRecommendation.Size(m)
}
func (m *ReadRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRecommendation proto.InternalMessageInfo

func (m *ReadRecommendation) GetSchemaMeta() *schemas.SchemaMeta {
	if m != nil {
		return m.SchemaMeta
	}
	return nil
}

func (m *ReadRecommendation) GetRecommendations() []*common.ReadMetricData {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

type WriteRecommendation struct {
	SchemaMeta           *schemas.SchemaMeta       `protobuf:"bytes,1,opt,name=schema_meta,json=schemaMeta,proto3" json:"schema_meta,omitempty"`
	Recommendations      []*common.WriteMetricData `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *WriteRecommendation) Reset()         { *m = WriteRecommendation{} }
func (m *WriteRecommendation) String() string { return proto.CompactTextString(m) }
func (*WriteRecommendation) ProtoMessage()    {}
func (*WriteRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f52d7b187a1555e, []int{8}
}

func (m *WriteRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecommendation.Unmarshal(m, b)
}
func (m *WriteRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecommendation.Marshal(b, m, deterministic)
}
func (m *WriteRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecommendation.Merge(m, src)
}
func (m *WriteRecommendation) XXX_Size() int {
	return xxx_messageInfo_WriteRecommendation.Size(m)
}
func (m *WriteRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecommendation proto.InternalMessageInfo

func (m *WriteRecommendation) GetSchemaMeta() *schemas.SchemaMeta {
	if m != nil {
		return m.SchemaMeta
	}
	return nil
}

func (m *WriteRecommendation) GetRecommendations() []*common.WriteMetricData {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

func init() {
	proto.RegisterType((*ContainerRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ContainerRecommendation")
	proto.RegisterType((*PodRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.PodRecommendation")
	proto.RegisterType((*ControllerRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendation")
	proto.RegisterType((*ApplicationRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ApplicationRecommendation")
	proto.RegisterType((*NamespaceRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.NamespaceRecommendation")
	proto.RegisterType((*NodeRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.NodeRecommendation")
	proto.RegisterType((*ClusterRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ClusterRecommendation")
	proto.RegisterType((*ReadRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ReadRecommendation")
	proto.RegisterType((*WriteRecommendation)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.WriteRecommendation")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/recommendations/recommendations.proto", fileDescriptor_7f52d7b187a1555e)
}

var fileDescriptor_7f52d7b187a1555e = []byte{
	// 835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x4f, 0xeb, 0x46,
	0x14, 0x95, 0x1f, 0xe6, 0x3d, 0x72, 0xa3, 0x42, 0x99, 0x3e, 0xc0, 0x50, 0x21, 0xa2, 0xac, 0x22,
	0x55, 0xb5, 0x4b, 0xaa, 0x54, 0x41, 0x6d, 0xa5, 0x42, 0xba, 0x41, 0x94, 0x34, 0x32, 0x48, 0x95,
	0x50, 0x25, 0x6b, 0x62, 0x0f, 0x61, 0x8a, 0xed, 0x19, 0x3c, 0x93, 0xa2, 0xa8, 0x5d, 0x74, 0xd3,
	0x55, 0x37, 0xfd, 0x47, 0x95, 0xaa, 0xb6, 0x52, 0xff, 0x41, 0xd5, 0x5f, 0xf3, 0xe4, 0x89, 0x1d,
	0xb0, 0x49, 0x20, 0x1f, 0x88, 0x95, 0x57, 0x99, 0xb9, 0xf6, 0x3d, 0xe7, 0xdc, 0x99, 0x73, 0xad,
	0xcc, 0xc0, 0x11, 0xf6, 0x71, 0x40, 0x3c, 0xec, 0x60, 0x4e, 0xad, 0x1f, 0xf7, 0xb1, 0xcf, 0xaf,
	0xf0, 0xbe, 0xe5, 0x61, 0x89, 0xaf, 0xfa, 0x5d, 0x2b, 0x22, 0x2e, 0x0b, 0x02, 0x12, 0x7a, 0x58,
	0x52, 0x16, 0x8a, 0xfc, 0xdc, 0xe4, 0x11, 0x93, 0x0c, 0x35, 0x5c, 0x16, 0x4a, 0x4c, 0x43, 0x12,
	0x09, 0x4c, 0xcd, 0x04, 0xd0, 0x4c, 0xc1, 0xcc, 0x04, 0xcc, 0xcc, 0x25, 0xef, 0xec, 0x3f, 0x4a,
	0x1d, 0xbf, 0xcb, 0x42, 0x2b, 0x20, 0x32, 0xa2, 0x6e, 0xc2, 0xb4, 0xd3, 0x78, 0x42, 0xad, 0x60,
	0xfd, 0xc8, 0x25, 0x22, 0xce, 0xc2, 0x71, 0x74, 0xc6, 0x34, 0xce, 0x7c, 0xea, 0x52, 0x92, 0xb2,
	0x7d, 0x36, 0x65, 0xda, 0x68, 0x94, 0xe4, 0x35, 0x67, 0x5a, 0x53, 0x39, 0xe0, 0xa3, 0xcc, 0x4f,
	0x1e, 0xcd, 0x14, 0xee, 0x15, 0x09, 0x70, 0x36, 0x63, 0xaf, 0xc7, 0x58, 0xcf, 0x27, 0x96, 0x9a,
	0x75, 0xfb, 0x97, 0x96, 0xa4, 0x01, 0x11, 0x12, 0x07, 0x7c, 0xf8, 0x42, 0xf5, 0x77, 0x1d, 0xb6,
	0x5a, 0xe9, 0xfe, 0xd8, 0x19, 0x6e, 0x84, 0x40, 0x0f, 0x71, 0x40, 0x0c, 0xad, 0xa2, 0xd5, 0x4a,
	0xb6, 0x1a, 0xa3, 0x00, 0x36, 0x7c, 0x1a, 0x50, 0xe9, 0xe4, 0x74, 0x1a, 0xaf, 0x2a, 0x4b, 0xb5,
	0x72, 0xbd, 0x69, 0x4e, 0xb7, 0xd9, 0xc3, 0xed, 0x33, 0x4f, 0xd5, 0xf6, 0x7d, 0x8d, 0x25, 0xb6,
	0xdf, 0x2a, 0xd8, 0xac, 0x02, 0x81, 0x6e, 0x60, 0x2b, 0x22, 0x37, 0x7d, 0x22, 0x1e, 0x12, 0x2e,
	0x2d, 0x48, 0xb8, 0x99, 0x00, 0xe7, 0x29, 0x7f, 0x86, 0x5d, 0x1a, 0x52, 0x49, 0xb1, 0xef, 0x8c,
	0xaf, 0x54, 0x5f, 0x90, 0xf8, 0xc3, 0x04, 0xfe, 0x9b, 0x71, 0x05, 0xff, 0xa2, 0xc1, 0x5e, 0x4a,
	0x3f, 0xa9, 0xf2, 0xe5, 0x05, 0x05, 0xa4, 0xf5, 0xd9, 0x63, 0x17, 0xa0, 0xfa, 0xef, 0x32, 0xac,
	0x77, 0x98, 0x97, 0x33, 0xc3, 0xf7, 0x50, 0x66, 0xdd, 0x1f, 0x88, 0x2b, 0x9d, 0xb8, 0x7b, 0x94,
	0x27, 0xca, 0xf5, 0xcf, 0xcd, 0x69, 0x7b, 0x3b, 0x6d, 0x81, 0x6f, 0x15, 0xc6, 0x29, 0x91, 0xd8,
	0x06, 0x36, 0x1a, 0xa3, 0x26, 0x18, 0x98, 0x73, 0x7f, 0x90, 0xab, 0xd5, 0x09, 0xd9, 0xad, 0xf1,
	0xaa, 0xa2, 0xd5, 0x56, 0xec, 0x4d, 0xf5, 0x3c, 0x2b, 0xaa, 0xcd, 0x6e, 0x91, 0x0f, 0xeb, 0x58,
	0x08, 0xda, 0x0b, 0x1d, 0xce, 0x3c, 0x47, 0xb5, 0xe8, 0xc0, 0x58, 0x52, 0xea, 0xbe, 0x9a, 0x59,
	0xdd, 0xa1, 0x42, 0xea, 0x30, 0xaf, 0xa3, 0x70, 0xec, 0x35, 0x9c, 0x0d, 0xa0, 0xdf, 0x34, 0xd8,
	0x1e, 0x81, 0x4e, 0x70, 0x46, 0xdb, 0x9c, 0xeb, 0x83, 0x67, 0x4e, 0x68, 0x43, 0xdb, 0x70, 0xc7,
	0x3f, 0x10, 0xe8, 0x00, 0x40, 0x48, 0x1c, 0x49, 0x27, 0xee, 0x6a, 0x63, 0x59, 0x15, 0xbd, 0x63,
	0x0e, 0x5b, 0xde, 0x4c, 0x5b, 0xde, 0x3c, 0x4f, 0x5b, 0xde, 0x2e, 0xa9, 0xb7, 0xe3, 0x39, 0x6a,
	0xc0, 0x0a, 0x09, 0xbd, 0x61, 0xe2, 0xeb, 0x27, 0x13, 0xdf, 0x90, 0xd0, 0x53, 0x69, 0x5d, 0x58,
	0x95, 0x8c, 0x3b, 0xb1, 0xa2, 0x88, 0xf9, 0x3e, 0x89, 0x8c, 0x37, 0x73, 0x1a, 0xa1, 0x35, 0x82,
	0xb0, 0xdf, 0x93, 0x8c, 0xdf, 0x4d, 0xd1, 0x47, 0xb0, 0x9e, 0x73, 0x01, 0xf5, 0x8c, 0x15, 0xf5,
	0x0d, 0x7a, 0x3f, 0xfb, 0xe0, 0xd8, 0x43, 0xbb, 0x00, 0x92, 0x49, 0xec, 0x3b, 0x2e, 0x13, 0xd2,
	0x28, 0x55, 0xb4, 0x9a, 0x66, 0x97, 0x54, 0xa4, 0xc5, 0x84, 0xac, 0xfe, 0xad, 0x83, 0x71, 0x8f,
	0xe9, 0x25, 0x2d, 0x7d, 0x0c, 0xfa, 0x35, 0x0d, 0x3d, 0x65, 0xdf, 0xd5, 0x7a, 0x63, 0x66, 0xd8,
	0x13, 0x1a, 0x7a, 0xb6, 0x82, 0x40, 0x3f, 0xc1, 0x5d, 0xe1, 0xc4, 0x73, 0xe2, 0x0f, 0xbc, 0xb2,
	0xf8, 0x6a, 0xbd, 0xb3, 0x80, 0xd7, 0x72, 0x6b, 0x42, 0xbc, 0xf3, 0x01, 0x27, 0xf6, 0x5a, 0x94,
	0x0d, 0xe4, 0xc9, 0x05, 0x27, 0xae, 0xa1, 0xab, 0xa5, 0x7a, 0x56, 0xf2, 0x33, 0x4e, 0xdc, 0x0c,
	0x79, 0x1c, 0x40, 0xbf, 0x6a, 0xf0, 0x36, 0xcf, 0xee, 0x5c, 0x37, 0x45, 0x62, 0xf6, 0xb3, 0xe7,
	0x56, 0x70, 0xd2, 0x14, 0x36, 0x8a, 0x1e, 0xc4, 0xaa, 0xff, 0xe8, 0xb0, 0x7d, 0xc8, 0xb9, 0x4f,
	0xdd, 0x61, 0x4f, 0x16, 0x46, 0x2a, 0x8c, 0x34, 0x97, 0x91, 0xfe, 0xd2, 0x61, 0xab, 0x8d, 0x03,
	0x22, 0x38, 0x76, 0x49, 0x61, 0xa3, 0xc2, 0x46, 0xf3, 0xd9, 0xe8, 0x0f, 0x1d, 0x50, 0x9b, 0x79,
	0x85, 0x83, 0x0a, 0x07, 0xcd, 0xe9, 0xa0, 0x3f, 0x75, 0xd8, 0x68, 0xf9, 0x7d, 0x21, 0x8b, 0xbf,
	0x45, 0x85, 0x89, 0xe6, 0x35, 0xd1, 0x7f, 0x1a, 0x20, 0x9b, 0xe0, 0xfc, 0x59, 0xf1, 0x02, 0xca,
	0xc3, 0xcb, 0x88, 0xfb, 0x0e, 0x3a, 0x98, 0x52, 0x54, 0x72, 0x8d, 0x61, 0x9e, 0xa9, 0xdf, 0xa1,
	0x7f, 0xc4, 0x68, 0x8c, 0x2e, 0x61, 0x6d, 0xfc, 0xd5, 0xc3, 0x17, 0xb3, 0x9d, 0x87, 0x63, 0xd9,
	0xf7, 0xce, 0xc4, 0x79, 0xd0, 0xea, 0xff, 0x1a, 0x7c, 0xf0, 0x5d, 0x44, 0x25, 0x79, 0xc1, 0xda,
	0x7a, 0x93, 0x6a, 0xfb, 0x72, 0xb6, 0xda, 0x94, 0xee, 0x47, 0x8a, 0x3b, 0x3a, 0xb9, 0x38, 0xee,
	0x51, 0x99, 0x64, 0x58, 0x77, 0xd8, 0x1f, 0x63, 0x6a, 0x61, 0x4e, 0xad, 0x59, 0x6e, 0xa8, 0xba,
	0xaf, 0xd5, 0x81, 0xf1, 0xd3, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x5e, 0x8e, 0x34, 0x2c,
	0x14, 0x00, 0x00,
}
