// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alameda_api/v1alpha1/datahub/recommendations/services.proto

package recommendations

import (
	fmt "fmt"
	common "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/common"
	resources "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/resources"
	schemas "github.com/containers-ai/api/alameda_api/v1alpha1/datahub/schemas"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRecommendationsRequest struct {
	Recommendations      []*WriteRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateRecommendationsRequest) Reset()         { *m = CreateRecommendationsRequest{} }
func (m *CreateRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecommendationsRequest) ProtoMessage()    {}
func (*CreateRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{0}
}

func (m *CreateRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecommendationsRequest.Merge(m, src)
}
func (m *CreateRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecommendationsRequest.Size(m)
}
func (m *CreateRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecommendationsRequest proto.InternalMessageInfo

func (m *CreateRecommendationsRequest) GetRecommendations() []*WriteRecommendation {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

// Represents a request for creating a pod's recommendation
type CreatePodRecommendationsRequest struct {
	PodRecommendations   []*PodRecommendation `protobuf:"bytes,1,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	Granularity          int64                `protobuf:"varint,2,opt,name=granularity,proto3" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatePodRecommendationsRequest) Reset()         { *m = CreatePodRecommendationsRequest{} }
func (m *CreatePodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodRecommendationsRequest) ProtoMessage()    {}
func (*CreatePodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{1}
}

func (m *CreatePodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreatePodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreatePodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodRecommendationsRequest.Merge(m, src)
}
func (m *CreatePodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodRecommendationsRequest.Size(m)
}
func (m *CreatePodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodRecommendationsRequest proto.InternalMessageInfo

func (m *CreatePodRecommendationsRequest) GetPodRecommendations() []*PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

func (m *CreatePodRecommendationsRequest) GetGranularity() int64 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

// Represents a request for creating a controller's recommendation
type CreateControllerRecommendationsRequest struct {
	ControllerRecommendations []*ControllerRecommendation `protobuf:"bytes,1,rep,name=controller_recommendations,json=controllerRecommendations,proto3" json:"controller_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                    `json:"-"`
	XXX_unrecognized          []byte                      `json:"-"`
	XXX_sizecache             int32                       `json:"-"`
}

func (m *CreateControllerRecommendationsRequest) Reset() {
	*m = CreateControllerRecommendationsRequest{}
}
func (m *CreateControllerRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateControllerRecommendationsRequest) ProtoMessage()    {}
func (*CreateControllerRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{2}
}

func (m *CreateControllerRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateControllerRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateControllerRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateControllerRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateControllerRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateControllerRecommendationsRequest.Merge(m, src)
}
func (m *CreateControllerRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateControllerRecommendationsRequest.Size(m)
}
func (m *CreateControllerRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateControllerRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateControllerRecommendationsRequest proto.InternalMessageInfo

func (m *CreateControllerRecommendationsRequest) GetControllerRecommendations() []*ControllerRecommendation {
	if m != nil {
		return m.ControllerRecommendations
	}
	return nil
}

type CreateApplicationRecommendationsRequest struct {
	ApplicationRecommendations []*ApplicationRecommendation `protobuf:"bytes,1,rep,name=application_recommendations,json=applicationRecommendations,proto3" json:"application_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *CreateApplicationRecommendationsRequest) Reset() {
	*m = CreateApplicationRecommendationsRequest{}
}
func (m *CreateApplicationRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationRecommendationsRequest) ProtoMessage()    {}
func (*CreateApplicationRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{3}
}

func (m *CreateApplicationRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateApplicationRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationRecommendationsRequest.Merge(m, src)
}
func (m *CreateApplicationRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationRecommendationsRequest.Size(m)
}
func (m *CreateApplicationRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationRecommendationsRequest proto.InternalMessageInfo

func (m *CreateApplicationRecommendationsRequest) GetApplicationRecommendations() []*ApplicationRecommendation {
	if m != nil {
		return m.ApplicationRecommendations
	}
	return nil
}

type CreateNamespaceRecommendationsRequest struct {
	NamespaceRecommendations []*NamespaceRecommendation `protobuf:"bytes,1,rep,name=namespace_recommendations,json=namespaceRecommendations,proto3" json:"namespace_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *CreateNamespaceRecommendationsRequest) Reset()         { *m = CreateNamespaceRecommendationsRequest{} }
func (m *CreateNamespaceRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRecommendationsRequest) ProtoMessage()    {}
func (*CreateNamespaceRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{4}
}

func (m *CreateNamespaceRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRecommendationsRequest.Merge(m, src)
}
func (m *CreateNamespaceRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRecommendationsRequest.Size(m)
}
func (m *CreateNamespaceRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRecommendationsRequest proto.InternalMessageInfo

func (m *CreateNamespaceRecommendationsRequest) GetNamespaceRecommendations() []*NamespaceRecommendation {
	if m != nil {
		return m.NamespaceRecommendations
	}
	return nil
}

type CreateNodeRecommendationsRequest struct {
	NodeRecommendations  []*NodeRecommendation `protobuf:"bytes,1,rep,name=node_recommendations,json=nodeRecommendations,proto3" json:"node_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateNodeRecommendationsRequest) Reset()         { *m = CreateNodeRecommendationsRequest{} }
func (m *CreateNodeRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNodeRecommendationsRequest) ProtoMessage()    {}
func (*CreateNodeRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{5}
}

func (m *CreateNodeRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodeRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateNodeRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodeRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateNodeRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodeRecommendationsRequest.Merge(m, src)
}
func (m *CreateNodeRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNodeRecommendationsRequest.Size(m)
}
func (m *CreateNodeRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodeRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodeRecommendationsRequest proto.InternalMessageInfo

func (m *CreateNodeRecommendationsRequest) GetNodeRecommendations() []*NodeRecommendation {
	if m != nil {
		return m.NodeRecommendations
	}
	return nil
}

type CreateClusterRecommendationsRequest struct {
	ClusterRecommendations []*ClusterRecommendation `protobuf:"bytes,1,rep,name=cluster_recommendations,json=clusterRecommendations,proto3" json:"cluster_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *CreateClusterRecommendationsRequest) Reset()         { *m = CreateClusterRecommendationsRequest{} }
func (m *CreateClusterRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClusterRecommendationsRequest) ProtoMessage()    {}
func (*CreateClusterRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{6}
}

func (m *CreateClusterRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClusterRecommendationsRequest.Unmarshal(m, b)
}
func (m *CreateClusterRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClusterRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *CreateClusterRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClusterRecommendationsRequest.Merge(m, src)
}
func (m *CreateClusterRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClusterRecommendationsRequest.Size(m)
}
func (m *CreateClusterRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClusterRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClusterRecommendationsRequest proto.InternalMessageInfo

func (m *CreateClusterRecommendationsRequest) GetClusterRecommendations() []*ClusterRecommendation {
	if m != nil {
		return m.ClusterRecommendations
	}
	return nil
}

// Represents a request for listing recommendations of pods
type ListPodRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition  `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind          `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	Granularity          int64                   `protobuf:"varint,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListPodRecommendationsRequest) Reset()         { *m = ListPodRecommendationsRequest{} }
func (m *ListPodRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsRequest) ProtoMessage()    {}
func (*ListPodRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{7}
}

func (m *ListPodRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListPodRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListPodRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsRequest.Merge(m, src)
}
func (m *ListPodRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsRequest.Size(m)
}
func (m *ListPodRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsRequest proto.InternalMessageInfo

func (m *ListPodRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListPodRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListPodRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListPodRecommendationsRequest) GetGranularity() int64 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

// Represents a response for listing pod recommendations request
type ListPodRecommendationsResponse struct {
	Status               *status.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PodRecommendations   []*PodRecommendation `protobuf:"bytes,2,rep,name=pod_recommendations,json=podRecommendations,proto3" json:"pod_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListPodRecommendationsResponse) Reset()         { *m = ListPodRecommendationsResponse{} }
func (m *ListPodRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodRecommendationsResponse) ProtoMessage()    {}
func (*ListPodRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{8}
}

func (m *ListPodRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListPodRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListPodRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodRecommendationsResponse.Merge(m, src)
}
func (m *ListPodRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPodRecommendationsResponse.Size(m)
}
func (m *ListPodRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodRecommendationsResponse proto.InternalMessageInfo

func (m *ListPodRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPodRecommendationsResponse) GetPodRecommendations() []*PodRecommendation {
	if m != nil {
		return m.PodRecommendations
	}
	return nil
}

// Represents a request for listing recommendations of controllers
type ListControllerRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition    `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta   `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind            `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType `protobuf:"varint,4,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListControllerRecommendationsRequest) Reset()         { *m = ListControllerRecommendationsRequest{} }
func (m *ListControllerRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListControllerRecommendationsRequest) ProtoMessage()    {}
func (*ListControllerRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{9}
}

func (m *ListControllerRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListControllerRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListControllerRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListControllerRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListControllerRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListControllerRecommendationsRequest.Merge(m, src)
}
func (m *ListControllerRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListControllerRecommendationsRequest.Size(m)
}
func (m *ListControllerRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListControllerRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListControllerRecommendationsRequest proto.InternalMessageInfo

func (m *ListControllerRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListControllerRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListControllerRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListControllerRecommendationsRequest) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

// Represents a response for listing controller recommendations request
type ListControllerRecommendationsResponse struct {
	Status                    *status.Status              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ControllerRecommendations []*ControllerRecommendation `protobuf:"bytes,2,rep,name=controller_recommendations,json=controllerRecommendations,proto3" json:"controller_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                    `json:"-"`
	XXX_unrecognized          []byte                      `json:"-"`
	XXX_sizecache             int32                       `json:"-"`
}

func (m *ListControllerRecommendationsResponse) Reset()         { *m = ListControllerRecommendationsResponse{} }
func (m *ListControllerRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListControllerRecommendationsResponse) ProtoMessage()    {}
func (*ListControllerRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{10}
}

func (m *ListControllerRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListControllerRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListControllerRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListControllerRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListControllerRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListControllerRecommendationsResponse.Merge(m, src)
}
func (m *ListControllerRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListControllerRecommendationsResponse.Size(m)
}
func (m *ListControllerRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListControllerRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListControllerRecommendationsResponse proto.InternalMessageInfo

func (m *ListControllerRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListControllerRecommendationsResponse) GetControllerRecommendations() []*ControllerRecommendation {
	if m != nil {
		return m.ControllerRecommendations
	}
	return nil
}

type ListApplicationRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition    `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta   `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind            `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType `protobuf:"varint,4,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListApplicationRecommendationsRequest) Reset()         { *m = ListApplicationRecommendationsRequest{} }
func (m *ListApplicationRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationRecommendationsRequest) ProtoMessage()    {}
func (*ListApplicationRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{11}
}

func (m *ListApplicationRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListApplicationRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationRecommendationsRequest.Merge(m, src)
}
func (m *ListApplicationRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationRecommendationsRequest.Size(m)
}
func (m *ListApplicationRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationRecommendationsRequest proto.InternalMessageInfo

func (m *ListApplicationRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListApplicationRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListApplicationRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListApplicationRecommendationsRequest) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

type ListApplicationRecommendationsResponse struct {
	Status                     *status.Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ApplicationRecommendations []*ApplicationRecommendation `protobuf:"bytes,2,rep,name=application_recommendations,json=applicationRecommendations,proto3" json:"application_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *ListApplicationRecommendationsResponse) Reset() {
	*m = ListApplicationRecommendationsResponse{}
}
func (m *ListApplicationRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationRecommendationsResponse) ProtoMessage()    {}
func (*ListApplicationRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{12}
}

func (m *ListApplicationRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListApplicationRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationRecommendationsResponse.Merge(m, src)
}
func (m *ListApplicationRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationRecommendationsResponse.Size(m)
}
func (m *ListApplicationRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationRecommendationsResponse proto.InternalMessageInfo

func (m *ListApplicationRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListApplicationRecommendationsResponse) GetApplicationRecommendations() []*ApplicationRecommendation {
	if m != nil {
		return m.ApplicationRecommendations
	}
	return nil
}

type ListNamespaceRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition    `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta   `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind            `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType `protobuf:"varint,4,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListNamespaceRecommendationsRequest) Reset()         { *m = ListNamespaceRecommendationsRequest{} }
func (m *ListNamespaceRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceRecommendationsRequest) ProtoMessage()    {}
func (*ListNamespaceRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{13}
}

func (m *ListNamespaceRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListNamespaceRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListNamespaceRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceRecommendationsRequest.Merge(m, src)
}
func (m *ListNamespaceRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceRecommendationsRequest.Size(m)
}
func (m *ListNamespaceRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceRecommendationsRequest proto.InternalMessageInfo

func (m *ListNamespaceRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListNamespaceRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListNamespaceRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListNamespaceRecommendationsRequest) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

type ListNamespaceRecommendationsResponse struct {
	Status                   *status.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NamespaceRecommendations []*NamespaceRecommendation `protobuf:"bytes,2,rep,name=namespace_recommendations,json=namespaceRecommendations,proto3" json:"namespace_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *ListNamespaceRecommendationsResponse) Reset()         { *m = ListNamespaceRecommendationsResponse{} }
func (m *ListNamespaceRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceRecommendationsResponse) ProtoMessage()    {}
func (*ListNamespaceRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{14}
}

func (m *ListNamespaceRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListNamespaceRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListNamespaceRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceRecommendationsResponse.Merge(m, src)
}
func (m *ListNamespaceRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceRecommendationsResponse.Size(m)
}
func (m *ListNamespaceRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceRecommendationsResponse proto.InternalMessageInfo

func (m *ListNamespaceRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNamespaceRecommendationsResponse) GetNamespaceRecommendations() []*NamespaceRecommendation {
	if m != nil {
		return m.NamespaceRecommendations
	}
	return nil
}

type ListNodeRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition    `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta   `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind            `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType `protobuf:"varint,4,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListNodeRecommendationsRequest) Reset()         { *m = ListNodeRecommendationsRequest{} }
func (m *ListNodeRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodeRecommendationsRequest) ProtoMessage()    {}
func (*ListNodeRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{15}
}

func (m *ListNodeRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListNodeRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListNodeRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeRecommendationsRequest.Merge(m, src)
}
func (m *ListNodeRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodeRecommendationsRequest.Size(m)
}
func (m *ListNodeRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeRecommendationsRequest proto.InternalMessageInfo

func (m *ListNodeRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListNodeRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListNodeRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListNodeRecommendationsRequest) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

type ListNodeRecommendationsResponse struct {
	Status               *status.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeRecommendations  []*NodeRecommendation `protobuf:"bytes,2,rep,name=node_recommendations,json=nodeRecommendations,proto3" json:"node_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListNodeRecommendationsResponse) Reset()         { *m = ListNodeRecommendationsResponse{} }
func (m *ListNodeRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodeRecommendationsResponse) ProtoMessage()    {}
func (*ListNodeRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{16}
}

func (m *ListNodeRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListNodeRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListNodeRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeRecommendationsResponse.Merge(m, src)
}
func (m *ListNodeRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodeRecommendationsResponse.Size(m)
}
func (m *ListNodeRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeRecommendationsResponse proto.InternalMessageInfo

func (m *ListNodeRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodeRecommendationsResponse) GetNodeRecommendations() []*NodeRecommendation {
	if m != nil {
		return m.NodeRecommendations
	}
	return nil
}

type ListClusterRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition    `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	ObjectMeta           []*resources.ObjectMeta   `protobuf:"bytes,2,rep,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	Kind                 resources.Kind            `protobuf:"varint,3,opt,name=kind,proto3,enum=containersai.alameda.v1alpha1.datahub.resources.Kind" json:"kind,omitempty"`
	RecommendedType      ControllerRecommendedType `protobuf:"varint,4,opt,name=recommended_type,json=recommendedType,proto3,enum=containersai.alameda.v1alpha1.datahub.recommendations.ControllerRecommendedType" json:"recommended_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListClusterRecommendationsRequest) Reset()         { *m = ListClusterRecommendationsRequest{} }
func (m *ListClusterRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListClusterRecommendationsRequest) ProtoMessage()    {}
func (*ListClusterRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{17}
}

func (m *ListClusterRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClusterRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListClusterRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClusterRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListClusterRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClusterRecommendationsRequest.Merge(m, src)
}
func (m *ListClusterRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListClusterRecommendationsRequest.Size(m)
}
func (m *ListClusterRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClusterRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClusterRecommendationsRequest proto.InternalMessageInfo

func (m *ListClusterRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListClusterRecommendationsRequest) GetObjectMeta() []*resources.ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *ListClusterRecommendationsRequest) GetKind() resources.Kind {
	if m != nil {
		return m.Kind
	}
	return resources.Kind_KIND_UNDEFINED
}

func (m *ListClusterRecommendationsRequest) GetRecommendedType() ControllerRecommendedType {
	if m != nil {
		return m.RecommendedType
	}
	return ControllerRecommendedType_CRT_UNDEFINED
}

type ListClusterRecommendationsResponse struct {
	Status                 *status.Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClusterRecommendations []*ClusterRecommendation `protobuf:"bytes,2,rep,name=cluster_recommendations,json=clusterRecommendations,proto3" json:"cluster_recommendations,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *ListClusterRecommendationsResponse) Reset()         { *m = ListClusterRecommendationsResponse{} }
func (m *ListClusterRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListClusterRecommendationsResponse) ProtoMessage()    {}
func (*ListClusterRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{18}
}

func (m *ListClusterRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClusterRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListClusterRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClusterRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListClusterRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClusterRecommendationsResponse.Merge(m, src)
}
func (m *ListClusterRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListClusterRecommendationsResponse.Size(m)
}
func (m *ListClusterRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClusterRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClusterRecommendationsResponse proto.InternalMessageInfo

func (m *ListClusterRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListClusterRecommendationsResponse) GetClusterRecommendations() []*ClusterRecommendation {
	if m != nil {
		return m.ClusterRecommendations
	}
	return nil
}

type ListRecommendationsRequest struct {
	QueryCondition       *common.QueryCondition `protobuf:"bytes,1,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition,omitempty"`
	SchemaMeta           *schemas.SchemaMeta    `protobuf:"bytes,2,opt,name=schema_meta,json=schemaMeta,proto3" json:"schema_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListRecommendationsRequest) Reset()         { *m = ListRecommendationsRequest{} }
func (m *ListRecommendationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecommendationsRequest) ProtoMessage()    {}
func (*ListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{19}
}

func (m *ListRecommendationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecommendationsRequest.Unmarshal(m, b)
}
func (m *ListRecommendationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecommendationsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecommendationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecommendationsRequest.Merge(m, src)
}
func (m *ListRecommendationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecommendationsRequest.Size(m)
}
func (m *ListRecommendationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecommendationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecommendationsRequest proto.InternalMessageInfo

func (m *ListRecommendationsRequest) GetQueryCondition() *common.QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return nil
}

func (m *ListRecommendationsRequest) GetSchemaMeta() *schemas.SchemaMeta {
	if m != nil {
		return m.SchemaMeta
	}
	return nil
}

type ListRecommendationsResponse struct {
	Status               *status.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Recommendations      []*ReadRecommendation `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRecommendationsResponse) Reset()         { *m = ListRecommendationsResponse{} }
func (m *ListRecommendationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecommendationsResponse) ProtoMessage()    {}
func (*ListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_603987ba119fba8b, []int{20}
}

func (m *ListRecommendationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecommendationsResponse.Unmarshal(m, b)
}
func (m *ListRecommendationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecommendationsResponse.Marshal(b, m, deterministic)
}
func (m *ListRecommendationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecommendationsResponse.Merge(m, src)
}
func (m *ListRecommendationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecommendationsResponse.Size(m)
}
func (m *ListRecommendationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecommendationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecommendationsResponse proto.InternalMessageInfo

func (m *ListRecommendationsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListRecommendationsResponse) GetRecommendations() []*ReadRecommendation {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateRecommendationsRequest")
	proto.RegisterType((*CreatePodRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreatePodRecommendationsRequest")
	proto.RegisterType((*CreateControllerRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateControllerRecommendationsRequest")
	proto.RegisterType((*CreateApplicationRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateApplicationRecommendationsRequest")
	proto.RegisterType((*CreateNamespaceRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateNamespaceRecommendationsRequest")
	proto.RegisterType((*CreateNodeRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateNodeRecommendationsRequest")
	proto.RegisterType((*CreateClusterRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.CreateClusterRecommendationsRequest")
	proto.RegisterType((*ListPodRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListPodRecommendationsRequest")
	proto.RegisterType((*ListPodRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListPodRecommendationsResponse")
	proto.RegisterType((*ListControllerRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListControllerRecommendationsRequest")
	proto.RegisterType((*ListControllerRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListControllerRecommendationsResponse")
	proto.RegisterType((*ListApplicationRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListApplicationRecommendationsRequest")
	proto.RegisterType((*ListApplicationRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListApplicationRecommendationsResponse")
	proto.RegisterType((*ListNamespaceRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListNamespaceRecommendationsRequest")
	proto.RegisterType((*ListNamespaceRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListNamespaceRecommendationsResponse")
	proto.RegisterType((*ListNodeRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListNodeRecommendationsRequest")
	proto.RegisterType((*ListNodeRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListNodeRecommendationsResponse")
	proto.RegisterType((*ListClusterRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListClusterRecommendationsRequest")
	proto.RegisterType((*ListClusterRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListClusterRecommendationsResponse")
	proto.RegisterType((*ListRecommendationsRequest)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListRecommendationsRequest")
	proto.RegisterType((*ListRecommendationsResponse)(nil), "containersai.alameda.v1alpha1.datahub.recommendations.ListRecommendationsResponse")
}

func init() {
	proto.RegisterFile("alameda_api/v1alpha1/datahub/recommendations/services.proto", fileDescriptor_603987ba119fba8b)
}

var fileDescriptor_603987ba119fba8b = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4f, 0x6b, 0xdb, 0x48,
	0x14, 0x67, 0xa4, 0x90, 0xc3, 0x33, 0x24, 0x8b, 0xb2, 0x6c, 0x1c, 0x67, 0x77, 0xe3, 0x55, 0x36,
	0x59, 0xb3, 0xb0, 0xd2, 0x26, 0x4b, 0x60, 0x97, 0xec, 0xa5, 0xc9, 0xa5, 0x69, 0xd2, 0x24, 0x55,
	0x0a, 0x85, 0x50, 0x30, 0x13, 0x69, 0x70, 0xa6, 0x95, 0x35, 0x8a, 0x66, 0x1c, 0x30, 0xed, 0xb5,
	0xa7, 0x42, 0xa1, 0xd0, 0x0f, 0xd0, 0x2f, 0x10, 0x28, 0xfd, 0x73, 0xe8, 0xa1, 0xb9, 0xf6, 0xd0,
	0x53, 0x6f, 0xbd, 0xb5, 0x87, 0x1e, 0xfa, 0x31, 0x8a, 0xfe, 0xd8, 0x89, 0xff, 0x8c, 0x15, 0xab,
	0xd4, 0xf1, 0xc1, 0x27, 0x5b, 0xd2, 0xcc, 0xfb, 0xfd, 0xde, 0xbc, 0x1f, 0xef, 0xbd, 0x79, 0xb0,
	0x8a, 0x5d, 0x5c, 0x25, 0x0e, 0x2e, 0x63, 0x9f, 0x9a, 0xc7, 0x4b, 0xd8, 0xf5, 0x0f, 0xf1, 0x92,
	0xe9, 0x60, 0x81, 0x0f, 0x6b, 0x07, 0x66, 0x40, 0x6c, 0x56, 0xad, 0x12, 0xcf, 0xc1, 0x82, 0x32,
	0x8f, 0x9b, 0x9c, 0x04, 0xc7, 0xd4, 0x26, 0xdc, 0xf0, 0x03, 0x26, 0x98, 0xb6, 0x62, 0x33, 0x4f,
	0x60, 0xea, 0x91, 0x80, 0x63, 0x6a, 0x24, 0x96, 0x8c, 0x86, 0x15, 0x23, 0xb1, 0x62, 0xb4, 0x59,
	0x29, 0x2c, 0xf5, 0xc4, 0x0c, 0xd7, 0x32, 0xcf, 0x3c, 0xaa, 0x91, 0x80, 0x36, 0x90, 0x0a, 0x6b,
	0x7d, 0xd1, 0x6c, 0x7b, 0x4e, 0x6c, 0xfc, 0xdb, 0x97, 0x0d, 0x51, 0xf7, 0x9b, 0xe8, 0x2b, 0x29,
	0x3b, 0x39, 0xab, 0x05, 0x36, 0xe1, 0x66, 0x95, 0x08, 0x1c, 0xbe, 0x4d, 0xb6, 0xfd, 0xdd, 0x73,
	0x1b, 0xb7, 0x0f, 0x49, 0x15, 0xb7, 0x02, 0x4d, 0x57, 0x18, 0xab, 0xb8, 0xc4, 0x0c, 0x7c, 0xdb,
	0xe4, 0x02, 0x8b, 0x5a, 0xf2, 0x41, 0x7f, 0x82, 0xe0, 0xe7, 0xf5, 0x80, 0x60, 0x41, 0xac, 0x56,
	0x9e, 0x16, 0x39, 0xaa, 0x11, 0x2e, 0x34, 0x01, 0x93, 0x6d, 0x1e, 0xe4, 0x51, 0x51, 0x2d, 0xe5,
	0x96, 0xaf, 0x19, 0x99, 0x82, 0x64, 0xdc, 0x0a, 0x68, 0x3b, 0x98, 0xd5, 0x0e, 0xa1, 0x9f, 0x22,
	0x98, 0x8b, 0x69, 0xed, 0x32, 0x47, 0xc2, 0xac, 0x0e, 0x53, 0x3e, 0x73, 0xca, 0xdd, 0xd9, 0x5d,
	0xcd, 0xc8, 0xae, 0x03, 0xce, 0xd2, 0xfc, 0x0e, 0x06, 0x5a, 0x11, 0x72, 0x95, 0x00, 0x7b, 0x35,
	0x17, 0x07, 0x54, 0xd4, 0xf3, 0x4a, 0x11, 0x95, 0x54, 0xeb, 0xfc, 0x2b, 0xfd, 0x35, 0x82, 0xc5,
	0xd8, 0x81, 0x75, 0xe6, 0x89, 0x80, 0xb9, 0x2e, 0x09, 0x24, 0x7e, 0x3c, 0x42, 0x50, 0xb0, 0x9b,
	0x8b, 0x24, 0xfe, 0xec, 0x64, 0xf4, 0x47, 0x86, 0x6e, 0xcd, 0xd8, 0x32, 0x5e, 0xfa, 0x1b, 0x04,
	0x7f, 0xc4, 0xdc, 0xaf, 0xf8, 0xbe, 0x4b, 0xed, 0x78, 0x43, 0x77, 0xf2, 0x8f, 0x11, 0xcc, 0xe2,
	0xb3, 0x55, 0x12, 0xf6, 0xbb, 0x19, 0xd9, 0x4b, 0xf1, 0xad, 0x02, 0x96, 0x52, 0xd3, 0x5f, 0x21,
	0x58, 0x88, 0xf9, 0x6f, 0xe3, 0x2a, 0xe1, 0x3e, 0xb6, 0x65, 0xe2, 0x7e, 0x88, 0x60, 0xc6, 0x6b,
	0xac, 0x91, 0x70, 0xdf, 0xce, 0xc8, 0x5d, 0x82, 0x6d, 0xe5, 0x3d, 0x09, 0x29, 0xfd, 0x29, 0x82,
	0x62, 0xc2, 0x9b, 0x39, 0x32, 0xca, 0xf7, 0xe1, 0x47, 0x8f, 0x39, 0x32, 0xb2, 0x1b, 0x59, 0xc9,
	0x76, 0x00, 0x5a, 0x53, 0x5e, 0x27, 0x09, 0xfd, 0x04, 0xc1, 0x7c, 0x22, 0x6b, 0xb7, 0xc6, 0x85,
	0x54, 0xd3, 0x0f, 0x10, 0x4c, 0xdb, 0xf1, 0x0a, 0x09, 0xd3, 0xad, 0xac, 0x82, 0xee, 0x86, 0x6b,
	0xfd, 0x64, 0x77, 0xa5, 0xa3, 0xbf, 0x57, 0xe0, 0x97, 0x2d, 0xca, 0x85, 0x3c, 0x8b, 0x10, 0x98,
	0x0c, 0x2b, 0x42, 0xbd, 0x6c, 0x33, 0xcf, 0xa1, 0xe1, 0xa7, 0x3c, 0x2a, 0xa2, 0x52, 0x6e, 0xf9,
	0xff, 0x0b, 0x12, 0x8c, 0xcb, 0x8a, 0x71, 0x23, 0x34, 0xb2, 0xde, 0xb0, 0x61, 0x4d, 0x1c, 0xb5,
	0x3c, 0x6b, 0xb7, 0x21, 0xc7, 0x0e, 0xee, 0x10, 0x5b, 0x94, 0xc3, 0x5c, 0x9e, 0x57, 0xa2, 0x33,
	0x58, 0xbd, 0xf0, 0x19, 0x24, 0x85, 0xc0, 0xd8, 0x89, 0x6c, 0x5c, 0x27, 0x02, 0x5b, 0xc0, 0x9a,
	0xff, 0xb5, 0x0d, 0x18, 0xbb, 0x4b, 0x3d, 0x27, 0xaf, 0x16, 0x51, 0x69, 0x62, 0x79, 0xa5, 0x6f,
	0xb3, 0x9b, 0xd4, 0x73, 0xac, 0xc8, 0x44, 0x7b, 0x6a, 0x1b, 0xeb, 0x4c, 0x6d, 0x6f, 0x11, 0xfc,
	0x2a, 0x3b, 0x53, 0xee, 0x33, 0x8f, 0x13, 0xed, 0x4f, 0x18, 0x8f, 0xab, 0x4c, 0x72, 0x96, 0x9a,
	0x11, 0xd7, 0x1f, 0x23, 0xf0, 0x6d, 0x63, 0x2f, 0xfa, 0x62, 0x25, 0x2b, 0x64, 0x69, 0x5c, 0xf9,
	0xfe, 0x69, 0x5c, 0x7f, 0xa1, 0xc2, 0xef, 0xa1, 0x27, 0xa9, 0x29, 0x7a, 0x24, 0x92, 0x56, 0x91,
	0xdc, 0x83, 0x1f, 0x9a, 0x27, 0x4e, 0x9c, 0x72, 0xd8, 0x69, 0x44, 0x4a, 0x99, 0xc8, 0x9c, 0xe9,
	0xbb, 0x84, 0x80, 0x38, 0x37, 0xeb, 0x3e, 0x39, 0xd7, 0x1b, 0xc4, 0x2f, 0xf4, 0xcf, 0x08, 0x16,
	0x52, 0xa2, 0x96, 0x41, 0x86, 0x29, 0x55, 0x58, 0x19, 0x78, 0x15, 0x7e, 0xa9, 0xc6, 0x6e, 0xa6,
	0xd7, 0xe0, 0x91, 0x3a, 0x87, 0x48, 0x9d, 0x5f, 0x10, 0x2c, 0xa6, 0x85, 0x2d, 0x83, 0x3c, 0xd3,
	0xfa, 0x2c, 0xe5, 0x12, 0xfa, 0xac, 0xe7, 0x2a, 0xcc, 0x87, 0xae, 0xa6, 0x75, 0x59, 0x23, 0x7d,
	0x0e, 0x91, 0x3e, 0x3f, 0xa1, 0xb8, 0xe6, 0xc9, 0x83, 0x96, 0x41, 0x9d, 0xbd, 0xfb, 0x68, 0x65,
	0xc0, 0x7d, 0xf4, 0x89, 0x1a, 0x37, 0x28, 0x3d, 0xba, 0xe8, 0x91, 0x24, 0x87, 0x48, 0x92, 0xef,
	0x10, 0xcc, 0x49, 0xe3, 0x95, 0x41, 0x8d, 0xb2, 0x2b, 0x92, 0x32, 0x90, 0x2b, 0xd2, 0x33, 0x15,
	0x7e, 0x8b, 0xda, 0x93, 0x9e, 0x17, 0xa4, 0x91, 0x00, 0x87, 0x48, 0x80, 0x1f, 0x10, 0xe8, 0xbd,
	0x42, 0x96, 0x41, 0x83, 0xbd, 0x2e, 0xc0, 0xca, 0x00, 0x2f, 0xc0, 0x1f, 0x11, 0x14, 0x42, 0xd7,
	0x2e, 0x57, 0x86, 0xfb, 0x90, 0x8b, 0xa7, 0x92, 0x0d, 0x19, 0x86, 0x10, 0xff, 0x5d, 0x10, 0x22,
	0x99, 0x67, 0x1a, 0x7b, 0xd1, 0x6f, 0x2c, 0x42, 0xde, 0xfc, 0xaf, 0x9f, 0x22, 0x98, 0xed, 0xea,
	0x61, 0x86, 0xa8, 0xf1, 0xce, 0x61, 0xe7, 0xb7, 0x25, 0x0d, 0x8b, 0x60, 0x27, 0x65, 0xd6, 0xb9,
	0xb6, 0xb9, 0xbf, 0x51, 0xa1, 0x22, 0x39, 0x4c, 0xf3, 0x0c, 0xe7, 0x2f, 0x4c, 0x4d, 0xec, 0x53,
	0xb3, 0x9f, 0xe9, 0xf2, 0xc1, 0x78, 0x34, 0xd6, 0xfd, 0xe7, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0x23, 0x2d, 0x5c, 0x7f, 0x17, 0x00, 0x00,
}
